"""Deterministically rebalance generated regression case shards."""

from __future__ import annotations

import argparse
import ast
import os
import pathlib
import subprocess
from typing import Dict, Iterable, List, Sequence, Tuple, Union


MODEL_MODULES = ("model", "model_index")
LIFECYCLE_MODULES = ("lifecycle", "lifecycle_2", "lifecycle_3", "lifecycle_4")
GOVERNANCE_MODULES = ("governance", "governance_2", "governance_3", "governance_4")
MODEL_SOURCE_PATHS = tuple(
    "tools/codex_assets/knowledge_hub/regression/{}.py".format(name)
    for name in MODEL_MODULES
)
LIFECYCLE_SOURCE_PATHS = tuple(
    "tools/codex_assets/knowledge_hub/regression/{}.py".format(name)
    for name in LIFECYCLE_MODULES
)
GOVERNANCE_SOURCE_PATHS = tuple(
    "tools/codex_assets/knowledge_hub/regression/{}.py".format(name)
    for name in GOVERNANCE_MODULES
)
DEFAULT_SOURCE_PATHS = (
    MODEL_SOURCE_PATHS + LIFECYCLE_SOURCE_PATHS + GOVERNANCE_SOURCE_PATHS
)
_FunctionNode = Union[ast.FunctionDef, ast.AsyncFunctionDef]
_TestBlock = Tuple[str, str]


def _source_from_git(root: pathlib.Path, revision: str, path: str) -> str:
    result = subprocess.run(
        ["rtk", "git", "show", "{}:{}".format(revision, path)],
        cwd=str(root),
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "unable to read {}:{}: {}".format(
                revision,
                path,
                result.stderr.strip(),
            )
        )
    return result.stdout


def _slice(lines: Sequence[str], node: _FunctionNode) -> str:
    if node.end_lineno is None:
        raise RuntimeError("Python AST node is missing end_lineno")
    return "".join(lines[node.lineno - 1 : node.end_lineno])


def _test_blocks(source: str) -> List[_TestBlock]:
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)
    blocks: List[_TestBlock] = []
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if not node.name.startswith("test_"):
            continue
        blocks.append((node.name, _slice(lines, node).rstrip()))
    return blocks


def _line_count(block: str) -> int:
    return block.count("\n") + 1


def _balanced_partitions(
    blocks: Sequence[_TestBlock],
    part_count: int,
) -> List[List[_TestBlock]]:
    if part_count < 2:
        raise RuntimeError("generated shard count must be at least two")
    if len(blocks) < part_count:
        raise RuntimeError(
            "at least {} generated tests are required for sharding".format(part_count)
        )
    total_lines = sum(_line_count(block) for _, block in blocks)
    indexes = [0]
    start = 0
    for part in range(1, part_count):
        target = total_lines * part / float(part_count)
        prefix_lines = sum(_line_count(block) for _, block in blocks[:start])
        best_index = start + 1
        best_delta = float("inf")
        last_allowed = len(blocks) - (part_count - part)
        for index in range(start + 1, last_allowed + 1):
            candidate = prefix_lines + sum(
                _line_count(block) for _, block in blocks[start:index]
            )
            delta = abs(candidate - target)
            if delta < best_delta:
                best_index = index
                best_delta = delta
            if candidate >= target and delta > best_delta:
                break
        indexes.append(best_index)
        start = best_index
    indexes.append(len(blocks))
    return [
        list(blocks[indexes[index] : indexes[index + 1]])
        for index in range(part_count)
    ]


def _render_module(name: str, blocks: Sequence[_TestBlock]) -> str:
    title = name.replace("_", " ")
    header = (
        '"""Generated regression cases: {}."""\n\n'
        "# Generated by regression_codegen.py; edit assertions here, then keep the generator deterministic.\n"
        "from .support import *  # noqa: F401,F403\n\n"
    ).format(title)
    body = "\n\n".join(block for _, block in blocks)
    return header + body + ("\n" if body else "")


def _rebalance_sources(
    module_names: Sequence[str],
    sources: Sequence[str],
) -> Dict[str, str]:
    if len(sources) != len(module_names):
        raise RuntimeError(
            "expected {} generated sources, got {}".format(
                len(module_names),
                len(sources),
            )
        )
    blocks: List[_TestBlock] = []
    for source in sources:
        blocks.extend(_test_blocks(source))
    if not blocks:
        raise RuntimeError("no top-level generated test functions found")
    names = [name for name, _ in blocks]
    duplicate_names = sorted(name for name in set(names) if names.count(name) > 1)
    if duplicate_names:
        raise RuntimeError(
            "duplicate generated tests: {}".format(", ".join(duplicate_names))
        )
    partitions = _balanced_partitions(blocks, len(module_names))
    return {
        module_name: _render_module(module_name, partition)
        for module_name, partition in zip(module_names, partitions)
    }


def rebalance_model_sources(sources: Sequence[str]) -> Dict[str, str]:
    return _rebalance_sources(MODEL_MODULES, sources)


def rebalance_lifecycle_sources(sources: Sequence[str]) -> Dict[str, str]:
    return _rebalance_sources(LIFECYCLE_MODULES, sources)


def rebalance_governance_sources(sources: Sequence[str]) -> Dict[str, str]:
    return _rebalance_sources(GOVERNANCE_MODULES, sources)


def _atomic_write(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        handle.write(content)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(str(temporary), str(path))


def _normalize_source_paths(source_paths: Sequence[str]) -> Tuple[str, ...]:
    paths = tuple(source_paths)
    if len(paths) == len(DEFAULT_SOURCE_PATHS):
        return paths
    if len(paths) == len(MODEL_MODULES):
        return paths + LIFECYCLE_SOURCE_PATHS + GOVERNANCE_SOURCE_PATHS
    if len(paths) == len(LIFECYCLE_MODULES):
        return MODEL_SOURCE_PATHS + paths + GOVERNANCE_SOURCE_PATHS
    if len(paths) == len(MODEL_MODULES) + len(LIFECYCLE_MODULES):
        return paths + GOVERNANCE_SOURCE_PATHS
    raise RuntimeError(
        "source paths must contain 2 model, 4 lifecycle, 6 model+lifecycle, "
        "or all 10 generated shard paths"
    )


def generate(
    root: pathlib.Path,
    revision: str,
    source_paths: Sequence[str] = DEFAULT_SOURCE_PATHS,
) -> List[str]:
    normalized_paths = _normalize_source_paths(source_paths)
    sources = [_source_from_git(root, revision, path) for path in normalized_paths]
    model_end = len(MODEL_MODULES)
    lifecycle_end = model_end + len(LIFECYCLE_MODULES)
    rendered = rebalance_model_sources(sources[:model_end])
    rendered.update(rebalance_lifecycle_sources(sources[model_end:lifecycle_end]))
    rendered.update(rebalance_governance_sources(sources[lifecycle_end:]))
    output_root = root / "tools/codex_assets/knowledge_hub/regression"
    outputs = {
        output_root / (name + ".py"): content for name, content in rendered.items()
    }
    for path, content in outputs.items():
        _atomic_write(path, content)
    return [str(path.relative_to(root)) for path in sorted(outputs)]


def main(argv: Iterable[str] = ()) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default="")
    parser.add_argument("--revision", default="HEAD")
    parser.add_argument(
        "--source-path",
        action="append",
        dest="source_paths",
        help=(
            "generated Python path inside the selected Git revision; pass 2 model, "
            "4 lifecycle, legacy 6 model+lifecycle, or all 10 generated shard paths "
            "to override defaults"
        ),
    )
    args = parser.parse_args(list(argv) if argv else None)
    root = pathlib.Path(
        args.root or pathlib.Path(__file__).resolve().parents[3]
    ).resolve()
    source_paths = args.source_paths or DEFAULT_SOURCE_PATHS
    try:
        normalized_paths = _normalize_source_paths(source_paths)
    except RuntimeError as exc:
        parser.error(str(exc))
    for path in generate(root, args.revision, normalized_paths):
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())