"""Deterministically rebalance generated regression model case shards."""

from __future__ import annotations

import argparse
import ast
import os
import pathlib
import subprocess
from typing import Dict, Iterable, List, Sequence, Tuple, Union


MODEL_MODULES = ("model", "model_index")
DEFAULT_SOURCE_PATHS = tuple(
    "tools/codex_assets/knowledge_hub/regression/{}.py".format(name)
    for name in MODEL_MODULES
)
_FunctionNode = Union[ast.FunctionDef, ast.AsyncFunctionDef]


def _source_from_git(root: pathlib.Path, revision: str, path: str) -> str:
    result = subprocess.run(
        ["rtk", "git", "show", "{}:{}".format(revision, path)],
        cwd=str(root),
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "unable to read {}:{}: {}".format(
                revision,
                path,
                result.stderr.strip(),
            )
        )
    return result.stdout


def _slice(lines: Sequence[str], node: _FunctionNode) -> str:
    if node.end_lineno is None:
        raise RuntimeError("Python AST node is missing end_lineno")
    return "".join(lines[node.lineno - 1 : node.end_lineno])


def _test_blocks(source: str) -> List[Tuple[str, str]]:
    tree = ast.parse(source)
    lines = source.splitlines(keepends=True)
    blocks: List[Tuple[str, str]] = []
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if not node.name.startswith("test_"):
            continue
        blocks.append((node.name, _slice(lines, node).rstrip()))
    return blocks


def _line_count(block: str) -> int:
    return block.count("\n") + 1


def _balanced_partition(
    blocks: Sequence[Tuple[str, str]],
) -> Tuple[List[Tuple[str, str]], List[Tuple[str, str]]]:
    if len(blocks) < 2:
        raise RuntimeError("at least two generated model tests are required for sharding")
    total_lines = sum(_line_count(block) for _, block in blocks)
    prefix_lines = 0
    best_index = 1
    best_delta = total_lines
    for index, (_, block) in enumerate(blocks[:-1], start=1):
        prefix_lines += _line_count(block)
        delta = abs(total_lines - (2 * prefix_lines))
        if delta < best_delta:
            best_index = index
            best_delta = delta
    return list(blocks[:best_index]), list(blocks[best_index:])


def _render_module(name: str, blocks: Sequence[Tuple[str, str]]) -> str:
    title = name.replace("_", " ")
    header = (
        '"""Generated regression cases: {}."""\n\n'
        "# Generated by regression_codegen.py; edit assertions here, then keep the generator deterministic.\n"
        "from .support import *  # noqa: F401,F403\n\n"
    ).format(title)
    body = "\n\n".join(block for _, block in blocks)
    return header + body + ("\n" if body else "")


def rebalance_model_sources(sources: Sequence[str]) -> Dict[str, str]:
    if len(sources) != len(MODEL_MODULES):
        raise RuntimeError(
            "expected {} generated model sources, got {}".format(
                len(MODEL_MODULES),
                len(sources),
            )
        )
    blocks: List[Tuple[str, str]] = []
    for source in sources:
        blocks.extend(_test_blocks(source))
    if not blocks:
        raise RuntimeError("no top-level generated model test functions found")
    names = [name for name, _ in blocks]
    duplicate_names = sorted(
        name for name in set(names) if names.count(name) > 1
    )
    if duplicate_names:
        raise RuntimeError(
            "duplicate generated model tests: {}".format(", ".join(duplicate_names))
        )
    first, second = _balanced_partition(blocks)
    return {
        MODEL_MODULES[0]: _render_module(MODEL_MODULES[0], first),
        MODEL_MODULES[1]: _render_module(MODEL_MODULES[1], second),
    }


def _atomic_write(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        handle.write(content)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(str(temporary), str(path))


def generate(
    root: pathlib.Path,
    revision: str,
    source_paths: Sequence[str] = DEFAULT_SOURCE_PATHS,
) -> List[str]:
    sources = [_source_from_git(root, revision, path) for path in source_paths]
    rendered = rebalance_model_sources(sources)
    output_root = root / "tools/codex_assets/knowledge_hub/regression"
    outputs = {
        output_root / (name + ".py"): content
        for name, content in rendered.items()
    }
    for path, content in outputs.items():
        _atomic_write(path, content)
    return [str(path.relative_to(root)) for path in sorted(outputs)]


def main(argv: Iterable[str] = ()) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default="")
    parser.add_argument("--revision", default="HEAD")
    parser.add_argument(
        "--source-path",
        action="append",
        dest="source_paths",
        help=(
            "generated model Python path inside the selected Git revision; "
            "pass twice to override the default model/model_index pair"
        ),
    )
    args = parser.parse_args(list(argv) if argv else None)
    root = pathlib.Path(
        args.root or pathlib.Path(__file__).resolve().parents[3]
    ).resolve()
    source_paths = args.source_paths or DEFAULT_SOURCE_PATHS
    if len(source_paths) != len(MODEL_MODULES):
        parser.error("--source-path must be supplied exactly twice when overridden")
    for path in generate(root, args.revision, source_paths):
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
