"""Generated regression cases: governance 2."""

# Generated by regression_codegen.py; edit assertions here, then keep the generator deterministic.
from .support import *  # noqa: F401,F403

def test_owner_summary_all_open():
    repo = copy_repo_with_open_owner_gates("owner-summary-all-open")
    result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-owner-gates.sh",
            "--source-id",
            "pcr02-project-docs",
            "--summary",
            "--json",
        ],
    )
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    summary = parsed.get("owner_summary", {})
    summary_rows = summary.get("rows", [])
    owner_dispatch = summary.get("owner_dispatch", [])
    dispatch_by_owner = {row.get("owner"): row for row in owner_dispatch}
    project_owner_dispatch = dispatch_by_owner.get("project-owner", {})
    project_owner_route = project_owner_dispatch.get("owner_route", {})
    first = summary_rows[0] if summary_rows else {}
    first_owner_route = first.get("owner_route", {})
    expect(
        result["exit_code"] == 0
        and parsed.get("row_count") == 7
        and parsed.get("open_count") == 7
        and parsed.get("status") == "ok"
        and parsed.get("status_scope") == "tool-health"
        and parsed.get("owner_review_status") == "needs-owner-review"
        and parsed.get("owner_gate_status") == "owner-gates-open"
        and summary.get("status") == "needs-owner-review"
        and summary.get("row_count") == 7
        and summary.get("open_count") == 7
        and summary.get("active_exposure_count") == 0
        and summary.get("owner_ready_package_count") == 7
        and summary.get("owner_ready_missing_count") == 0
        and summary.get("owner_ready_invalid_count") == 0
        and summary.get("owner_ready_duplicate_count") == 0
        and summary.get("owner_ready_package_coverage") == "7/7"
        and summary.get("source_identity_counts", {}).get("match") == 7
        and len(owner_dispatch) == 6
        and project_owner_dispatch.get("open_count") == 2
        and project_owner_route.get("routing_owner") == "pcr02-registry-owner"
        and project_owner_route.get("no_owner_decision_generated") is True
        and "pcr02-owner-decision-worksheet-005" in project_owner_dispatch.get("worksheet_ids", [])
        and "--owner project-owner --forms-jsonl" in project_owner_dispatch.get("forms_jsonl_command", "")
        and "--owner project-owner --validate-forms '<owner-decisions.jsonl>' --json" in project_owner_dispatch.get("validate_forms_command_template", "")
        and "--owner project-owner --validate-forms '<owner-decisions.jsonl>' --landing-plan --json" in project_owner_dispatch.get("landing_plan_command_template", "")
        and "--owner project-owner --validate-forms '<owner-decisions.jsonl>' --landing-audit --json" in project_owner_dispatch.get("landing_audit_command_template", "")
        and "--owner project-owner --worksheet-id pcr02-owner-decision-worksheet-005 --checklist --forms" in project_owner_dispatch.get("next_focus_command", "")
        and len(summary_rows) == 7
        and first.get("worksheet_id") == "pcr02-owner-decision-worksheet-001"
        and first_owner_route.get("decision_owner_role") == "team-core-or-pcr02-docs-owner"
        and first_owner_route.get("routing_owner") == "pcr02-registry-owner"
        and first_owner_route.get("no_owner_decision_generated") is True
        and first.get("owner_ready_package_status") == "covered"
        and first.get("owner_ready_package_count") == 1
        and first.get("owner_ready_packages", [{}])[0].get("status") == "valid"
        and first.get("owner_ready_packages", [{}])[0].get("decision") == "owner-ready-no-decision"
        and first.get("owner_ready_packages", [{}])[0].get("open_gate_remains") is True
        and first.get("owner_ready_packages", [{}])[0].get("identity_status") == "match"
        and first.get("required_owner_field_count") == 13
        and "--owner team-core-or-pcr02-docs-owner" in first.get("focus_command", "")
        and "--worksheet-id pcr02-owner-decision-worksheet-001 --checklist --forms" in first.get("focus_command", "")
        and "decision_forms" not in parsed
        and "owner_checklists" not in parsed,
        "owner-summary-all-open",
        "owner summary gives all open gates without emitting forms or closing gates",
        {
            "exit_code": result["exit_code"],
            "status": parsed.get("status"),
            "status_scope": parsed.get("status_scope"),
            "owner_review_status": parsed.get("owner_review_status"),
            "owner_gate_status": parsed.get("owner_gate_status"),
            "row_count": parsed.get("row_count"),
            "open_count": parsed.get("open_count"),
            "summary_status": summary.get("status"),
            "summary_row_count": summary.get("row_count"),
            "owner_ready_package_coverage": summary.get("owner_ready_package_coverage"),
            "owner_ready_missing_count": summary.get("owner_ready_missing_count"),
            "owner_ready_invalid_count": summary.get("owner_ready_invalid_count"),
            "owner_ready_duplicate_count": summary.get("owner_ready_duplicate_count"),
            "identity_counts": summary.get("source_identity_counts", {}),
            "owner_dispatch": owner_dispatch,
            "first": first,
            "has_decision_forms": "decision_forms" in parsed,
            "has_owner_checklists": "owner_checklists" in parsed,
            "stdout_sample": result["stdout"][:1000],
        },
    )

def test_owner_summary_by_owner():
    repo = copy_repo_with_open_owner_gates("owner-summary-by-owner")
    result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-owner-gates.sh",
            "--source-id",
            "pcr02-project-docs",
            "--owner",
            "project-owner",
            "--summary",
            "--json",
        ],
    )
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    summary = parsed.get("owner_summary", {})
    summary_rows = summary.get("rows", [])
    owner_dispatch = summary.get("owner_dispatch", [])
    dispatch = owner_dispatch[0] if owner_dispatch else {}
    handoff_packet = dispatch.get("suggested_owner_packet", {})
    owners = {row.get("owner") for row in parsed.get("rows", [])}
    worksheet_ids = {row.get("worksheet_id") for row in summary_rows}
    expect(
        result["exit_code"] == 0
        and parsed.get("owner") == "project-owner"
        and parsed.get("row_count") == 2
        and parsed.get("open_count") == 2
        and summary.get("row_count") == 2
        and summary.get("open_count") == 2
        and summary.get("owner_counts", {}).get("project-owner") == 2
        and len(owner_dispatch) == 1
        and dispatch.get("owner") == "project-owner"
        and dispatch.get("open_count") == 2
        and handoff_packet.get("status") == "ready-for-owner-review"
        and handoff_packet.get("read_only") is True
        and handoff_packet.get("suggested_local_owner_decisions_path") == "artifacts/manifests/pcr02-project-docs-project-owner-owner-decisions-YYYYMMDD.local.jsonl"
        and len(handoff_packet.get("recommended_sequence", [])) == 7
        and any(step.get("step") == "1-open-owner-inbox" and "--owner-inbox --json" in step.get("command", "") for step in handoff_packet.get("recommended_sequence", []))
        and any(step.get("step") == "4-export-forms" and "--forms-jsonl" in step.get("command", "") for step in handoff_packet.get("recommended_sequence", []))
        and any("不得由工具或 AI 代签 owner decision" in rule for rule in handoff_packet.get("must_not", []))
        and "--owner project-owner --forms-jsonl" in dispatch.get("forms_jsonl_command", "")
        and "--owner project-owner --validate-forms '<owner-decisions.jsonl>' --json" in dispatch.get("validate_forms_command_template", "")
        and "--owner project-owner --validate-forms '<owner-decisions.jsonl>' --landing-plan --json" in dispatch.get("landing_plan_command_template", "")
        and "--owner project-owner --validate-forms '<owner-decisions.jsonl>' --landing-audit --json" in dispatch.get("landing_audit_command_template", "")
        and owners == {"project-owner"}
        and worksheet_ids == {
            "pcr02-owner-decision-worksheet-005",
            "pcr02-owner-decision-worksheet-007",
        }
        and all("--owner project-owner" in row.get("focus_command", "") for row in summary_rows),
        "owner-summary-by-owner",
        "owner summary can filter open gates by exact owner",
        {
            "exit_code": result["exit_code"],
            "owner": parsed.get("owner"),
            "row_count": parsed.get("row_count"),
            "open_count": parsed.get("open_count"),
            "owner_counts": summary.get("owner_counts", {}),
            "owner_dispatch": owner_dispatch,
            "handoff_packet": handoff_packet,
            "worksheet_ids": sorted(worksheet_ids),
            "stdout_sample": result["stdout"][:1000],
        },
    )

def test_owner_handoff_packet_json():
    repo = copy_repo_with_open_owner_gates("owner-handoff-packet-json")
    result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-owner-gates.sh",
            "--source-id",
            "pcr02-project-docs",
            "--owner",
            "project-owner",
            "--handoff-packet",
            "--json",
        ],
    )
    text_result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-owner-gates.sh",
            "--source-id",
            "pcr02-project-docs",
            "--owner",
            "project-owner",
            "--handoff-packet",
        ],
    )
    status_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--json"])
    parsed = {}
    status_parsed = {}
    parse_error = ""
    status_parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    try:
        status_parsed = json.loads(status_result["stdout"])
    except Exception as exc:
        status_parse_error = str(exc)
    packets = parsed.get("owner_handoff_packets", []) if isinstance(parsed, dict) else []
    packet = packets[0] if packets else {}
    status_dispatch = status_parsed.get("owner_gates", {}).get("owner_dispatch", []) if isinstance(status_parsed, dict) else []
    project_owner_dispatch = next(
        (
            row for row in status_dispatch
            if row.get("owner") == "project-owner" and row.get("source_id") == "pcr02-project-docs"
        ),
        {},
    )
    forms_jsonl_lines = packet.get("forms_jsonl_lines", [])
    parsed_forms = []
    form_parse_errors = []
    for line in forms_jsonl_lines:
        try:
            parsed_forms.append(json.loads(line))
        except Exception as exc:
            form_parse_errors.append(str(exc))
    owner_inbox = packet.get("owner_inbox", {})
    evidence_readiness = packet.get("evidence_readiness", {})
    commands = packet.get("commands", {})
    expect(
        result["exit_code"] == 0
        and text_result["exit_code"] == 2
        and status_result["exit_code"] == 0
        and not parse_error
        and not status_parse_error
        and len(packets) == 1
        and packet.get("packet_type") == "owner-handoff"
        and packet.get("status") == "ready-for-owner-review"
        and packet.get("read_only") is True
        and packet.get("report_only") is True
        and packet.get("owner") == "project-owner"
        and packet.get("source_id") == "pcr02-project-docs"
        and packet.get("dispatch_scope_id") == "pcr02-project-docs:project-owner"
        and packet.get("source_ids") == ["pcr02-project-docs"]
        and packet.get("mixed_source_owner") is False
        and packet.get("open_count") == 2
        and packet.get("no_owner_decision_generated") is True
        and packet.get("no_owner_gate_closed") is True
        and packet.get("routing_owner_is_not_reviewed_by") is True
        and owner_inbox.get("row_count") == 2
        and evidence_readiness.get("row_count") == 2
        and len(forms_jsonl_lines) == 2
        and not form_parse_errors
        and {form.get("worksheet_id") for form in parsed_forms} == {
            "pcr02-owner-decision-worksheet-005",
            "pcr02-owner-decision-worksheet-007",
        }
        and all(not form.get("owner_decision") for form in parsed_forms)
        and "--owner project-owner --owner-inbox --json" in commands.get("owner_inbox_json_command", "")
        and "--owner project-owner --forms-jsonl" in commands.get("forms_jsonl_command", "")
        and "--owner project-owner --validate-forms '<owner-decisions.jsonl>' --json" in commands.get("validate_forms_command_template", "")
        and "--owner project-owner --handoff-packet --json" in project_owner_dispatch.get("handoff_packet_json_command", "")
        and any("不得由工具或 AI 代签 owner decision" in rule for rule in packet.get("must_not", []))
        and "decision_forms" not in parsed
        and "form_validation" not in parsed,
        "owner-handoff-packet-json",
        "owner gate helper emits a one-shot read-only handoff packet without generating owner decisions",
        {
            "exit_code": result["exit_code"],
            "text_exit_code": text_result["exit_code"],
            "status_exit_code": status_result["exit_code"],
            "parse_error": parse_error,
            "status_parse_error": status_parse_error,
            "packet": packet,
            "project_owner_dispatch": project_owner_dispatch,
            "form_parse_errors": form_parse_errors,
            "stdout_sample": result["stdout"][:1000],
            "text_stderr_sample": text_result["stderr"][:1000],
        },
    )

def test_owner_dispatch_source_scope_isolation():
    repo = copy_repo_with_open_owner_gates("owner-dispatch-source-scope-isolation")
    worksheet_path = repo / "artifacts" / "manifests" / "pcr02-owner-decision-worksheets-20260618.jsonl"
    rows = []
    for line in worksheet_path.read_text().splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        if row.get("id") == "pcr02-owner-decision-worksheet-007":
            row["source_id"] = "pcr02-project-tools"
        rows.append(row)
    worksheet_path.write_text("\n".join(json.dumps(row, ensure_ascii=False, separators=(",", ":")) for row in rows) + "\n")

    owner_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-owner-gates.sh", "--summary", "--json"])
    status_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--json"])
    owner_parsed = {}
    status_parsed = {}
    try:
        owner_parsed = json.loads(owner_result["stdout"])
    except Exception:
        pass
    try:
        status_parsed = json.loads(status_result["stdout"])
    except Exception:
        pass
    owner_dispatch = owner_parsed.get("owner_summary", {}).get("owner_dispatch", [])
    status_dispatch = status_parsed.get("owner_gates", {}).get("owner_dispatch", [])
    owner_project_dispatches = [row for row in owner_dispatch if row.get("owner") == "project-owner"]
    status_project_dispatches = [row for row in status_dispatch if row.get("owner") == "project-owner"]
    expected_sources = {"pcr02-project-docs", "pcr02-project-tools"}

    def scoped_dispatch_ok(dispatch_rows):
        source_ids = {row.get("source_id") for row in dispatch_rows}
        commands_ok = all(
            row.get("source_id")
            and f"--source-id {row.get('source_id')}" in row.get("owner_inbox_json_command", "")
            and f"--source-id {row.get('source_id')}" in row.get("forms_jsonl_command", "")
            and row.get("dispatch_scope_id") == f"{row.get('source_id')}:project-owner"
            and row.get("source_ids") == [row.get("source_id")]
            and row.get("mixed_source_owner") is False
            for row in dispatch_rows
        )
        worksheet_scope_ok = all(
            (
                row.get("source_id") == "pcr02-project-docs"
                and row.get("worksheet_ids") == ["pcr02-owner-decision-worksheet-005"]
            )
            or (
                row.get("source_id") == "pcr02-project-tools"
                and row.get("worksheet_ids") == ["pcr02-owner-decision-worksheet-007"]
            )
            for row in dispatch_rows
        )
        return len(dispatch_rows) == 2 and source_ids == expected_sources and commands_ok and worksheet_scope_ok

    expect(
        owner_result["exit_code"] == 0
        and status_result["exit_code"] in {0, 1}
        and scoped_dispatch_ok(owner_project_dispatches)
        and scoped_dispatch_ok(status_project_dispatches),
        "owner-dispatch-source-scope-isolation",
        "owner dispatch keeps same-owner multi-source gates in separate executable source scopes",
        {
            "owner_exit_code": owner_result["exit_code"],
            "status_exit_code": status_result["exit_code"],
            "owner_project_dispatches": owner_project_dispatches,
            "status_project_dispatches": status_project_dispatches,
            "owner_stdout_sample": owner_result["stdout"][:1200],
            "status_stdout_sample": status_result["stdout"][:1200],
        },
        repo,
    )

def test_owner_next_open_focus():
    repo = copy_repo_with_open_owner_gates("owner-next-open-focus")
    result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-owner-gates.sh",
            "--source-id",
            "pcr02-project-docs",
            "--next-open",
            "--checklist",
            "--forms",
            "--json",
        ],
    )
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    checklists = parsed.get("owner_checklists", [])
    forms = parsed.get("decision_forms", [])
    first_row = parsed.get("rows", [{}])[0] if parsed.get("rows") else {}
    first_form = forms[0] if forms else {}
    expect(
        result["exit_code"] == 0
        and parsed.get("next_open") is True
        and parsed.get("row_count") == 1
        and parsed.get("open_count") == 1
        and len(checklists) == 1
        and len(forms) == 1
        and first_row.get("id") == "pcr02-owner-decision-worksheet-001"
        and first_form.get("worksheet_id") == "pcr02-owner-decision-worksheet-001"
        and "是否确认" in first_form.get("owner_question_zh", ""),
        "owner-next-open-focus",
        "owner gate helper focuses next open worksheet without manual worksheet id",
        {
            "exit_code": result["exit_code"],
            "next_open": parsed.get("next_open"),
            "row_count": parsed.get("row_count"),
            "open_count": parsed.get("open_count"),
            "worksheet_id": first_row.get("id"),
            "form_count": len(forms),
            "checklist_count": len(checklists),
            "stdout_sample": result["stdout"][:1000],
        },
    )

def test_stable_governance_command_examples():
    scan_paths = [
        "README.md",
        "tools/README.md",
        "templates/README.md",
        "governance",
        "indexes",
    ]
    banned_patterns = [
        ("repo-relative-tool-command", "rtk bash tools/"),
        ("short-knowledge-check-command", "`knowledge-check --dry-run"),
        ("bare-knowledge-check-command", "knowledge-check --dry-run --json --diagnostics"),
        ("weak-validation-ref", 'validation_refs":["tools/knowledge-check.sh --dry-run'),
    ]
    findings = []
    for relative in scan_paths:
        path = root / relative
        paths = [path]
        if path.is_dir():
            paths = sorted(child for child in path.rglob("*") if child.is_file())
        for file_path in paths:
            try:
                text = file_path.read_text()
            except Exception as exc:
                findings.append({
                    "file": str(file_path.relative_to(root)),
                    "pattern_id": "read-error",
                    "line": 0,
                    "sample": str(exc),
                })
                continue
            for line_no, line in enumerate(text.splitlines(), 1):
                for pattern_id, needle in banned_patterns:
                    if needle not in line:
                        continue
                    if needle == "knowledge-check --dry-run --json --diagnostics" and "rtk bash ~/knowledge-hub/tools/knowledge-check.sh --dry-run --json --diagnostics" in line:
                        continue
                    findings.append({
                        "file": str(file_path.relative_to(root)),
                        "pattern_id": pattern_id,
                        "line": line_no,
                        "sample": line.strip()[:240],
                    })
    expect(
        not findings,
        "stable-governance-command-examples",
        "governance docs and templates use cwd-stable rtk command examples",
        {
            "scan_paths": scan_paths,
            "banned_patterns": [row[0] for row in banned_patterns],
            "findings": findings,
        },
    )

def test_final_gap_readability_positive_contracts():
    if os.environ.get("KNOWLEDGE_FINAL_GATE_INNER_REGRESSION") == "1":
        expect(
            True,
            "final-gap-readability-positive-contracts",
            "final gap readability contract is skipped inside nested regression",
            {"skipped_in_inner_final_gate": True},
        )
        return
    check_result = run_cmd(root, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    final_result = run_cmd(
        root,
        ["rtk", "bash", "-lc", "KNOWLEDGE_FINAL_GATE_INNER_REGRESSION=1 rtk bash tools/knowledge-final-gate.sh --json"],
    )
    check_parsed = {}
    final_parsed = {}
    try:
        check_parsed = json.loads(check_result["stdout"])
    except Exception:
        pass
    try:
        final_parsed = json.loads(final_result["stdout"])
    except Exception:
        pass
    items_path = root / "registry" / "items.jsonl"
    sources_path = root / "registry" / "sources.json"
    retired_sources_path = root / "registry" / "retired-sources.jsonl"
    readability_fields = [
        "summary_zh",
        "primary_language",
        "source_language",
        "translation_status",
        "terminology_status",
    ]
    missing_readability_fields = []
    missing_source_fields = []
    try:
        for row in [json.loads(line) for line in items_path.read_text().splitlines() if line.strip()]:
            created_at = str(row.get("created_at", ""))
            if (
                created_at >= "2026-06-21"
                and row.get("domain") == "governance"
                and row.get("kind") == "audit"
            ):
                for field in readability_fields:
                    if not str(row.get(field, "")).strip():
                        missing_readability_fields.append(f"{row.get('id')}:{field}")
    except Exception as exc:
        missing_readability_fields.append(f"parse-error:{exc}")
    try:
        source_required_fields = ["owner", "review_after", "source_strategy", "final_disposition"]
        source_data = json.loads(sources_path.read_text())
        retired_source_rows = [
            json.loads(line)
            for line in retired_sources_path.read_text().splitlines()
            if line.strip()
        ]
        for source in source_data.get("sources", []) + retired_source_rows:
            source_id = str(source.get("id", ""))
            for field in source_required_fields:
                if not str(source.get(field, "")).strip():
                    missing_source_fields.append(f"{source_id}:{field}")
            if not str(source.get("check", "")).strip() and not str(source.get("no_check_reason", "")).strip():
                missing_source_fields.append(f"{source_id}:check_or_no_check_reason")
    except Exception as exc:
        missing_source_fields.append(f"parse-error:{exc}")
    gap_map = final_parsed.get("gap_map", [])
    non_owner_gaps = [
        gap
        for gap in gap_map
        if gap.get("requires_owner_decision") is not True
        and gap.get("gap_type") not in {"owner-review"}
    ]
    terminal_gap_contracts = {
        "local-delivery-evidence-pending": ("delivery", True),
        "remote-publish-evidence-pending": ("remote-publish", False),
        "offsite-restore-evidence-pending": ("offsite-recovery", False),
        "real-adoption-evidence-pending": ("adoption", False),
    }
    expected_delivery_gaps = [
        gap for gap in non_owner_gaps if gap.get("gap_id") in terminal_gap_contracts
    ]
    expected_external_evidence_gaps = [
        gap for gap in non_owner_gaps if gap.get("gap_id") == "owner-and-real-evidence-pending"
    ]
    invalid_expected_gaps = [
        gap
        for gap in expected_delivery_gaps
        if (
            gap.get("gap_type"),
            gap.get("codex_auto_can_complete"),
        )
        != terminal_gap_contracts[str(gap.get("gap_id"))]
    ] + [
        gap
        for gap in expected_external_evidence_gaps
        if gap.get("gap_type") != "evidence" or gap.get("codex_auto_can_complete") is not False
    ]
    unexpected_non_owner_gaps = [
        gap
        for gap in non_owner_gaps
        if gap.get("gap_id")
        not in {*terminal_gap_contracts, "owner-and-real-evidence-pending"}
    ]
    expect(
        check_result["exit_code"] == 0
        and check_parsed.get("status") == "pass"
        and final_result["exit_code"] == 0
        and final_parsed.get("status") == "needs-review"
        and not missing_readability_fields
        and not missing_source_fields
        and len(expected_delivery_gaps) <= len(terminal_gap_contracts)
        and len(expected_external_evidence_gaps) <= 1
        and not invalid_expected_gaps
        and not unexpected_non_owner_gaps,
        "final-gap-readability-positive-contracts",
        "current repository exposes owner evidence and terminal delivery axes without hidden product gaps",
        {
            "knowledge_check_exit_code": check_result["exit_code"],
            "knowledge_check_status": check_parsed.get("status"),
            "final_gate_exit_code": final_result["exit_code"],
            "status": final_parsed.get("status"),
            "missing_readability_fields": missing_readability_fields,
            "missing_source_fields": missing_source_fields,
            "non_owner_gaps": non_owner_gaps,
            "expected_delivery_gaps": expected_delivery_gaps,
            "expected_external_evidence_gaps": expected_external_evidence_gaps,
            "invalid_expected_gaps": invalid_expected_gaps,
            "unexpected_non_owner_gaps": unexpected_non_owner_gaps,
            "final_stdout_sample": final_result["stdout"][:1200],
        },
    )
