"""Generated regression cases: governance 4."""

# Generated by regression_codegen.py; edit assertions here, then keep the generator deterministic.
from .support import *  # noqa: F401,F403

def test_no_user_absolute_path_persisted():
    scan_roots = [
        root / "AGENTS.md",
        root / "README.md",
        root / "docs",
        root / "domains",
        root / "governance",
        root / "indexes",
        root / "notes",
        root / "projects",
        root / "registry",
        root / "sources",
        root / "templates",
        root / "tools",
        root / "artifacts" / "manifests",
    ]
    suffixes = {".md", ".json", ".jsonl", ".sh", ".txt"}
    matches = []
    prefixes = user_path_prefixes()
    for base in scan_roots:
        if not base.exists():
            continue
        candidates = [base] if base.is_file() else base.rglob("*")
        for path in candidates:
            if not path.is_file() or path.suffix.lower() not in suffixes:
                continue
            try:
                text = path.read_text(errors="ignore")
            except Exception:
                continue
            if any(prefix in text for prefix in prefixes):
                matches.append(str(path.relative_to(root)))
    expect(
        not matches,
        "no-user-absolute-path-persisted",
        "persistent Knowledge Hub text does not contain user-specific absolute path prefixes",
        {"matches": matches[:20], "match_count": len(matches)},
    )

def test_user_path_redaction_in_tool_outputs():
    commands = [
        ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--as-of", today.isoformat()],
        ["rtk", "bash", "tools/knowledge-status.sh", "--json", "--as-of", today.isoformat(), "--review-queue-limit", "1"],
        ["rtk", "bash", "tools/knowledge-source-check.sh", "--json", "--plan", "--as-of", today.isoformat()],
        ["rtk", "bash", "tools/knowledge-search.sh", "Knowledge", "--json", "--limit", "1"],
    ]
    rows = []
    prefixes = user_path_prefixes()
    for command in commands:
        result = run_cmd(root, command)
        combined = result["stdout"] + result["stderr"]
        rows.append(
            {
                "command": " ".join(command),
                "exit_code": result["exit_code"],
                "has_forbidden_prefix": any(prefix in combined for prefix in prefixes),
            }
        )
    expect(
        all(row["exit_code"] == 0 and not row["has_forbidden_prefix"] for row in rows),
        "user-path-redaction-in-tool-outputs",
        "core read-only tool outputs redact user-specific absolute path prefixes",
        {"rows": rows},
    )

def test_source_control_directory_gate():
    repo = copy_repo("source-control-directory-gate")
    missing_path = repo / "sources" / "pcr02-project-docs" / "README.md"
    if missing_path.exists():
        missing_path.unlink()
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    combined = result["stdout"] + result["stderr"]
    expect(
        result["exit_code"] != 0
        and "source-control:pcr02-project-docs missing sources/pcr02-project-docs/README.md" in combined,
        "source-control-directory-gate",
        "knowledge-check rejects missing source control directory required files",
        {"exit_code": result["exit_code"], "stderr": result["stderr"][:500], "stdout": result["stdout"][:1000]},
        repo,
    )

def test_source_control_raw_copy_body_gate():
    repo = copy_repo("source-control-raw-copy-body-gate")
    inventory_path = repo / "sources" / "codex-raw-sessions" / "inventory.jsonl"
    fixture_row = {
        "id": "fixture-raw-session-copy-body",
        "source_id": "codex-raw-sessions",
        "source_path": "fixture-session.jsonl",
        "object_type": "session",
        "hub_disposition": "copy-body",
        "target_path": "sources/codex-raw-sessions/README.md",
        "status": "covered",
        "reason_zh": "fixture should fail because raw sessions cannot use copy-body",
        "risk_zh": "raw session body must not enter long-term body layer",
        "checked_at": today.isoformat(),
    }
    inventory_path.write_text(inventory_path.read_text() + json.dumps(fixture_row, ensure_ascii=False) + "\n")
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    combined = result["stdout"] + result["stderr"]
    expect(
        result["exit_code"] != 0
        and "source-control:codex-raw-sessions inventory row fixture-raw-session-copy-body raw/session/source-code/log/binary must not use copy-body" in combined,
        "source-control-raw-copy-body-gate",
        "knowledge-check rejects copy-body disposition for raw session/history/source-code/log/binary inventory rows",
        {"exit_code": result["exit_code"], "stderr": result["stderr"][:500], "stdout": result["stdout"][:1000]},
        repo,
    )

def test_owner_target_existence_gate():
    repo = copy_repo("owner-target-existence-gate")
    target_path = repo / "projects" / "xcrz-sigmastar-demo" / "current" / "runbooks" / "asan-debug-guide.md"
    if target_path.exists():
        target_path.unlink()
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    combined = result["stdout"] + result["stderr"]
    expect(
        result["exit_code"] != 0
        and "owner-target:pcr02-owner-decision-worksheet-003 target path missing: projects/xcrz-sigmastar-demo/current/runbooks/asan-debug-guide.md" in combined,
        "owner-target-existence-gate",
        "knowledge-check rejects missing owner decision landing target documents",
        {"exit_code": result["exit_code"], "stderr": result["stderr"][:500], "stdout": result["stdout"][:1000]},
        repo,
    )

def test_owner_target_materialization_read_only_no_source_dependency():
    repo = copy_repo("owner-target-materialization-read-only-no-source-dependency")
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-pcr02-owner-targets.sh", "--json"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    expect(
        result["exit_code"] == 0
        and parsed.get("status") == "planned"
        and parsed.get("read_only") is True
        and parsed.get("target_present_count") == 4
        and parsed.get("blocked_count") == 0
        and all(row.get("source_identity_source") == "owner-decision-landing-manifest" for row in parsed.get("results", [])),
        "owner-target-materialization-read-only-no-source-dependency",
        "knowledge-pcr02-owner-targets read-only mode uses landing manifest identity and does not require retired origin source files",
        {"exit_code": result["exit_code"], "stderr": result["stderr"][:500], "stdout": result["stdout"][:1000], "parse_error": parse_error},
        repo,
    )

def test_owner_decision_draft_leak_warning():
    repo = copy_repo("owner-decision-draft-leak-warning")
    draft_path = repo / "artifacts" / "manifests" / "fixture-owner-decision-landing-29990101.jsonl"
    draft_path.write_text(
        json.dumps(
            {
                "worksheet_id": "fixture-owner-decision-worksheet-001",
                "owner_decision": "reference-only",
                "target_decision": "no-local-copy",
                "reviewed_by": "fixture-owner",
                "reviewed_at": "2999-01-01",
                "status_reason": "fixture warning only",
            },
            ensure_ascii=False,
            separators=(",", ":"),
        ) + "\n"
    )
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics", "--as-of", "2026-06-23"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    warnings = parsed.get("warnings", []) if isinstance(parsed.get("warnings"), list) else []
    expect(
        result["exit_code"] == 0
        and parsed.get("status") == "pass"
        and not parse_error
        and any("owner-decision-draft:artifacts/manifests/fixture-owner-decision-landing-29990101.jsonl" in warning for warning in warnings),
        "owner-decision-draft-leak-warning",
        "knowledge-check warns about non-local owner decision drafts without closing owner gates",
        {
            "exit_code": result["exit_code"],
            "status": parsed.get("status"),
            "parse_error": parse_error,
            "warnings": warnings,
            "diagnostics": parsed.get("diagnostics", {}),
        },
        repo,
    )

def test_review_after_near_due_json_contract():
    repo = copy_repo_with_open_owner_gates("review-after-near-due-json-contract")
    seeded_count = seed_review_after_near_due_fixture(repo)
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-review-after.sh", "--json", "--as-of", "2026-06-22", "--window-days", "30"])
    owner_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-review-after.sh", "--json", "--as-of", "2026-06-22", "--window-days", "30", "--include-owner-gates"])
    parsed = {}
    owner_parsed = {}
    parse_error = ""
    owner_parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    try:
        owner_parsed = json.loads(owner_result["stdout"])
    except Exception as exc:
        owner_parse_error = str(exc)
    counts = parsed.get("counts", {}) if isinstance(parsed.get("counts"), dict) else {}
    groups = parsed.get("groups", {}) if isinstance(parsed.get("groups"), dict) else {}
    rows = parsed.get("rows", []) if isinstance(parsed.get("rows"), list) else []
    owner_counts = owner_parsed.get("counts", {}) if isinstance(owner_parsed.get("counts"), dict) else {}
    owner_rows = owner_parsed.get("rows", []) if isinstance(owner_parsed.get("rows"), list) else []
    owner_gate_rows = [row for row in owner_rows if row.get("row_type") == "open_owner_gate"]
    archived_rows = [row for row in rows if row.get("status") == "archived"]
    expect(
        result["exit_code"] == 0
        and owner_result["exit_code"] == 0
        and not parse_error
        and not owner_parse_error
        and parsed.get("status") == "report-only"
        and owner_parsed.get("status") == "report-only"
        and parsed.get("read_only") is True
        and parsed.get("report_only") is True
        and parsed.get("today") == "2026-06-22"
        and parsed.get("item_window_end") == "2026-07-22"
        and seeded_count == 27
        and counts.get("stale_items") == 0
        and counts.get("near_due_items") == 27
        and counts.get("stale_sources") == 0
        and counts.get("near_due_sources") == 0
        and counts.get("owner_gate_open_count") == 7
        and counts.get("detail_row_count") == 27
        and counts.get("missing_source_id_count") == 4
        and owner_counts.get("owner_gate_open_count") == 7
        and owner_counts.get("detail_row_count") == 34
        and len(owner_gate_rows) == 7
        and all(row.get("worksheet_file", "").endswith("owner-decision-worksheets-20260618.jsonl") for row in owner_gate_rows)
        and groups.get("grouping_contract_version") == 1
        and groups.get("by_owner", {}).get("team-core", {}).get("count") == 23
        and groups.get("by_owner", {}).get("leiwenjun", {}).get("count") == 4
        and groups.get("by_status", {}).get("reviewing", {}).get("count") == 13
        and groups.get("by_status", {}).get("archived", {}).get("count") == 14
        and groups.get("by_domain", {}).get("projects/xcrz-sigmastar-demo", {}).get("count") == 22
        and groups.get("by_domain", {}).get("projects/pcr02-ssc305", {}).get("count") == 5
        and groups.get("by_source_id", {}).get("pcr02-project-docs", {}).get("count") == 23
        and groups.get("by_source_id", {}).get("<missing-source-id>", {}).get("count") == 4
        and len(archived_rows) >= 1
        and all("source_status" in row for row in rows)
        and "archive-only" in str(
            groups.get("by_status", {})
            .get("archived", {})
            .get("suggested_action_zh", "")
        )
        and "不得把 ordinary near-due warning 当作 blocking error" in parsed.get("must_not", []),
        "review-after-near-due-json-contract",
        "review_after helper reports 30-day near-due items without creating a blocking gate",
        {
            "exit_code": result["exit_code"],
            "owner_exit_code": owner_result["exit_code"],
            "parse_error": parse_error,
            "owner_parse_error": owner_parse_error,
            "status": parsed.get("status"),
            "seeded_count": seeded_count,
            "counts": counts,
            "owner_counts": owner_counts,
            "groups": groups,
            "archived_row_count": len(archived_rows),
            "owner_gate_row_count": len(owner_gate_rows),
            "stderr_sample": result["stderr"][:500],
            "owner_stderr_sample": owner_result["stderr"][:500],
        },
    )

def test_automation_report_only_safety_gate():
    repo = copy_repo("automation-report-only-safety-gate")
    maintenance_path = repo / "registry" / "maintenance-runs.jsonl"
    rows = []
    try:
        for line in maintenance_path.read_text().splitlines():
            if not line.strip():
                continue
            row = json.loads(line)
            if row.get("automation_id") == "memory-auto-curation-report-only":
                row["enabled"] = True
                row["mode"] = "apply"
                row["writes_memory"] = True
                row["writes_team_active_index"] = True
                row.pop("no_memory_write_gate", None)
            rows.append(row)
        maintenance_path.write_text(
            "\n".join(json.dumps(row, ensure_ascii=False, separators=(",", ":")) for row in rows) + "\n"
        )
        setup_error = ""
    except Exception as exc:
        setup_error = str(exc)
    result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-check.sh",
            "--dry-run",
            "--json",
            "--diagnostics",
            "--as-of",
            today.isoformat(),
        ],
    )
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    errors = parsed.get("errors", [])
    health = parsed.get("automation_safety_health", {})
    expect(
        not setup_error
        and result["exit_code"] == 1
        and parsed.get("status") == "needs-fix"
        and "memory-auto-curation-20260618-definition" in health.get("unsafe_run_ids", [])
        and any("enabled must be false" in error for error in errors)
        and any("mode must be read-only/report-only/plan-only/local-commit/apply-with-review/forbidden" in error for error in errors)
        and any("no_memory_write_gate is required" in error for error in errors),
        "automation-report-only-safety-gate",
        "knowledge-check rejects enabled or memory-writing automation records",
        {
            "setup_error": setup_error,
            "exit_code": result["exit_code"],
            "status": parsed.get("status"),
            "automation_safety_health": health,
            "errors": errors,
            "stdout_sample": result["stdout"][:1200],
        },
        repo,
    )

def test_review_after_as_of_deterministic():
    if os.environ.get("KNOWLEDGE_FINAL_GATE_INNER_REGRESSION") == "1":
        expect(
            True,
            "review-after-as-of-deterministic",
            "review-after as-of fixture is skipped inside nested regression",
            {"skipped_in_inner_final_gate": True},
        )
        return
    repo = copy_repo("review-after-as-of")
    setup_error = init_temp_git_repo(repo)
    if setup_error:
        expect(False, "review-after-as-of-deterministic", "--as-of fixes review_after warning semantics for check/status/final-gate", setup_error, repo)
        return
    item_id = "pcr02-camera-raw-preview-virtual-stream-architecture-20260711"
    path = repo / "registry" / "items.jsonl"
    lines = path.read_text().splitlines()
    updated_lines = []
    mutated = False
    for line in lines:
        if not line.strip():
            updated_lines.append(line)
            continue
        row = json.loads(line)
        if row.get("id") == item_id:
            row["review_after"] = "2026-06-30"
            mutated = True
            updated_lines.append(json.dumps(row, ensure_ascii=False, separators=(",", ":")))
        else:
            updated_lines.append(line)
    if not mutated:
        expect(False, "review-after-as-of-deterministic", "--as-of fixes review_after warning semantics for check/status/final-gate", {"setup_error": f"missing {item_id}"}, repo)
        return
    path.write_text("\n".join(updated_lines) + "\n")
    sync_review_date_index_entries(repo, [item_id], "2026-06-30")
    body_path = (
        repo
        / "projects"
        / "xcrz-sigmastar-demo"
        / "decisions"
        / "camera-raw-preview-virtual-stream-architecture-20260711.md"
    )
    body_path.write_text(
        body_path.read_text().replace(
            "review_after: '2026-10-11'", "review_after: '2026-06-30'", 1
        )
    )

    past_check = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics", "--as-of", "2026-06-01"])
    future_check = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics", "--as-of", "2026-07-01"])
    past_status = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--json", "--as-of", "2026-06-01"])
    future_status = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--json", "--as-of", "2026-07-01"])
    final_result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-final-gate.sh",
            "--json",
            "--as-of",
            "2026-06-01",
        ],
    )
    parsed = {}
    parse_errors = {}
    for name, result in [
        ("past_check", past_check),
        ("future_check", future_check),
        ("past_status", past_status),
        ("future_status", future_status),
        ("final_gate", final_result),
    ]:
        try:
            parsed[name] = json.loads(result["stdout"])
        except Exception as exc:
            parse_errors[name] = str(exc)
    past_warnings = "\n".join(parsed.get("past_check", {}).get("warnings", []))
    future_warnings = "\n".join(parsed.get("future_check", {}).get("warnings", []))
    past_registry = parsed.get("past_status", {}).get("registry", {})
    future_registry = parsed.get("future_status", {}).get("registry", {})
    past_actions_text = "\n".join(parsed.get("past_status", {}).get("next_actions_zh", []))
    expect(
        not parse_errors
        and past_check["exit_code"] == 0
        and future_check["exit_code"] == 0
        and item_id not in past_warnings
        and item_id in future_warnings
        and parsed.get("past_check", {}).get("today") == "2026-06-01"
        and parsed.get("past_check", {}).get("as_of_source") == "arg:--as-of"
        and parsed.get("past_status", {}).get("today") == "2026-06-01"
        and parsed.get("past_status", {}).get("as_of_source") == "arg:--as-of"
        and parsed.get("past_status", {}).get("final_gate_command") == "rtk bash ~/knowledge-hub/tools/knowledge-final-gate.sh --as-of 2026-06-01 --json --final-profile product"
        and not any(row.get("id") == item_id for row in past_registry.get("stale_review_after_sample", []) if isinstance(row, dict))
        and any(row.get("id") == item_id for row in future_registry.get("stale_review_after_sample", []) if isinstance(row, dict))
        and parsed.get("final_gate", {}).get("as_of") == "2026-06-01"
        and parsed.get("final_gate", {}).get("checks", {}).get("knowledge_check", {}).get("status") == "pass",
        "review-after-as-of-deterministic",
        "--as-of fixes review_after warning semantics for check/status/final-gate",
        {
            "parse_errors": parse_errors,
            "past_check_exit": past_check["exit_code"],
            "future_check_exit": future_check["exit_code"],
            "past_status_exit": past_status["exit_code"],
            "future_status_exit": future_status["exit_code"],
            "final_gate_exit": final_result["exit_code"],
            "past_check_today": parsed.get("past_check", {}).get("today"),
            "past_status_today": parsed.get("past_status", {}).get("today"),
            "past_status_final_gate_command": parsed.get("past_status", {}).get("final_gate_command"),
            "past_actions_text": past_actions_text,
            "final_gate_as_of": parsed.get("final_gate", {}).get("as_of"),
            "final_gate_check_status": parsed.get("final_gate", {}).get("checks", {}).get("knowledge_check", {}).get("status"),
            "future_warning_sample": parsed.get("future_check", {}).get("warnings", [])[:5],
            "past_stale_count": past_registry.get("stale_review_after_count"),
            "future_stale_count": future_registry.get("stale_review_after_count"),
        },
        repo,
    )

def test_stale_review_after_warning_surface():
    repo = copy_repo("stale-review-after")
    item_id = "pcr02-camera-raw-preview-virtual-stream-architecture-20260711"
    path = repo / "registry" / "items.jsonl"
    lines = path.read_text().splitlines()
    updated_lines = []
    mutated = False
    for line in lines:
        if not line.strip():
            updated_lines.append(line)
            continue
        row = json.loads(line)
        if row.get("id") == item_id:
            row["review_after"] = "2026-01-01"
            mutated = True
            updated_lines.append(json.dumps(row, ensure_ascii=False, separators=(",", ":")))
        else:
            updated_lines.append(line)
    if not mutated:
        expect(False, "stale-review-after-warning-surface", "stale review_after is surfaced as warning and status action", {"setup_error": f"missing {item_id}"}, repo)
        return
    path.write_text("\n".join(updated_lines) + "\n")
    sync_review_date_index_entries(repo, [item_id], "2026-01-01")
    body_path = (
        repo
        / "projects"
        / "xcrz-sigmastar-demo"
        / "decisions"
        / "camera-raw-preview-virtual-stream-architecture-20260711.md"
    )
    body_path.write_text(
        body_path.read_text().replace(
            "review_after: '2026-10-11'", "review_after: '2026-01-01'", 1
        )
    )

    check_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    status_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--json"])
    check_payload = {}
    status_payload = {}
    parse_errors = {}
    try:
        check_payload = json.loads(check_result["stdout"])
    except Exception as exc:
        parse_errors["knowledge_check"] = str(exc)
    try:
        status_payload = json.loads(status_result["stdout"])
    except Exception as exc:
        parse_errors["knowledge_status"] = str(exc)
    warnings_text = "\n".join(check_payload.get("warnings", []))
    registry = status_payload.get("registry", {}) if isinstance(status_payload.get("registry"), dict) else {}
    stale_sample = registry.get("stale_review_after_sample", [])
    next_actions_text = "\n".join(status_payload.get("next_actions_zh", []))
    expect(
        not parse_errors
        and check_result["exit_code"] == 0
        and check_payload.get("status") == "pass"
        and item_id in warnings_text
        and "review_after is stale" in warnings_text
        and status_result["exit_code"] == 0
        and registry.get("stale_review_after_count", 0) >= 1
        and any(row.get("id") == item_id for row in stale_sample if isinstance(row, dict))
        and "review_after" in next_actions_text
        and "rtk bash ~/knowledge-hub/tools/knowledge-index-plan.sh --section review-date" in next_actions_text,
        "stale-review-after-warning-surface",
        "stale review_after is warning/status surface, not a blocking check failure",
        {
            "parse_errors": parse_errors,
            "knowledge_check_exit": check_result["exit_code"],
            "knowledge_check_status": check_payload.get("status"),
            "warning_count": len(check_payload.get("warnings", [])),
            "warning_sample": check_payload.get("warnings", [])[:5],
            "knowledge_status_exit": status_result["exit_code"],
            "status": status_payload.get("status"),
            "stale_review_after_count": registry.get("stale_review_after_count"),
            "stale_sample": stale_sample[:3] if isinstance(stale_sample, list) else stale_sample,
            "next_actions_sample": status_payload.get("next_actions_zh", [])[:5],
        },
        repo,
    )

def test_source_review_after_stale_surface():
    repo = copy_repo("source-review-after-stale")
    source_id = "pcr02-project-tools"
    if not update_source_registry_entry(repo, source_id, {"review_after": "2026-01-01"}):
        expect(False, "source-review-after-stale-surface", "stale source review_after is surfaced as warning and status action", {"setup_error": f"missing {source_id}"}, repo)
        return

    check_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    status_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--json"])
    check_payload = {}
    status_payload = {}
    parse_errors = {}
    try:
        check_payload = json.loads(check_result["stdout"])
    except Exception as exc:
        parse_errors["knowledge_check"] = str(exc)
    try:
        status_payload = json.loads(status_result["stdout"])
    except Exception as exc:
        parse_errors["knowledge_status"] = str(exc)
    warnings_text = "\n".join(check_payload.get("warnings", []))
    source_check_health = check_payload.get("source_check_health", {}) if isinstance(check_payload.get("source_check_health"), dict) else {}
    sources_status = status_payload.get("sources", {}) if isinstance(status_payload.get("sources"), dict) else {}
    stale_sample = sources_status.get("stale_review_after_sample", [])
    next_actions_text = "\n".join(status_payload.get("next_actions_zh", []))
    expect(
        not parse_errors
        and check_result["exit_code"] == 0
        and check_payload.get("status") == "pass"
        and f"sources:{source_id}" in warnings_text
        and "review_after is stale" in warnings_text
        and source_id in source_check_health.get("stale_review_after_ids", [])
        and status_result["exit_code"] == 0
        and sources_status.get("stale_review_after_count", 0) >= 1
        and any(row.get("id") == source_id for row in stale_sample if isinstance(row, dict))
        and sources_status.get("review_after_command") == "rtk bash ~/knowledge-hub/tools/knowledge-index-plan.sh --section source"
        and "registered source" in next_actions_text
        and "rtk bash ~/knowledge-hub/tools/knowledge-index-plan.sh --section source" in next_actions_text,
        "source-review-after-stale-surface",
        "stale source review_after is warning/status surface, not a blocking check failure",
        {
            "parse_errors": parse_errors,
            "knowledge_check_exit": check_result["exit_code"],
            "knowledge_check_status": check_payload.get("status"),
            "warning_sample": check_payload.get("warnings", [])[:5],
            "source_check_health": source_check_health,
            "knowledge_status_exit": status_result["exit_code"],
            "sources_status": sources_status,
            "next_actions_sample": status_payload.get("next_actions_zh", [])[:8],
        },
        repo,
    )

def test_embedded_asan_methodology_deprojectized():
    asan_path = root / "domains" / "embedded" / "runbooks" / "asan-debug-guide.md"
    try:
        text = asan_path.read_text()
    except Exception as exc:
        text = ""
        read_error = str(exc)
    else:
        read_error = ""
    banned = [
        "DEBUG=256",
        "prog_pcr02",
        "/customer/bin",
        "release/bin/prog_pcr02",
        "libs/3rdparty/libasan",
    ]
    required = [
        "AddressSanitizer",
        "ASAN_OPTIONS",
        "-fsanitize=address",
        "BuildID",
        "asan-offline-symbolize-guide.md",
        "团队级本文当前状态为 `active`",
        "不得仅凭单一项目 owner decision 自动提升到 `domains/embedded/standards/`",
    ]
    banned_hits = [token for token in banned if token in text]
    missing_required = [token for token in required if token not in text]
    expect(
        not read_error
        and not banned_hits
        and not missing_required
        and "status: active" in text
        and "projects/xcrz-sigmastar-demo/current/runbooks/asan-debug-guide.md" in text,
        "embedded-asan-methodology-deprojectized",
        "team-level ASAN methodology stays deprojectized with active runbook boundaries",
        {
            "read_error": read_error,
            "banned_hits": banned_hits,
            "missing_required": missing_required,
            "path": str(asan_path),
        },
    )
