"""Generated regression cases: governance 3."""

# Generated by regression_codegen.py; edit assertions here, then keep the generator deterministic.
from .support import *  # noqa: F401,F403

def test_owner_validate_forms_partial_coverage_warning():
    repo = copy_repo_with_open_owner_gates("owner-validate-forms-partial-coverage")
    form, setup_error = make_valid_owner_decision_form(repo)
    if setup_error:
        expect(False, "owner-validate-forms-partial-coverage-warning", "owner validate-forms reports partial coverage without blocking valid subset forms", setup_error, repo)
        return
    form_path = repo / "partial-owner-decisions.jsonl"
    form_path.write_text(json.dumps(form, ensure_ascii=False, separators=(",", ":")) + "\n")
    result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-owner-gates.sh",
            "--source-id",
            "pcr02-project-docs",
            "--validate-forms",
            str(form_path),
            "--landing-plan",
            "--landing-audit",
            "--json",
        ],
    )
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    validation = parsed.get("form_validation", {}) if isinstance(parsed, dict) else {}
    coverage = validation.get("coverage", {}) if isinstance(validation, dict) else {}
    landing_plan = parsed.get("landing_plan", {}) if isinstance(parsed, dict) else {}
    landing_audit = parsed.get("landing_audit", {}) if isinstance(parsed, dict) else {}
    expect(
        result["exit_code"] == 0
        and not parse_error
        and validation.get("status") == "pass"
        and validation.get("coverage_status") == "partial"
        and coverage.get("filtered_open_count") == 7
        and coverage.get("submitted_open_count") == 1
        and form.get("worksheet_id") in coverage.get("submitted_worksheet_ids", [])
        and len(coverage.get("missing_open_worksheet_ids", [])) == 6
        and validation.get("warning_count") == 1
        and landing_plan.get("status") == "planned"
        and landing_plan.get("landing_scope", {}).get("coverage_status") == "partial"
        and len(landing_plan.get("remaining_open_after_this_batch", [])) == 6
        and landing_audit.get("status") == "ready-for-manual-landing"
        and landing_audit.get("landing_scope", {}).get("coverage_status") == "partial"
        and len(landing_audit.get("remaining_open_after_this_batch", [])) == 6,
        "owner-validate-forms-partial-coverage-warning",
        "owner validate-forms reports partial coverage without blocking valid subset forms",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "form_status": validation.get("status"),
            "coverage": coverage,
            "warning_count": validation.get("warning_count"),
            "landing_plan_status": landing_plan.get("status"),
            "landing_scope": landing_plan.get("landing_scope", {}),
            "remaining_open_after_this_batch": landing_plan.get("remaining_open_after_this_batch", []),
            "landing_audit_status": landing_audit.get("status"),
            "stdout_sample": result["stdout"][:1200],
            "stderr_sample": result["stderr"][:1000],
        },
        repo,
    )

def test_owner_archive_only_explicit_path_contract():
    repo = copy_repo_with_open_owner_gates("owner-archive-only-target-path")
    form, setup_error = make_owner_decision_form_for_worksheet(repo, "pcr02-owner-decision-worksheet-007")
    if setup_error:
        expect(False, "owner-archive-only-explicit-path-contract", "owner archive-only forms can target explicit archive paths", setup_error, repo)
        return
    archive_target = "projects/xcrz-sigmastar-demo/archive/reports/2026-06-16-dvr-record-replay-session-archive.md"
    form["owner_decision"] = "archive-only"
    form["target_decision"] = archive_target
    form_path = repo / "archive-owner-decisions.jsonl"
    form_path.write_text(json.dumps(form, ensure_ascii=False, separators=(",", ":")) + "\n")
    result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-owner-gates.sh",
            "--source-id",
            "pcr02-project-docs",
            "--worksheet-id",
            "pcr02-owner-decision-worksheet-007",
            "--validate-forms",
            str(form_path),
            "--json",
        ],
    )
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    diagnostics = parsed.get("form_validation", {}).get("diagnostics", [])
    expect(
        result["exit_code"] == 0
        and parsed.get("form_validation", {}).get("status") == "pass"
        and not any(row.get("code") == "owner-decision-target-mismatch" for row in diagnostics),
        "owner-archive-only-explicit-path-contract",
        "owner archive-only forms can target explicit archive paths",
        {
            "exit_code": result["exit_code"],
            "validation_status": parsed.get("form_validation", {}).get("status"),
            "diagnostics": diagnostics,
            "target_decision": archive_target,
            "stdout_sample": result["stdout"][:1000],
        },
        repo,
    )

def test_owner_archive_only_rejects_non_archive_target():
    repo = copy_repo_with_open_owner_gates("owner-archive-only-rejects-non-archive")
    form, setup_error = make_owner_decision_form_for_worksheet(repo, "pcr02-owner-decision-worksheet-007")
    if setup_error:
        expect(False, "owner-archive-only-rejects-non-archive-target", "owner archive-only forms reject validation or decision targets", setup_error, repo)
        return
    form["owner_decision"] = "archive-only"
    form["target_decision"] = "projects/pcr02-ssc305/validation/"
    form_path = repo / "archive-owner-decisions.jsonl"
    form_path.write_text(json.dumps(form, ensure_ascii=False, separators=(",", ":")) + "\n")
    result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-owner-gates.sh",
            "--source-id",
            "pcr02-project-docs",
            "--worksheet-id",
            "pcr02-owner-decision-worksheet-007",
            "--validate-forms",
            str(form_path),
            "--json",
        ],
    )
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    diagnostics = parsed.get("form_validation", {}).get("diagnostics", [])
    mismatch_diagnostic = next(
        (
            row for row in diagnostics
            if row.get("code") == "owner-decision-target-mismatch"
            and row.get("field") == "target_decision"
        ),
        {},
    )
    expect(
        result["exit_code"] == 1
        and parsed.get("form_validation", {}).get("status") == "fail"
        and mismatch_diagnostic.get("worksheet_id") == "pcr02-owner-decision-worksheet-007"
        and "/archive/" in str(mismatch_diagnostic.get("expected", "")),
        "owner-archive-only-rejects-non-archive-target",
        "owner archive-only forms reject validation or decision targets",
        {
            "exit_code": result["exit_code"],
            "validation_status": parsed.get("form_validation", {}).get("status"),
            "diagnostics": diagnostics,
            "mismatch_diagnostic": mismatch_diagnostic,
            "stdout_sample": result["stdout"][:1000],
        },
        repo,
    )

def test_owner_landing_plan_project_index():
    repo = copy_repo_with_open_owner_gates("owner-landing-plan-project-index")
    form, setup_error = make_valid_owner_decision_form(repo)
    if setup_error:
        expect(False, "owner-landing-plan-project-index", "owner landing plan requires by-project index", setup_error, repo)
        return
    temp_root = pathlib.Path(tempfile.mkdtemp(prefix="kh-regression-owner-landing-plan-"))
    temp_roots.append(temp_root)
    forms_path = temp_root / "owner-decisions.jsonl"
    forms_path.write_text(json.dumps(form, ensure_ascii=False, separators=(",", ":")) + "\n")
    result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-owner-gates.sh",
            "--source-id",
            "pcr02-project-docs",
            "--worksheet-id",
            "pcr02-owner-decision-worksheet-001",
            "--validate-forms",
            str(forms_path),
            "--landing-plan",
            "--landing-audit",
            "--json",
        ],
    )
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    required_files = parsed.get("landing_plan", {}).get("required_manual_files", [])
    landing_audit = parsed.get("landing_audit", {})
    owner_ready_gate = parsed.get("landing_plan", {}).get("owner_ready_gate", {})
    steps = parsed.get("landing_plan", {}).get("steps", [])
    audit_rows = landing_audit.get("rows", [])
    first_audit = audit_rows[0] if audit_rows else {}
    worksheet_resolution = first_audit.get("worksheet_resolution_status", {})
    first_step = steps[0] if steps else {}
    worksheet_cwd = first_step.get("worksheet_verification_cwd", "")
    worksheet_commands = first_step.get("worksheet_verification_commands", [])
    expect(
        result["exit_code"] == 0
        and parsed.get("landing_plan", {}).get("status") == "planned"
        and owner_ready_gate.get("status") == "pass"
        and owner_ready_gate.get("error_count") == 0
        and "artifacts/manifests/pcr02-owner-decision-worksheets-20260618.jsonl" in required_files
        and "artifacts/manifests/*owner-decision-worksheets-*.jsonl" not in required_files
        and "indexes/by-project.md" in required_files
        and "indexes/by-source.md" in required_files
        and "indexes/by-status.md" in required_files
        and "indexes/by-decision.md" in required_files
        and landing_audit.get("status") == "ready-for-manual-landing"
        and landing_audit.get("read_only") is True
        and "artifacts/manifests/pcr02-owner-decision-worksheets-20260618.jsonl" in landing_audit.get("required_manual_files", [])
        and "artifacts/manifests/*owner-decision-worksheets-*.jsonl" not in landing_audit.get("required_manual_files", [])
        and "indexes/by-source.md" in landing_audit.get("required_manual_files", [])
        and "indexes/by-decision.md" in landing_audit.get("required_manual_files", [])
        and worksheet_resolution.get("must_update_worksheet_row") is True
        and "owner_decision" in worksheet_resolution.get("required_fields", [])
        and "reviewed_by" in worksheet_resolution.get("required_fields", [])
        and first_audit.get("expected_manual_deltas", {}).get("worksheet_jsonl")
        and "indexes/by-source.md" in first_audit.get("expected_manual_deltas", {}).get("indexes", [])
        and "indexes/by-decision.md" in first_audit.get("expected_manual_deltas", {}).get("indexes", [])
        and any("knowledge-final-gate.sh" in str(command) for command in first_audit.get("post_landing_commands", []))
        and worksheet_cwd == "sources/pcr02-project-docs"
        and bool(worksheet_commands)
        and any("knowledge-check.sh" in str(command) for command in worksheet_commands),
        "owner-landing-plan-project-index",
        "owner landing plan requires worksheet/index manual deltas and carries worksheet verification cwd and commands",
        {
            "exit_code": result["exit_code"],
            "landing_status": parsed.get("landing_plan", {}).get("status"),
            "landing_audit": landing_audit,
            "owner_ready_gate": owner_ready_gate,
            "required_manual_files": required_files,
            "worksheet_verification_cwd": worksheet_cwd,
            "worksheet_verification_commands": worksheet_commands,
            "stdout_sample": result["stdout"][:1000],
        },
    )

def test_owner_form_target_decision_candidate_gate():
    repo = copy_repo_with_open_owner_gates("owner-form-target-decision-candidate-gate")
    form, setup_error = make_valid_owner_decision_form(repo)
    if setup_error:
        expect(False, "owner-form-target-decision-candidate-gate", "owner form rejects target decisions outside worksheet candidates", setup_error, repo)
        return
    form["target_decision"] = "domains/embedded/standards/invalid-owner-target.md"
    temp_root = pathlib.Path(tempfile.mkdtemp(prefix="kh-regression-owner-target-decision-"))
    temp_roots.append(temp_root)
    forms_path = temp_root / "owner-decisions.jsonl"
    forms_path.write_text(json.dumps(form, ensure_ascii=False, separators=(",", ":")) + "\n")
    result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-owner-gates.sh",
            "--source-id",
            "pcr02-project-docs",
            "--worksheet-id",
            "pcr02-owner-decision-worksheet-001",
            "--validate-forms",
            str(forms_path),
            "--json",
        ],
    )
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    errors = parsed.get("form_validation", {}).get("errors", [])
    diagnostics = parsed.get("form_validation", {}).get("diagnostics", [])
    target_diagnostic = next(
        (
            row for row in diagnostics
            if row.get("code") == "target-decision-not-candidate"
            and row.get("field") == "target_decision"
        ),
        {},
    )
    expect(
        result["exit_code"] == 1
        and parsed.get("form_validation", {}).get("status") == "fail"
        and any("target_decision" in error and "target candidates" in error for error in errors)
        and target_diagnostic.get("worksheet_id") == "pcr02-owner-decision-worksheet-001"
        and target_diagnostic.get("actual") == "domains/embedded/standards/invalid-owner-target.md"
        and target_diagnostic.get("expected") == form.get("target_candidates", [])
        and "重新填写" in target_diagnostic.get("action_zh", ""),
        "owner-form-target-decision-candidate-gate",
        "owner form rejects target decisions outside worksheet candidates",
        {
            "exit_code": result["exit_code"],
            "validation_status": parsed.get("form_validation", {}).get("status"),
            "errors": errors,
            "diagnostics": diagnostics,
            "target_candidates": form.get("target_candidates", []),
            "stdout_sample": result["stdout"][:1000],
        },
    )

def test_owner_form_decision_target_pair_gate():
    repo = copy_repo_with_open_owner_gates("owner-form-decision-target-pair-gate")
    form, setup_error = make_valid_owner_decision_form(repo)
    if setup_error:
        expect(False, "owner-form-decision-target-pair-gate", "owner form rejects invalid owner_decision and target_decision pairs", setup_error, repo)
        return
    project_target = next(
        (
            target for target in form.get("target_candidates", [])
            if str(target).startswith("projects/")
        ),
        "",
    )
    if not project_target:
        expect(False, "owner-form-decision-target-pair-gate", "owner form rejects invalid owner_decision and target_decision pairs", {"setup_error": "missing project target candidate", "target_candidates": form.get("target_candidates", [])}, repo)
        return
    run_owner_decision_target_pair_gate(
        "owner-form-decision-target-pair-reference-only-project-path",
        "reference-only",
        project_target,
        "owner_decision 'reference-only' does not form a valid pair",
    )
    run_owner_decision_target_pair_gate(
        "owner-form-decision-target-pair-no-migration-project-path",
        "no-migration",
        project_target,
        "owner_decision 'no-migration' does not form a valid pair",
    )
    run_owner_decision_target_pair_gate(
        "owner-form-decision-target-pair-project-rule-reference-only",
        "project-local-rule",
        "reference-only",
        "owner_decision 'project-local-rule' does not form a valid pair",
    )

def test_owner_form_decision_target_pair_positive_gate():
    run_owner_decision_target_pair_positive(
        "owner-form-decision-target-pair-positive-reference-only",
        "reference-only",
        "reference-only",
    )
    run_owner_decision_target_pair_positive(
        "owner-form-decision-target-pair-positive-no-migration",
        "no-migration",
        "no-migration",
    )

def test_owner_form_routing_owner_reviewed_by_gate():
    repo = copy_repo_with_open_owner_gates("owner-form-routing-owner-reviewed-by-gate")
    form, setup_error = make_valid_owner_decision_form(repo)
    if setup_error:
        expect(False, "owner-form-routing-owner-reviewed-by-gate", "owner form rejects routing_owner as reviewed_by", setup_error, repo)
        return
    form["reviewed_by"] = "pcr02-registry-owner"
    temp_root = pathlib.Path(tempfile.mkdtemp(prefix="kh-regression-owner-routing-reviewed-by-"))
    temp_roots.append(temp_root)
    forms_path = temp_root / "owner-decisions.jsonl"
    forms_path.write_text(json.dumps(form, ensure_ascii=False, separators=(",", ":")) + "\n")
    result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-owner-gates.sh",
            "--source-id",
            "pcr02-project-docs",
            "--worksheet-id",
            "pcr02-owner-decision-worksheet-001",
            "--validate-forms",
            str(forms_path),
            "--json",
        ],
    )
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    errors = parsed.get("form_validation", {}).get("errors", [])
    expect(
        result["exit_code"] == 1
        and parsed.get("form_validation", {}).get("status") == "fail"
        and any("reviewed_by must be a real owner" in error and "routing_owner" in error for error in errors),
        "owner-form-routing-owner-reviewed-by-gate",
        "owner form rejects routing_owner as reviewed_by",
        {
            "exit_code": result["exit_code"],
            "validation_status": parsed.get("form_validation", {}).get("status"),
            "errors": errors,
            "stdout_sample": result["stdout"][:1000],
        },
    )

def test_owner_form_must_not_tamper_gate():
    def mutate(form):
        form["must_not"] = list(form.get("must_not", [])) + ["fixture-invalid-extra-guardrail"]

    run_owner_form_tamper_gate(
        "owner-form-must-not-tamper-gate",
        mutate,
        "must_not differs from worksheet guardrails",
    )

def test_owner_form_allowed_decisions_tamper_gate():
    def mutate(form):
        form["allowed_owner_decisions"] = list(form.get("allowed_owner_decisions", [])) + ["fixture-invalid-decision"]

    run_owner_form_tamper_gate(
        "owner-form-allowed-decisions-tamper-gate",
        mutate,
        "allowed_owner_decisions differs from worksheet decision options",
    )

def test_owner_form_target_candidates_tamper_gate():
    def mutate(form):
        form["target_candidates"] = list(form.get("target_candidates", [])) + ["projects/pcr02-ssc305/current/invalid-target-candidate-fixture.md"]

    run_owner_form_tamper_gate(
        "owner-form-target-candidates-tamper-gate",
        mutate,
        "target_candidates differs from worksheet target candidates",
    )

def test_owner_landing_plan_requires_owner_ready_package_missing():
    def mutate(repo):
        items_path = repo / "registry" / "items.jsonl"
        lines = items_path.read_text().splitlines()
        filtered = [
            line
            for line in lines
            if '"id":"pcr02-agents-owner-ready-package-20260620"' not in line
        ]
        if len(filtered) == len(lines):
            return {"setup_error": "missing owner-ready registry fixture line"}
        items_path.write_text("\n".join(filtered) + "\n")
        return None

    run_owner_landing_ready_block_fixture("missing", "missing", mutate)

def test_owner_landing_plan_requires_owner_ready_package_invalid():
    def mutate(repo):
        package_path = repo / "artifacts" / "manifests" / "pcr02-agents-owner-ready-package-20260620.jsonl"
        if not package_path.exists():
            return {"setup_error": "missing owner-ready package jsonl"}
        rows = [json.loads(line) for line in package_path.read_text().splitlines() if line.strip()]
        if len(rows) != 1:
            return {"setup_error": "owner-ready package jsonl should contain one row", "row_count": len(rows)}
        rows[0]["decision"] = "owner-approved-fixture"
        package_path.write_text(json.dumps(rows[0], ensure_ascii=False, separators=(",", ":")) + "\n")
        return None

    run_owner_landing_ready_block_fixture("invalid", "invalid", mutate)

def test_owner_landing_plan_requires_owner_ready_package_repo_relative_command():
    def mutate(repo):
        package_path = repo / "artifacts" / "manifests" / "pcr02-agents-owner-ready-package-20260620.md"
        if not package_path.exists():
            return {"setup_error": "missing owner-ready package markdown"}
        text = package_path.read_text()
        stable_command = "rtk bash ~/knowledge-hub/tools/knowledge-owner-gates.sh"
        if stable_command not in text:
            return {"setup_error": "stable owner-ready command fixture missing"}
        package_path.write_text(text.replace(stable_command, "rtk bash tools/knowledge-owner-gates.sh", 1))
        return None

    run_owner_landing_ready_block_fixture("repo-relative-command", "invalid", mutate)

def test_owner_landing_plan_requires_owner_ready_package_duplicate():
    def mutate(repo):
        items_path = repo / "registry" / "items.jsonl"
        lines = items_path.read_text().splitlines()
        for line in lines:
            if '"id":"pcr02-agents-owner-ready-package-20260620"' in line:
                item = json.loads(line)
                item["id"] = "pcr02-agents-owner-ready-package-duplicate-fixture"
                item["title"] = "PCR02 AGENTS owner ready package duplicate fixture"
                lines.append(json.dumps(item, ensure_ascii=False, separators=(",", ":")))
                items_path.write_text("\n".join(lines) + "\n")
                return None
        return {"setup_error": "missing owner-ready registry fixture line"}

    run_owner_landing_ready_block_fixture("duplicate", "duplicate", mutate)

def test_owner_form_source_identity_mismatch():
    repo = copy_repo_with_open_owner_gates("owner-form-source-identity-mismatch")
    forms_result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-owner-gates.sh",
            "--source-id",
            "pcr02-project-docs",
            "--worksheet-id",
            "pcr02-owner-decision-worksheet-001",
            "--forms",
            "--json",
        ],
    )
    parsed_forms = {}
    try:
        parsed_forms = json.loads(forms_result["stdout"])
    except Exception:
        pass
    forms = parsed_forms.get("decision_forms", [])
    if not forms:
        expect(
            False,
            "owner-form-source-identity-mismatch",
            "owner form rejects stale source identity",
            {"setup_error": "missing decision form", "stdout_sample": forms_result["stdout"][:1000]},
            repo,
        )
        return
    form = forms[0]
    identity = form.get("observed_source_identity", {})
    for key, value in {
        "owner_decision": form.get("allowed_owner_decisions", ["project-local-rule"])[0],
        "target_decision": form.get("target_candidates", ["project-local-rule"])[0],
        "reviewed_by": "regression-fixture-owner",
        "reviewed_at": "2026-06-19",
        "review_after": "2026-09-19",
        "source_status": "owner-reviewed-fixture",
        "source_sha256": "0" * 64,
        "source_size": identity.get("observed_size", ""),
        "current_validity": "fixture-only",
        "scope_statement": "PCR02 project-local only",
        "applicable_project_version": "fixture-version",
        "evidence_refs": ["artifacts/manifests/pcr02-owner-resolution-playbook-20260618.md"],
        "status_reason": "Regression fixture for stale source identity rejection.",
    }.items():
        form[key] = value
    temp_root = pathlib.Path(tempfile.mkdtemp(prefix="kh-regression-owner-source-identity-"))
    temp_roots.append(temp_root)
    forms_path = temp_root / "owner-decisions.jsonl"
    forms_path.write_text(json.dumps(form, ensure_ascii=False, separators=(",", ":")) + "\n")
    result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-owner-gates.sh",
            "--source-id",
            "pcr02-project-docs",
            "--worksheet-id",
            "pcr02-owner-decision-worksheet-001",
            "--validate-forms",
            str(forms_path),
            "--json",
        ],
    )
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    errors = parsed.get("form_validation", {}).get("errors", [])
    expect(
        result["exit_code"] == 1
        and parsed.get("form_validation", {}).get("status") == "fail"
        and any("source_sha256 does not match observed source identity" in error for error in errors),
        "owner-form-source-identity-mismatch",
        "owner form rejects stale source identity",
        {
            "exit_code": result["exit_code"],
            "validation_status": parsed.get("form_validation", {}).get("status"),
            "errors": errors,
            "observed_sha256": identity.get("observed_sha256", ""),
            "stdout_sample": result["stdout"][:1000],
        },
    )

def test_readme_offline_shortest_paths():
    readme_path = root / "README.md"
    gitignore_path = root / ".gitignore"
    try:
        readme = readme_path.read_text()
        read_error = ""
    except Exception as exc:
        readme = ""
        read_error = str(exc)
    try:
        gitignore = gitignore_path.read_text()
        gitignore_read_error = ""
    except Exception as exc:
        gitignore = ""
        gitignore_read_error = str(exc)
    required_fragments = [
        "## 日常入口",
        "## 离线人工维护",
        "## 高风险授权",
        "manual_validation_pending: true",
        "required_followup",
        "rtk bash ~/knowledge-hub/tools/knowledge-final-gate.sh --json",
        "rtk bash ~/knowledge-hub/tools/knowledge-final-gate.sh --json",
        "registry/authorizations.jsonl",
        "registry/automation-runs.jsonl",
        "本地 commit 只代表可审计快照",
        "push、merge、release、tag",
        "改变远端 Git 状态",
        "没有授权记录时，AI / Codex 只能在 Hub 内执行 L1/L2 维护、本地 commit，或输出 plan、diff、manifest、review package、report-only 报告。",
    ]
    missing_fragments = [fragment for fragment in required_fragments if fragment not in readme]
    gitignore_required_fragments = ["artifacts/manifests/*.local.jsonl"]
    gitignore_missing_fragments = [
        fragment
        for fragment in gitignore_required_fragments
        if fragment not in gitignore
    ]
    expect(
        not read_error and not gitignore_read_error and not missing_fragments and not gitignore_missing_fragments,
        "readme-offline-shortest-paths",
        "README keeps the five shortest manual maintenance paths and terminal-gate offline fallback",
        {
            "read_error": read_error,
            "gitignore_read_error": gitignore_read_error,
            "missing_fragments": missing_fragments,
            "gitignore_missing_fragments": gitignore_missing_fragments,
        },
    )
