"""Generated regression cases: lifecycle 2."""

# Generated by regression_codegen.py; edit assertions here, then keep the generator deterministic.
from .support import *  # noqa: F401,F403

def test_manual_entry_no_migration_ledger_guide():
    removed_ledger_path = "registry/" + "source policies.jsonl"
    result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "decision",
            "--domain",
            "governance",
            "--id",
            "governance-no-migration-ledger",
            "--path",
            "governance/no-migration-ledger.md",
        ],
    )
    expect(
        result["exit_code"] == 0
        and removed_ledger_path not in result["stdout"]
        and "source policy notes" not in result["stdout"]
        and "Evidence Index" in result["stdout"],
        "manual-entry-no-migration-ledger-guide",
        "manual entry guide does not expose migration ledger entrypoints",
        {
            "exit_code": result["exit_code"],
            "has_source policies_jsonl": removed_ledger_path in result["stdout"],
            "has_migration_notes": "source policy notes" in result["stdout"],
            "has_evidence_index": "Evidence Index" in result["stdout"],
            "stdout_sample": result["stdout"][:1600],
        },
    )

def test_manual_entry_template_selection():
    cases = [
        ("runbook", "templates/runbook.md", "runbook"),
        ("decision", "templates/decision.md", "decision"),
        ("validation", "templates/validation-report.md", "validation"),
        ("validation-report", "templates/validation-report.md", "validation"),
        ("project-archive", "templates/archive-note.md", "project-archive"),
        ("archive-note", "templates/archive-note.md", "project-archive"),
        ("debug-record", "templates/debug-record.md", "debug-record"),
        ("external-source-note", "templates/external-source-note.md", "external-source-note"),
        ("external-source", "templates/external-source-note.md", "external-source-note"),
        ("owner-decision-worksheet", "templates/owner-decision-worksheet.md", "owner-decision-worksheet"),
        ("owner-worksheet", "templates/owner-decision-worksheet.md", "owner-decision-worksheet"),
        ("patent-disclosure", "templates/patent-disclosure.md", "patent-disclosure"),
        ("patent", "templates/patent-disclosure.md", "patent"),
        ("artifact-ref", "templates/artifact-ref.md", "artifact-ref"),
        ("audit", "templates/item.md", "audit"),
    ]
    failures = []
    for kind, template, registry_kind in cases:
        result = run_cmd(
            root,
            [
                "rtk",
                "bash",
                "tools/knowledge-new.sh",
                "--kind",
                kind,
                "--domain",
                "governance",
                "--id",
                f"governance-template-{kind}",
                "--path",
                f"artifacts/manifests/governance-template-{kind}.md",
            ],
        )
        if (
            result["exit_code"] != 0
            or f"推荐模板: {template}" not in result["stdout"]
            or f"- registry_kind: {registry_kind}" not in result["stdout"]
            or f'"kind":"{registry_kind}"' not in result["stdout"]
        ):
            failures.append(
                {
                    "kind": kind,
                    "expected_template": template,
                    "expected_registry_kind": registry_kind,
                    "exit_code": result["exit_code"],
                    "stdout_sample": result["stdout"][:1000],
                }
            )
    expect(
        not failures,
        "manual-entry-template-selection",
        "manual entry guide keeps stable kind-to-template and registry-kind mapping",
        {
            "failures": failures,
            "case_count": len(cases),
        },
    )

def test_review_queue_json_contract():
    queue_repo = root
    status_result = run_cmd(
        queue_repo,
        ["rtk", "bash", "tools/knowledge-status.sh", "--json", "--as-of", today.isoformat()],
    )
    index_result = run_cmd(
        queue_repo,
        ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "review-queue", "--json"],
    )
    parse_errors = []
    try:
        status_payload = json.loads(status_result["stdout"])
    except Exception as exc:
        status_payload = {}
        parse_errors.append(f"status: {exc}")
    try:
        index_payload = json.loads(index_result["stdout"])
    except Exception as exc:
        index_payload = {}
        parse_errors.append(f"index-plan: {exc}")
    review_queues = status_payload.get("review_queues", {}) if isinstance(status_payload.get("review_queues", {}), dict) else {}
    status_summary = review_queues.get("summary", {}) if isinstance(review_queues.get("summary", {}), dict) else {}
    by_review_queue = (
        index_payload.get("indexes", {}).get("by_review_queue", {})
        if isinstance(index_payload.get("indexes", {}), dict)
        else {}
    )
    index_summary = by_review_queue.get("summary", {}) if isinstance(by_review_queue.get("summary", {}), dict) else {}
    rows = by_review_queue.get("rows", []) if isinstance(by_review_queue.get("rows", []), list) else []
    real_empty_queue_contract = True
    if not rows and not parse_errors:
        real_empty_queue_contract = (
            review_queues.get("read_only") is True
            and review_queues.get("report_only") is True
            and status_summary.get("total_pending_count", -1) == 0
            and index_summary.get("row_count", -1) == 0
            and index_summary.get("matched_count", -1) == 0
            and by_review_queue.get("rows", []) == []
        )
        queue_repo = copy_repo("review-queue-json-contract-pending")
        seed_pending_review_queue_items(queue_repo, count=3)
        status_result = run_cmd(
            queue_repo,
            ["rtk", "bash", "tools/knowledge-status.sh", "--json", "--as-of", today.isoformat()],
        )
        index_result = run_cmd(
            queue_repo,
            ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "review-queue", "--json"],
        )
        try:
            status_payload = json.loads(status_result["stdout"])
        except Exception as exc:
            status_payload = {}
            parse_errors.append(f"seeded-status: {exc}")
        try:
            index_payload = json.loads(index_result["stdout"])
        except Exception as exc:
            index_payload = {}
            parse_errors.append(f"seeded-index-plan: {exc}")
        review_queues = status_payload.get("review_queues", {}) if isinstance(status_payload.get("review_queues", {}), dict) else {}
        status_summary = review_queues.get("summary", {}) if isinstance(review_queues.get("summary", {}), dict) else {}
        by_review_queue = (
            index_payload.get("indexes", {}).get("by_review_queue", {})
            if isinstance(index_payload.get("indexes", {}), dict)
            else {}
        )
        index_summary = by_review_queue.get("summary", {}) if isinstance(by_review_queue.get("summary", {}), dict) else {}
        rows = by_review_queue.get("rows", []) if isinstance(by_review_queue.get("rows", []), list) else []
    first_row = rows[0] if rows else {}
    filtered_result = run_cmd(
        queue_repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-index-plan.sh",
            "--section",
            "review-queue",
            "--json",
            "--queue-type",
            str(first_row.get("queue_type", "ai-human-review")),
            "--queue-owner",
            str(first_row.get("owner", "leiwenjun")),
            "--queue-review-after",
            str(first_row.get("review_after", "2026-09-17")),
            "--queue-limit",
            "3",
        ],
    )
    try:
        filtered_payload = json.loads(filtered_result["stdout"])
    except Exception as exc:
        filtered_payload = {}
        parse_errors.append(f"filtered-index-plan: {exc}")
    filtered_queue = (
        filtered_payload.get("indexes", {}).get("by_review_queue", {})
        if isinstance(filtered_payload.get("indexes", {}), dict)
        else {}
    )
    filtered_summary = filtered_queue.get("summary", {}) if isinstance(filtered_queue.get("summary", {}), dict) else {}
    filtered_pagination = filtered_queue.get("pagination", {}) if isinstance(filtered_queue.get("pagination", {}), dict) else {}
    filtered_batch_packet = filtered_queue.get("review_batch_packet", {}) if isinstance(filtered_queue.get("review_batch_packet", {}), dict) else {}
    filtered_rows = filtered_queue.get("rows", []) if isinstance(filtered_queue.get("rows", []), list) else []
    forms_result = run_cmd(
        queue_repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-index-plan.sh",
            "--section",
            "review-queue",
            "--queue-forms-jsonl",
            "--queue-type",
            str(first_row.get("queue_type", "ai-human-review")),
            "--queue-owner",
            str(first_row.get("owner", "leiwenjun")),
            "--queue-review-after",
            str(first_row.get("review_after", "2026-09-17")),
            "--queue-limit",
            "3",
        ],
    )
    forms_conflict_result = run_cmd(
        queue_repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-index-plan.sh",
            "--section",
            "review-queue",
            "--queue-forms-jsonl",
            "--json",
        ],
    )
    form_parse_errors = []
    forms = []
    for line in forms_result["stdout"].splitlines():
        if not line.strip():
            continue
        try:
            forms.append(json.loads(line))
        except Exception as exc:
            form_parse_errors.append(str(exc))
    first_form = forms[0] if forms else {}
    first_form_text = forms_result["stdout"]
    temp_form_paths = []

    def write_review_queue_forms_jsonl(form_rows):
        handle = tempfile.NamedTemporaryFile("w", encoding="utf-8", suffix=".jsonl", delete=False)
        temp_form_paths.append(pathlib.Path(handle.name))
        with handle:
            for form_row in form_rows:
                handle.write(json.dumps(form_row, ensure_ascii=False, separators=(",", ":")) + "\n")
        return handle.name

    filled_form = dict(first_form)
    filled_form.update({
        "human_reviewed_by": "regression-fixture-human",
        "human_reviewed_at": today.isoformat(),
        "review_basis": "Regression fixture for review queue validation.",
        "review_decision": "accept-as-review-record",
    })
    duplicate_form = dict(filled_form)
    unknown_form = dict(filled_form)
    unknown_form["queue_id"] = "item:unknown-review-queue-form:ai-human-review"
    invalid_decision_form = dict(filled_form)
    invalid_decision_form["review_decision"] = "owner-approved"
    missing_human_field_form = dict(filled_form)
    missing_human_field_form["review_basis"] = ""
    forbidden_owner_field_form = dict(filled_form)
    forbidden_owner_field_form["owner_decision"] = "approved"
    identity_mismatch_form = dict(filled_form)
    identity_mismatch_form["id"] = "tampered-review-queue-id"
    guardrail_mismatch_form = dict(filled_form)
    guardrail_mismatch_form["read_only"] = False
    content_hash_mismatch_form = dict(filled_form)
    content_hash_mismatch_form["content_sha256"] = "0" * 64
    valid_forms_path = write_review_queue_forms_jsonl([filled_form])
    duplicate_forms_path = write_review_queue_forms_jsonl([filled_form, duplicate_form])
    unknown_forms_path = write_review_queue_forms_jsonl([unknown_form])
    invalid_decision_forms_path = write_review_queue_forms_jsonl([invalid_decision_form])
    missing_human_field_forms_path = write_review_queue_forms_jsonl([missing_human_field_form])
    forbidden_owner_field_forms_path = write_review_queue_forms_jsonl([forbidden_owner_field_form])
    identity_mismatch_forms_path = write_review_queue_forms_jsonl([identity_mismatch_form])
    guardrail_mismatch_forms_path = write_review_queue_forms_jsonl([guardrail_mismatch_form])
    content_hash_mismatch_forms_path = write_review_queue_forms_jsonl([content_hash_mismatch_form])
    validate_base_command = [
        "rtk",
        "bash",
        "tools/knowledge-index-plan.sh",
        "--section",
        "review-queue",
        "--json",
        "--queue-type",
        str(first_row.get("queue_type", "ai-human-review")),
        "--queue-owner",
        str(first_row.get("owner", "leiwenjun")),
        "--queue-review-after",
        str(first_row.get("review_after", "2026-09-17")),
        "--queue-limit",
        "3",
        "--validate-queue-forms",
    ]
    validate_result = run_cmd(queue_repo, validate_base_command + [valid_forms_path])
    duplicate_validate_result = run_cmd(queue_repo, validate_base_command + [duplicate_forms_path])
    unknown_validate_result = run_cmd(queue_repo, validate_base_command + [unknown_forms_path])
    invalid_decision_validate_result = run_cmd(queue_repo, validate_base_command + [invalid_decision_forms_path])
    missing_human_field_validate_result = run_cmd(queue_repo, validate_base_command + [missing_human_field_forms_path])
    forbidden_owner_field_validate_result = run_cmd(queue_repo, validate_base_command + [forbidden_owner_field_forms_path])
    identity_mismatch_validate_result = run_cmd(queue_repo, validate_base_command + [identity_mismatch_forms_path])
    guardrail_mismatch_validate_result = run_cmd(queue_repo, validate_base_command + [guardrail_mismatch_forms_path])
    content_hash_mismatch_validate_result = run_cmd(queue_repo, validate_base_command + [content_hash_mismatch_forms_path])
    validate_without_json_result = run_cmd(
        queue_repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-index-plan.sh",
            "--section",
            "review-queue",
            "--validate-queue-forms",
            valid_forms_path,
        ],
    )
    validate_wrong_section_result = run_cmd(
        queue_repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-index-plan.sh",
            "--section",
            "owner",
            "--json",
            "--validate-queue-forms",
            valid_forms_path,
        ],
    )
    validate_forms_conflict_result = run_cmd(
        queue_repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-index-plan.sh",
            "--section",
            "review-queue",
            "--queue-forms-jsonl",
            "--validate-queue-forms",
            valid_forms_path,
        ],
    )
    validate_parse_errors = []
    try:
        validate_payload = json.loads(validate_result["stdout"])
    except Exception as exc:
        validate_payload = {}
        validate_parse_errors.append(f"valid-forms: {exc}")
    try:
        duplicate_validate_payload = json.loads(duplicate_validate_result["stdout"])
    except Exception as exc:
        duplicate_validate_payload = {}
        validate_parse_errors.append(f"duplicate-forms: {exc}")
    try:
        unknown_validate_payload = json.loads(unknown_validate_result["stdout"])
    except Exception as exc:
        unknown_validate_payload = {}
        validate_parse_errors.append(f"unknown-forms: {exc}")
    try:
        invalid_decision_validate_payload = json.loads(invalid_decision_validate_result["stdout"])
    except Exception as exc:
        invalid_decision_validate_payload = {}
        validate_parse_errors.append(f"invalid-decision-forms: {exc}")
    try:
        missing_human_field_validate_payload = json.loads(missing_human_field_validate_result["stdout"])
    except Exception as exc:
        missing_human_field_validate_payload = {}
        validate_parse_errors.append(f"missing-human-field-forms: {exc}")
    try:
        forbidden_owner_field_validate_payload = json.loads(forbidden_owner_field_validate_result["stdout"])
    except Exception as exc:
        forbidden_owner_field_validate_payload = {}
        validate_parse_errors.append(f"forbidden-owner-field-forms: {exc}")
    try:
        identity_mismatch_validate_payload = json.loads(identity_mismatch_validate_result["stdout"])
    except Exception as exc:
        identity_mismatch_validate_payload = {}
        validate_parse_errors.append(f"identity-mismatch-forms: {exc}")
    try:
        guardrail_mismatch_validate_payload = json.loads(guardrail_mismatch_validate_result["stdout"])
    except Exception as exc:
        guardrail_mismatch_validate_payload = {}
        validate_parse_errors.append(f"guardrail-mismatch-forms: {exc}")
    try:
        content_hash_mismatch_validate_payload = json.loads(content_hash_mismatch_validate_result["stdout"])
    except Exception as exc:
        content_hash_mismatch_validate_payload = {}
        validate_parse_errors.append(f"content-hash-mismatch-forms: {exc}")
    for temp_form_path in temp_form_paths:
        try:
            temp_form_path.unlink()
        except FileNotFoundError:
            pass
    form_validation = validate_payload.get("form_validation", {}) if isinstance(validate_payload.get("form_validation", {}), dict) else {}
    duplicate_diagnostic_codes = [
        row.get("code")
        for row in duplicate_validate_payload.get("form_validation", {}).get("diagnostics", [])
        if isinstance(row, dict)
    ]
    unknown_diagnostic_codes = [
        row.get("code")
        for row in unknown_validate_payload.get("form_validation", {}).get("diagnostics", [])
        if isinstance(row, dict)
    ]
    invalid_decision_diagnostic_codes = [
        row.get("code")
        for row in invalid_decision_validate_payload.get("form_validation", {}).get("diagnostics", [])
        if isinstance(row, dict)
    ]
    missing_human_field_diagnostic_codes = [
        row.get("code")
        for row in missing_human_field_validate_payload.get("form_validation", {}).get("diagnostics", [])
        if isinstance(row, dict)
    ]
    forbidden_owner_field_diagnostic_codes = [
        row.get("code")
        for row in forbidden_owner_field_validate_payload.get("form_validation", {}).get("diagnostics", [])
        if isinstance(row, dict)
    ]
    identity_mismatch_diagnostic_codes = [
        row.get("code")
        for row in identity_mismatch_validate_payload.get("form_validation", {}).get("diagnostics", [])
        if isinstance(row, dict)
    ]
    guardrail_mismatch_diagnostic_codes = [
        row.get("code")
        for row in guardrail_mismatch_validate_payload.get("form_validation", {}).get("diagnostics", [])
        if isinstance(row, dict)
    ]
    content_hash_mismatch_diagnostic_codes = [
        row.get("code")
        for row in content_hash_mismatch_validate_payload.get("form_validation", {}).get("diagnostics", [])
        if isinstance(row, dict)
    ]
    required_first_row_fields = [
        "queue_id",
        "queue_type",
        "object_type",
        "id",
        "content_hash_required",
        "content_hash_status",
        "content_sha256",
        "owner",
        "status",
        "review_after",
        "priority",
        "missing_fields",
        "evidence_refs",
        "ai_role",
        "ai_model_or_tool",
        "ai_generated_at",
        "promotion_decision",
        "next_commands",
        "must_not",
        "read_only",
        "report_only",
        "owner_gate_mutation",
        "memory_write",
        "source_project_write",
    ]
    missing_first_row_fields = [field for field in required_first_row_fields if field not in first_row]
    expect(
        status_result["exit_code"] in {0, 1}
        and real_empty_queue_contract
        and index_result["exit_code"] == 0
        and not parse_errors
        and review_queues.get("read_only") is True
        and review_queues.get("report_only") is True
        and status_summary.get("total_pending_count", 0) == index_summary.get("row_count", -1)
        and status_summary.get("ai_generated_pending_count", 0) == index_summary.get("ai_generated_pending_count", -1)
        and status_summary.get("external_source_pending_count", 0) == index_summary.get("external_source_pending_count", -1)
        and index_summary.get("active_or_promotion_blocker_count", -1) == status_summary.get("active_or_promotion_blocker_count", -2)
        and index_summary.get("active_or_promotion_blocker_count", 1) == 0
        and rows
        and not missing_first_row_fields
        and first_row.get("read_only") is True
        and first_row.get("report_only") is True
        and first_row.get("owner_gate_mutation") is False
        and first_row.get("memory_write") is False
        and first_row.get("source_project_write") is False
        and first_row.get("content_hash_required") is True
        and len(first_row.get("content_sha256", "")) == 64
        and "ai-human-review" in by_review_queue.get("by_type", {})
        and "不写 memory" in " ".join(by_review_queue.get("must_not", []))
        and first_row.get("next_commands")
        and first_row.get("id", "") in first_row.get("next_commands", [""])[0]
        and "--explain" in first_row.get("next_commands", [""])[0]
        and "不自动提升 active" in " ".join(first_row.get("must_not", []))
        and filtered_result["exit_code"] == 0
        and filtered_summary.get("matched_count", 0) >= len(filtered_rows)
        and filtered_summary.get("shown_count") == len(filtered_rows)
        and len(filtered_rows) <= 3
        and filtered_pagination.get("limit") == 3
        and all(row.get("queue_type") == first_row.get("queue_type") for row in filtered_rows)
        and all(row.get("owner") == first_row.get("owner") for row in filtered_rows)
        and all(row.get("review_after") == first_row.get("review_after") for row in filtered_rows)
        and filtered_summary.get("read_only") is True
        and filtered_summary.get("report_only") is True
        and filtered_summary.get("memory_write") is False
        and "review_batch_packet" not in filtered_summary
        and len(filtered_result["stdout"].encode("utf-8")) <= 64 * 1024
        and filtered_batch_packet.get("packet_type") == "review-queue-batch"
        and filtered_batch_packet.get("read_only") is True
        and filtered_batch_packet.get("report_only") is True
        and filtered_batch_packet.get("shown_count") == len(filtered_rows)
        and filtered_batch_packet.get("row_ids") == [row.get("queue_id") for row in filtered_rows]
        and "human_reviewed_by" in filtered_batch_packet.get("required_human_fields", [])
        and len(filtered_batch_packet.get("next_commands", [])) == len(filtered_rows)
        and all("--explain" in command for command in filtered_batch_packet.get("next_commands", []))
        and "不把 review queue 当 owner gate 签收结果" in " ".join(filtered_batch_packet.get("must_not", []))
        and "knowledge-index-plan.sh --section review-queue" in filtered_batch_packet.get("recommended_batch_json", "")
        and "--json" in filtered_batch_packet.get("recommended_batch_json", "")
        and "--queue-forms-jsonl" in filtered_batch_packet.get("recommended_forms_jsonl", "")
        and "--validate-queue-forms" in filtered_batch_packet.get("validate_queue_forms_command_template", "")
        and "review-queue-forms.jsonl" in filtered_batch_packet.get("validate_queue_forms_command_template", "")
        and filtered_batch_packet.get("forms_jsonl_command", "").endswith("--queue-limit 3 --queue-offset 0")
        and "--queue-forms-jsonl" in filtered_batch_packet.get("forms_jsonl_command", "")
        and forms_result["exit_code"] == 0
        and not form_parse_errors
        and len(forms) == len(filtered_rows)
        and len(forms) <= 3
        and "# Knowledge Index Plan" not in first_form_text
        and "## 验证" not in first_form_text
        and first_form.get("form_type") == "review-queue-human-review"
        and first_form.get("schema_version") == 2
        and first_form.get("status") == "human-fill-required"
        and first_form.get("read_only") is True
        and first_form.get("report_only") is True
        and first_form.get("owner_gate_mutation") is False
        and first_form.get("memory_write") is False
        and first_form.get("source_project_write") is False
        and first_form.get("human_reviewed_by") == ""
        and first_form.get("human_reviewed_at") == ""
        and first_form.get("review_basis") == ""
        and first_form.get("content_hash_required") is True
        and first_form.get("content_sha256") == first_row.get("content_sha256")
        and "content_sha256" in first_form.get("required_binding_fields", [])
        and "owner" not in first_form
        and "owner_decision" not in first_form
        and "reviewed_by" not in first_form
        and "human_reviewed_by" in first_form.get("required_human_fields", [])
        and "不写 registry" in " ".join(first_form.get("must_not", []))
        and first_form.get("read_only_context", {}).get("registry_owner") == first_row.get("owner")
        and forms_conflict_result["exit_code"] != 0
        and "--queue-forms-jsonl cannot be combined with --json" in forms_conflict_result["stderr"]
        and validate_result["exit_code"] == 0
        and not validate_parse_errors
        and form_validation.get("status") == "pass"
        and form_validation.get("read_only") is True
        and form_validation.get("report_only") is True
        and form_validation.get("no_registry_write") is True
        and form_validation.get("no_owner_decision_generated") is True
        and form_validation.get("owner_gate_mutation") is False
        and form_validation.get("accepted_count") == 1
        and form_validation.get("coverage_status") in {"partial", "complete"}
        and "review_decision" in form_validation.get("required_submission_fields", [])
        and duplicate_validate_result["exit_code"] != 0
        and "duplicate-queue-id" in duplicate_diagnostic_codes
        and unknown_validate_result["exit_code"] != 0
        and "unknown-queue-id" in unknown_diagnostic_codes
        and invalid_decision_validate_result["exit_code"] != 0
        and "invalid-review-decision" in invalid_decision_diagnostic_codes
        and missing_human_field_validate_result["exit_code"] != 0
        and "missing-required-human-field" in missing_human_field_diagnostic_codes
        and forbidden_owner_field_validate_result["exit_code"] != 0
        and "forbidden-owner-field" in forbidden_owner_field_diagnostic_codes
        and identity_mismatch_validate_result["exit_code"] != 0
        and "field-mismatch" in identity_mismatch_diagnostic_codes
        and guardrail_mismatch_validate_result["exit_code"] != 0
        and "guardrail-field-mismatch" in guardrail_mismatch_diagnostic_codes
        and content_hash_mismatch_validate_result["exit_code"] != 0
        and "content-sha256-mismatch" in content_hash_mismatch_diagnostic_codes
        and validate_without_json_result["exit_code"] != 0
        and "--validate-queue-forms requires --json" in validate_without_json_result["stderr"]
        and validate_wrong_section_result["exit_code"] != 0
        and "--validate-queue-forms requires --section review-queue" in validate_wrong_section_result["stderr"]
        and validate_forms_conflict_result["exit_code"] != 0
        and "--validate-queue-forms cannot be combined with --queue-forms-jsonl" in validate_forms_conflict_result["stderr"],
        "review-queue-json-contract",
        "status and index-plan expose report-only human review queue from registry",
        {
            "status_exit_code": status_result["exit_code"],
            "real_empty_queue_contract": real_empty_queue_contract,
            "index_exit_code": index_result["exit_code"],
            "parse_errors": parse_errors,
            "status_total_pending_count": status_summary.get("total_pending_count"),
            "index_row_count": index_summary.get("row_count"),
            "status_ai_generated_pending_count": status_summary.get("ai_generated_pending_count"),
            "index_ai_generated_pending_count": index_summary.get("ai_generated_pending_count"),
            "active_or_promotion_blocker_count": index_summary.get("active_or_promotion_blocker_count"),
            "missing_first_row_fields": missing_first_row_fields,
            "filtered_exit_code": filtered_result["exit_code"],
            "filtered_summary": filtered_summary,
            "filtered_row_count": len(filtered_rows),
            "filtered_pagination": filtered_pagination,
            "filtered_batch_packet": filtered_batch_packet,
            "forms_exit_code": forms_result["exit_code"],
            "forms_line_count": len(forms),
            "form_parse_errors": form_parse_errors,
            "first_form": first_form,
            "forms_conflict_exit_code": forms_conflict_result["exit_code"],
            "forms_conflict_stderr": forms_conflict_result["stderr"][:500],
            "validate_exit_code": validate_result["exit_code"],
            "validate_parse_errors": validate_parse_errors,
            "form_validation": form_validation,
            "duplicate_validate_exit_code": duplicate_validate_result["exit_code"],
            "duplicate_diagnostic_codes": duplicate_diagnostic_codes,
            "unknown_validate_exit_code": unknown_validate_result["exit_code"],
            "unknown_diagnostic_codes": unknown_diagnostic_codes,
            "invalid_decision_validate_exit_code": invalid_decision_validate_result["exit_code"],
            "invalid_decision_diagnostic_codes": invalid_decision_diagnostic_codes,
            "missing_human_field_validate_exit_code": missing_human_field_validate_result["exit_code"],
            "missing_human_field_diagnostic_codes": missing_human_field_diagnostic_codes,
            "forbidden_owner_field_validate_exit_code": forbidden_owner_field_validate_result["exit_code"],
            "forbidden_owner_field_diagnostic_codes": forbidden_owner_field_diagnostic_codes,
            "identity_mismatch_validate_exit_code": identity_mismatch_validate_result["exit_code"],
            "identity_mismatch_diagnostic_codes": identity_mismatch_diagnostic_codes,
            "guardrail_mismatch_validate_exit_code": guardrail_mismatch_validate_result["exit_code"],
            "guardrail_mismatch_diagnostic_codes": guardrail_mismatch_diagnostic_codes,
            "content_hash_mismatch_validate_exit_code": content_hash_mismatch_validate_result["exit_code"],
            "content_hash_mismatch_diagnostic_codes": content_hash_mismatch_diagnostic_codes,
            "validate_without_json_exit_code": validate_without_json_result["exit_code"],
            "validate_without_json_stderr": validate_without_json_result["stderr"][:500],
            "validate_wrong_section_exit_code": validate_wrong_section_result["exit_code"],
            "validate_wrong_section_stderr": validate_wrong_section_result["stderr"][:500],
            "validate_forms_conflict_exit_code": validate_forms_conflict_result["exit_code"],
            "validate_forms_conflict_stderr": validate_forms_conflict_result["stderr"][:500],
        },
    )
