"""Generated regression cases: lifecycle."""

# Generated by regression_codegen.py; edit assertions here, then keep the generator deterministic.
from .support import *  # noqa: F401,F403

def test_manual_entry_project_index_hint():
    project_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "runbook",
            "--domain",
            "projects/xcrz-sigmastar-demo",
            "--id",
            "pcr02-regression-runbook",
            "--path",
            "projects/xcrz-sigmastar-demo/current/runbooks/regression.md",
        ],
    )
    governance_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "decision",
            "--domain",
            "governance",
            "--id",
            "governance-regression-decision",
            "--path",
            "governance/regression-decision.md",
        ],
    )
    expect(
        project_result["exit_code"] == 0
        and governance_result["exit_code"] == 0
        and "indexes/by-project.md" in project_result["stdout"]
        and "indexes/by-source.md" in project_result["stdout"]
        and "未知来源不要同步 by-source" in project_result["stdout"]
        and "- <source-id>:" not in project_result["stdout"]
        and "# - <真实-source-id>:" in project_result["stdout"]
        and "projects/xcrz-sigmastar-demo/current/runbooks/regression.md" in project_result["stdout"]
        and "indexes/by-decision.md" in governance_result["stdout"]
        and "governance-regression-decision: governance/regression-decision.md" in governance_result["stdout"]
        and "indexes/by-project.md" not in governance_result["stdout"],
        "manual-entry-project-index-hint",
        "manual entries mention project/source/decision conditional index hints",
        {
            "project_exit_code": project_result["exit_code"],
            "governance_exit_code": governance_result["exit_code"],
            "project_has_by_project": "indexes/by-project.md" in project_result["stdout"],
            "project_has_by_source": "indexes/by-source.md" in project_result["stdout"],
            "project_has_unsafe_source_placeholder": "- <source-id>:" in project_result["stdout"],
            "governance_has_by_decision": "indexes/by-decision.md" in governance_result["stdout"],
            "governance_has_by_project": "indexes/by-project.md" in governance_result["stdout"],
            "project_stdout_sample": project_result["stdout"][:1200],
            "governance_stdout_sample": governance_result["stdout"][:1200],
        },
    )

def test_manual_entry_registered_source_binding():
    bound_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "runbook",
            "--domain",
            "projects/xcrz-sigmastar-demo",
            "--owner",
            "team-core",
            "--id",
            "pcr02-source-bound-runbook",
            "--path",
            "projects/xcrz-sigmastar-demo/current/runbooks/source-bound.md",
            "--item-source-id",
            "codex-history",
            "--item-source-path",
            "runbooks/source-bound.md",
        ],
    )
    unknown_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "runbook",
            "--domain",
            "projects/xcrz-sigmastar-demo",
            "--id",
            "pcr02-unknown-source-runbook",
            "--path",
            "projects/xcrz-sigmastar-demo/current/runbooks/unknown-source.md",
            "--item-source-id",
            "not-registered-source",
        ],
    )
    expect(
        bound_result["exit_code"] == 0
        and '"source":{"type":"registered","source_id":"codex-history","source_path":"runbooks/source-bound.md","from":"manual-entry:knowledge-new.sh"}' in bound_result["stdout"]
        and "- codex-history: `pcr02-source-bound-runbook`" in bound_result["stdout"]
        and 'knowledge-search.sh "pcr02-source-bound-runbook" --source-id codex-history --json' in bound_result["stdout"]
        and "未知来源不要同步 by-source" not in bound_result["stdout"]
        and unknown_result["exit_code"] != 0
        and "--item-source-id is not registered" in unknown_result["stderr"],
        "manual-entry-registered-source-binding",
        "manual entry guide can bind a normal item to a registered source without forging unknown source ids",
        {
            "bound_exit_code": bound_result["exit_code"],
            "unknown_exit_code": unknown_result["exit_code"],
            "has_registered_source_json": '"source":{"type":"registered","source_id":"codex-history","source_path":"runbooks/source-bound.md","from":"manual-entry:knowledge-new.sh"}' in bound_result["stdout"],
            "has_by_source_draft": "- codex-history: `pcr02-source-bound-runbook`" in bound_result["stdout"],
            "has_source_search_command": 'knowledge-search.sh "pcr02-source-bound-runbook" --source-id codex-history --json' in bound_result["stdout"],
            "unknown_stderr": unknown_result["stderr"][:500],
            "bound_stdout_sample": bound_result["stdout"][:1600],
        },
    )

def test_manual_entry_project_from_domain():
    derived_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "runbook",
            "--domain",
            "projects/xcrz-sigmastar-demo",
            "--id",
            "pcr02-derived-project-runbook",
            "--path",
            "projects/xcrz-sigmastar-demo/current/runbooks/derived.md",
        ],
    )
    removed_project_arg_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "runbook",
            "--domain",
            "projects/xcrz-sigmastar-demo",
            "--project",
            "wrong-project",
            "--id",
            "pcr02-mismatch-runbook",
            "--path",
            "projects/xcrz-sigmastar-demo/current/runbooks/mismatch.md",
        ],
    )
    expect(
        derived_result["exit_code"] == 0
        and "- xcrz-sigmastar-demo: projects/xcrz-sigmastar-demo/current/runbooks/derived.md" in derived_result["stdout"]
        and removed_project_arg_result["exit_code"] == 2
        and "ERROR unknown argument: --project" in removed_project_arg_result["stderr"],
        "manual-entry-project-derived-from-domain",
        "manual project entries derive project id from domain and reject the unsupported --project option",
        {
            "derived_exit_code": derived_result["exit_code"],
            "removed_project_arg_exit_code": removed_project_arg_result["exit_code"],
            "derived_has_project": "- xcrz-sigmastar-demo: projects/xcrz-sigmastar-demo/current/runbooks/derived.md" in derived_result["stdout"],
            "removed_project_arg_rejected": "ERROR unknown argument: --project" in removed_project_arg_result["stderr"],
            "derived_stdout_sample": derived_result["stdout"][:1200],
            "removed_project_arg_stderr_sample": removed_project_arg_result["stderr"][:500],
        },
    )

def test_manual_entry_default_dates():
    result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "decision",
            "--domain",
            "governance",
            "--id",
            "governance-date-defaults",
            "--path",
            "governance/date-defaults.md",
        ],
    )
    current_today = today.isoformat()
    expect(
        result["exit_code"] == 0
        and f'"created_at":"{current_today}"' in result["stdout"]
        and f'"updated_at":"{current_today}"' in result["stdout"]
        and '"review_after":"<YYYY-MM-DD>"' not in result["stdout"]
        and "checked_at\":\"<YYYY-MM-DD>" not in result["stdout"],
        "manual-entry-default-dates",
        "manual entry skeleton fills default ISO dates",
        {
            "exit_code": result["exit_code"],
            "today": current_today,
            "has_created_at": f'"created_at":"{current_today}"' in result["stdout"],
            "has_updated_at": f'"updated_at":"{current_today}"' in result["stdout"],
            "stdout_sample": result["stdout"][:1200],
        },
    )

def test_manual_entry_owner_override():
    default_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "decision",
            "--domain",
            "governance",
            "--id",
            "governance-owner-default",
            "--path",
            "governance/owner-default.md",
        ],
    )
    override_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "decision",
            "--domain",
            "governance",
            "--owner",
            "team-core",
            "--id",
            "governance-owner-override",
            "--path",
            "governance/owner-override.md",
        ],
    )
    expect(
        default_result["exit_code"] == 0
        and override_result["exit_code"] == 0
        and '"owner":"leiwenjun"' in default_result["stdout"]
        and '"owner":"team-core"' in override_result["stdout"]
        and "- owner: team-core" in override_result["stdout"],
        "manual-entry-owner-override",
        "manual entry skeleton supports owner override",
        {
            "default_exit_code": default_result["exit_code"],
            "override_exit_code": override_result["exit_code"],
            "default_has_owner": '"owner":"leiwenjun"' in default_result["stdout"],
            "override_has_owner": '"owner":"team-core"' in override_result["stdout"],
            "override_stdout_sample": override_result["stdout"][:1200],
        },
    )

def test_manual_entry_owner_registry_and_personal_defaults():
    registered_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "decision",
            "--domain",
            "governance",
            "--owner",
            "team-core",
            "--id",
            "governance-owner-registered",
            "--path",
            "governance/owner-registered.md",
        ],
    )
    unknown_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "decision",
            "--domain",
            "governance",
            "--owner",
            "unknown-item-owner",
            "--id",
            "governance-owner-warning",
            "--path",
            "governance/owner-warning.md",
        ],
    )
    personal_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "personal-note",
            "--domain",
            "notes",
            "--id",
            "personal-defaults",
            "--path",
            "notes/personal/defaults.md",
        ],
    )
    inferred_personal_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "personal-note",
            "--id",
            "personal-path-defaults",
            "--path",
            "notes/personal/path-defaults.md",
        ],
    )
    mismatch_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "runbook",
            "--domain",
            "governance",
            "--id",
            "personal-path-mismatch",
            "--path",
            "notes/personal/path-mismatch.md",
        ],
    )
    unsupported_personal_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "personal-note",
            "--domain",
            "personal",
            "--id",
            "personal-unsupported-domain",
            "--path",
            "notes/personal/unsupported-domain.md",
        ],
    )
    unsupported_path_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "personal-note",
            "--domain",
            "notes",
            "--id",
            "personal-unsupported-path",
            "--path",
            "domains/personal/unsupported.md",
        ],
    )
    expect(
        registered_result["exit_code"] == 0
        and unknown_result["exit_code"] == 0
        and personal_result["exit_code"] == 0
        and inferred_personal_result["exit_code"] == 0
        and mismatch_result["exit_code"] == 2
        and unsupported_personal_result["exit_code"] == 2
        and unsupported_path_result["exit_code"] == 2
        and "- owner_registry_status: registered" in registered_result["stdout"]
        and "owner_warning_zh" not in registered_result["stdout"]
        and "- owner_registry_status: unknown-owner" in unknown_result["stdout"]
        and "item owner 未在 registry/owners.json 登记" in unknown_result["stdout"]
        and '"owner":"unknown-item-owner"' in unknown_result["stdout"]
        and '"domain":"notes"' in personal_result["stdout"]
        and '"scope":"team-general"' in personal_result["stdout"]
        and '"visibility":"personal-local"' in personal_result["stdout"]
        and '"status":"personal"' in personal_result["stdout"]
        and '"domain":"notes"' in inferred_personal_result["stdout"]
        and '"visibility":"personal-local"' in inferred_personal_result["stdout"]
        and '"status":"personal"' in inferred_personal_result["stdout"]
        and "请改为 --domain notes" in mismatch_result["stderr"]
        and "domain=personal 不属于当前路径契约" in unsupported_personal_result["stderr"]
        and "domains/personal/ 不属于当前路径契约" in unsupported_path_result["stderr"],
        "manual-entry-owner-registry-and-personal-defaults",
        "manual entry guide exposes item owner registry status, notes/personal safe defaults, and rejects unsupported personal entrypoints",
        {
            "registered_exit_code": registered_result["exit_code"],
            "unknown_exit_code": unknown_result["exit_code"],
            "personal_exit_code": personal_result["exit_code"],
            "inferred_personal_exit_code": inferred_personal_result["exit_code"],
            "mismatch_exit_code": mismatch_result["exit_code"],
            "unsupported_personal_exit_code": unsupported_personal_result["exit_code"],
            "unsupported_path_exit_code": unsupported_path_result["exit_code"],
            "registered_stdout_sample": registered_result["stdout"][:1200],
            "unknown_stdout_sample": unknown_result["stdout"][:1200],
            "personal_stdout_sample": personal_result["stdout"][:1600],
            "inferred_personal_stdout_sample": inferred_personal_result["stdout"][:1600],
            "mismatch_stderr_sample": mismatch_result["stderr"][:1600],
            "unsupported_personal_stderr_sample": unsupported_personal_result["stderr"][:800],
            "unsupported_path_stderr_sample": unsupported_path_result["stderr"][:800],
        },
    )

def test_manual_entry_docs_owner_option():
    readme_path = root / "README.md"
    tools_readme_path = root / "tools" / "README.md"
    try:
        readme = readme_path.read_text()
        tools_readme = tools_readme_path.read_text()
        help_result = run_cmd(root, ["rtk", "bash", "tools/knowledge-new.sh", "--help"])
        read_error = ""
    except Exception as exc:
        readme = ""
        tools_readme = ""
        help_result = {"exit_code": 1, "stdout": "", "stderr": str(exc)}
        read_error = str(exc)
    readme_has_owner = "knowledge-new.sh" in readme and "--owner" in readme
    tools_readme_has_owner = "knowledge-new.sh" in tools_readme and "--owner" in tools_readme
    help_has_owner_example = (
        help_result["exit_code"] == 0
        and "--owner team-core" in help_result["stdout"]
        and "--domain projects/xcrz-sigmastar-demo --owner" in help_result["stdout"]
    )
    expect(
        not read_error and readme_has_owner and tools_readme_has_owner and help_has_owner_example,
        "manual-entry-docs-owner-option",
        "manual entry docs mention owner option",
        {
            "read_error": read_error,
            "readme_has_owner": readme_has_owner,
            "tools_readme_has_owner": tools_readme_has_owner,
            "help_exit_code": help_result["exit_code"],
            "help_has_owner_example": help_has_owner_example,
            "help_stdout_sample": help_result["stdout"][:800],
        },
    )

def test_manual_entry_offline_docs():
    readme_path = root / "README.md"
    templates_readme_path = root / "templates" / "README.md"
    removed_ledger_path = "registry/" + "source policies.jsonl"
    removed_template_kind = "migration" + "-record"
    try:
        readme = readme_path.read_text()
        templates_readme = templates_readme_path.read_text()
        read_error = ""
    except Exception as exc:
        readme = ""
        templates_readme = ""
        read_error = str(exc)
    expect(
        not read_error
        and "manual_validation_pending: true" in readme
        and '"type": "manual"' in readme
        and '"from": "field-debug / meeting / code-review / lab-test / owner-decision / design-review"' in readme
        and '"status": "reviewing"' in readme
        and '"review_status": "manual-entry-pending-review"' in readme
        and removed_ledger_path not in templates_readme
        and removed_template_kind not in templates_readme,
        "manual-entry-offline-docs",
        "manual and offline maintenance docs state default registry values without migration ledger entrypoints",
        {
            "read_error": read_error,
            "readme_has_manual_validation_pending": "manual_validation_pending: true" in readme,
            "readme_has_manual_source_type": '"type": "manual"' in readme,
            "readme_has_reviewing_default": '"status": "reviewing"' in readme,
            "templates_has_migration_ledger": removed_ledger_path in templates_readme or removed_template_kind in templates_readme,
        },
    )

def test_manual_entry_offline_package_consistency():
    files = {
        "README.md": root / "README.md",
        "indexes/README.md": root / "indexes" / "README.md",
        "docs/goals/knowledge-hub-simplified-final-version.md": root / "docs" / "goals" / "knowledge-hub-simplified-final-version.md",
    }
    texts = {}
    read_errors = {}
    for rel, path in files.items():
        try:
            texts[rel] = path.read_text()
            read_errors[rel] = ""
        except Exception as exc:
            texts[rel] = ""
            read_errors[rel] = str(exc)

    diagnostics_command = "rtk bash ~/knowledge-hub/tools/knowledge-check.sh --dry-run --json --diagnostics"
    index_plan_command = "rtk bash ~/knowledge-hub/tools/knowledge-index-plan.sh --section all"
    weak_followup = "required_followup: run knowledge-check and update registry/index"
    per_file_missing = {}
    for rel, text in texts.items():
        required = [
            "manual_validation_pending: true",
            "required_followup",
            diagnostics_command,
            index_plan_command,
        ]
        per_file_missing[rel] = [fragment for fragment in required if fragment not in text]

    expect(
        not any(read_errors.values())
        and not any(per_file_missing.values())
        and weak_followup not in texts.get("docs/goals/knowledge-hub-simplified-final-version.md", ""),
        "manual-entry-offline-package-consistency",
        "offline manual maintenance package keeps complete rtk follow-up commands across README, indexes and goal docs",
        {
            "read_errors": read_errors,
            "per_file_missing": per_file_missing,
            "weak_followup_present_in_goal": weak_followup in texts.get("docs/goals/knowledge-hub-simplified-final-version.md", ""),
        },
    )

def test_manual_entry_validation_diagnostics_default():
    result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "decision",
            "--domain",
            "governance",
            "--id",
            "governance-validation-diagnostics",
            "--path",
            "governance/validation-diagnostics.md",
        ],
    )
    diagnostics_command = "rtk bash ~/knowledge-hub/tools/knowledge-check.sh --dry-run --json --diagnostics"
    expect(
        result["exit_code"] == 0
        and f'"validation_refs":["{diagnostics_command}"]' in result["stdout"]
        and f"| `{diagnostics_command}` |" in result["stdout"],
        "manual-entry-validation-diagnostics-default",
        "manual entry drafts default validation refs and Evidence Index to diagnostics check",
        {
            "exit_code": result["exit_code"],
            "has_validation_ref": f'"validation_refs":["{diagnostics_command}"]' in result["stdout"],
            "has_evidence_index_command": f"| `{diagnostics_command}` |" in result["stdout"],
            "stdout_sample": result["stdout"][:1600],
        },
    )

def test_manual_entry_readability_fields():
    result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "runbook",
            "--domain",
            "projects/xcrz-sigmastar-demo",
            "--owner",
            "team-core",
            "--id",
            "pcr02-readable-runbook",
            "--path",
            "projects/xcrz-sigmastar-demo/current/runbooks/readable.md",
            "--manual-source-reason",
            "field-debug",
            "--manual-validation-pending",
            "--manual-validation-reason",
            "offline lab note awaiting rtk validation",
            "--generated-by-ai",
            "--ai-role",
            "drafted",
        ],
    )
    required_fragments = [
        '"from":"field-debug"',
        '"summary_zh":"<中文 1-3 句摘要>"',
        '"primary_language":"zh-CN"',
        '"source_language":"zh-CN"',
        '"translation_status":"not-required"',
        '"terminology_status":"pending-review"',
        '"review_status":"manual-entry-pending-review"',
        '"evidence_strength":"manual-entry-pending-validation"',
        '"evidence_refs":[]',
        '"promotion_decision":"none"',
        '"generated_by_ai":true',
        '"ai_role":"drafted"',
        '"ai_model_or_tool":"Codex"',
        '"ai_generated_at":"',
        '"human_reviewed_by":""',
        '"review_basis":""',
        "manual_validation_pending: true",
        "offline lab note awaiting rtk validation",
        "required_followup: rtk bash ~/knowledge-hub/tools/knowledge-check.sh --dry-run --json --diagnostics",
    ]
    missing_fragments = [fragment for fragment in required_fragments if fragment not in result["stdout"]]
    expect(
        result["exit_code"] == 0 and not missing_fragments,
        "manual-entry-readability-fields",
        "manual entry skeleton exposes Chinese readability, evidence and AI provenance fields",
        {
            "exit_code": result["exit_code"],
            "missing_fragments": missing_fragments,
            "stdout_sample": result["stdout"][:1600],
        },
    )

def test_manual_entry_archive_default_status():
    result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--kind",
            "project-archive",
            "--domain",
            "projects/pcr02-ssc305",
            "--owner",
            "team-core",
            "--id",
            "pcr02-archive-status-default",
            "--path",
            "projects/pcr02-ssc305/archive/status-default.md",
        ],
    )
    required_fragments = [
        "- 推荐 registry status: archived",
        '"status":"archived"',
        "- archived: `pcr02-archive-status-default`",
    ]
    missing_fragments = [fragment for fragment in required_fragments if fragment not in result["stdout"]]
    expect(
        result["exit_code"] == 0 and not missing_fragments,
        "manual-entry-archive-default-status",
        "project archive manual entry guide defaults registry and status index drafts to archived",
        {
            "exit_code": result["exit_code"],
            "missing_fragments": missing_fragments,
            "stdout_sample": result["stdout"][:1600],
        },
    )
