"""Generated regression cases: lifecycle 3."""

# Generated by regression_codegen.py; edit assertions here, then keep the generator deterministic.
from .support import *  # noqa: F401,F403

def test_review_queue_apply_tool_contract():
    repo = copy_repo("review-queue-apply-tool")
    seed_pending_review_queue_items(repo, count=3)
    forms_result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-index-plan.sh",
            "--section",
            "review-queue",
            "--queue-forms-jsonl",
            "--queue-type",
            "ai-human-review",
            "--queue-owner",
            "leiwenjun",
            "--queue-limit",
            "3",
        ],
    )
    parse_errors = []
    forms = []
    for line in forms_result["stdout"].splitlines():
        if not line.strip():
            continue
        try:
            forms.append(json.loads(line))
        except Exception as exc:
            parse_errors.append(str(exc))
    if len(forms) < 3:
        expect(False, "review-queue-apply-tool-contract", "review queue apply validates and applies filled forms without owner-gate mutation", {"setup_error": "expected at least three forms", "parse_errors": parse_errors, "stdout": forms_result["stdout"][:1000]}, repo)
        return

    temp_root = pathlib.Path(tempfile.mkdtemp(prefix="kh-regression-review-queue-apply-"))
    temp_roots.append(temp_root)
    accept_form = dict(forms[0])
    accept_form.update({
        "human_reviewed_by": "regression-fixture-human",
        "human_reviewed_at": today.isoformat(),
        "review_basis": "Regression fixture accepted this AI review record.",
        "review_decision": "accept-as-review-record",
    })
    needs_edits_form = dict(forms[1])
    needs_edits_form.update({
        "human_reviewed_by": "regression-fixture-human",
        "human_reviewed_at": today.isoformat(),
        "review_basis": "Regression fixture keeps this item open for edits.",
        "review_decision": "needs-edits",
    })
    forbidden_form = dict(accept_form)
    forbidden_form["owner_decision"] = "approved"
    stale_date_form = dict(accept_form)
    stale_date_form["human_reviewed_at"] = "2000-01-01"
    hash_mismatch_form = dict(accept_form)
    hash_mismatch_form["content_sha256"] = "0" * 64
    archive_only_form = dict(forms[2])
    archive_only_form.update({
        "human_reviewed_by": "regression-fixture-human",
        "human_reviewed_at": today.isoformat(),
        "review_basis": "Regression fixture records archive-only without changing lifecycle.",
        "review_decision": "archive-only",
    })

    accept_path = temp_root / "accept.jsonl"
    needs_edits_path = temp_root / "needs-edits.jsonl"
    forbidden_path = temp_root / "forbidden.jsonl"
    stale_date_path = temp_root / "stale-date.jsonl"
    hash_mismatch_path = temp_root / "hash-mismatch.jsonl"
    archive_only_path = temp_root / "archive-only.jsonl"
    accept_path.write_text(json.dumps(accept_form, ensure_ascii=False, separators=(",", ":")) + "\n")
    needs_edits_path.write_text(json.dumps(needs_edits_form, ensure_ascii=False, separators=(",", ":")) + "\n")
    forbidden_path.write_text(json.dumps(forbidden_form, ensure_ascii=False, separators=(",", ":")) + "\n")
    stale_date_path.write_text(json.dumps(stale_date_form, ensure_ascii=False, separators=(",", ":")) + "\n")
    hash_mismatch_path.write_text(json.dumps(hash_mismatch_form, ensure_ascii=False, separators=(",", ":")) + "\n")
    archive_only_path.write_text(json.dumps(archive_only_form, ensure_ascii=False, separators=(",", ":")) + "\n")

    before_status_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--strict", "--json", "--as-of", today.isoformat()])
    dry_run_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-review-queue-apply.sh", "--forms", str(accept_path), "--dry-run", "--json"])
    forbidden_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-review-queue-apply.sh", "--forms", str(forbidden_path), "--dry-run", "--json"])
    stale_date_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-review-queue-apply.sh", "--forms", str(stale_date_path), "--dry-run", "--json"])
    hash_mismatch_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-review-queue-apply.sh", "--forms", str(hash_mismatch_path), "--dry-run", "--json"])
    archive_only_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-review-queue-apply.sh", "--forms", str(archive_only_path), "--dry-run", "--json"])
    apply_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-review-queue-apply.sh", "--forms", str(accept_path), "--apply", "--json"])
    after_accept_check_result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-check.sh",
            "--dry-run",
            "--json",
            "--diagnostics",
            "--as-of",
            today.isoformat(),
        ],
    )
    after_accept_status_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--strict", "--json", "--as-of", today.isoformat()])
    review_body_path = repo / str(accept_form.get("path", ""))
    original_review_body = review_body_path.read_text()
    try:
        review_body_path.write_text(original_review_body + "\n<!-- regression review content drift -->\n")
        drift_status_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--strict", "--json", "--as-of", today.isoformat()])
        drift_check_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics", "--as-of", today.isoformat()])
    finally:
        review_body_path.write_text(original_review_body)
    needs_edits_apply_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-review-queue-apply.sh", "--forms", str(needs_edits_path), "--apply", "--json"])
    after_needs_edits_status_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--strict", "--json", "--as-of", today.isoformat()])
    archive_only_apply_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-review-queue-apply.sh", "--forms", str(archive_only_path), "--apply", "--json"])
    after_archive_status_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--strict", "--json", "--as-of", today.isoformat()])
    archive_review_body_path = repo / str(archive_only_form.get("path", ""))
    original_archive_review_body = archive_review_body_path.read_text()
    try:
        archive_review_body_path.write_text(original_archive_review_body + "\n<!-- regression terminal review content drift -->\n")
        archive_drift_status_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--strict", "--json", "--as-of", today.isoformat()])
        archive_drift_check_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics", "--as-of", today.isoformat()])
    finally:
        archive_review_body_path.write_text(original_archive_review_body)

    payloads = {}
    for name, result in [
        ("before", before_status_result),
        ("dry_run", dry_run_result),
        ("forbidden", forbidden_result),
        ("stale_date", stale_date_result),
        ("hash_mismatch", hash_mismatch_result),
        ("archive_only", archive_only_result),
        ("apply", apply_result),
        ("after_accept_check", after_accept_check_result),
        ("after_accept", after_accept_status_result),
        ("drift_status", drift_status_result),
        ("drift_check", drift_check_result),
        ("needs_edits_apply", needs_edits_apply_result),
        ("after_needs_edits", after_needs_edits_status_result),
        ("archive_only_apply", archive_only_apply_result),
        ("after_archive", after_archive_status_result),
        ("archive_drift_status", archive_drift_status_result),
        ("archive_drift_check", archive_drift_check_result),
    ]:
        try:
            payloads[name] = json.loads(result["stdout"])
        except Exception as exc:
            payloads[name] = {}
            parse_errors.append(f"{name}: {exc}")

    def pending_count(name):
        return int(payloads.get(name, {}).get("review_queues", {}).get("summary", {}).get("total_pending_count", -1))

    forbidden_codes = [
        row.get("code")
        for row in payloads.get("forbidden", {}).get("diagnostics", [])
        if isinstance(row, dict)
    ]
    stale_date_codes = [
        row.get("code")
        for row in payloads.get("stale_date", {}).get("diagnostics", [])
        if isinstance(row, dict)
    ]
    hash_mismatch_codes = [
        row.get("code")
        for row in payloads.get("hash_mismatch", {}).get("diagnostics", [])
        if isinstance(row, dict)
    ]
    items_by_id = {}
    for line in (repo / "registry" / "items.jsonl").read_text().splitlines():
        if not line.strip():
            continue
        item = json.loads(line)
        items_by_id[item.get("id")] = item
    accept_item_id = accept_form.get("id")
    needs_edits_item_id = needs_edits_form.get("id")
    archive_only_item_id = archive_only_form.get("id")
    accept_item = items_by_id.get(accept_item_id, {})
    needs_edits_item = items_by_id.get(needs_edits_item_id, {})
    archive_only_item = items_by_id.get(archive_only_item_id, {})
    accept_current_hash = hashlib.sha256(
        (repo / str(accept_form.get("path", ""))).read_bytes()
    ).hexdigest()
    archive_only_current_hash = hashlib.sha256(
        (repo / str(archive_only_form.get("path", ""))).read_bytes()
    ).hexdigest()
    archive_drift_rows = payloads.get("archive_drift_status", {}).get("review_queues", {}).get("ai_generated_pending", [])

    expect(
        forms_result["exit_code"] == 0
        and len(forms) >= 3
        and not parse_errors
        and all(form.get("schema_version") == 2 for form in forms)
        and all(len(form.get("content_sha256", "")) == 64 for form in forms)
        and before_status_result["exit_code"] != 0
        and pending_count("before") >= 3
        and dry_run_result["exit_code"] == 0
        and payloads.get("dry_run", {}).get("status") == "planned"
        and payloads.get("dry_run", {}).get("applied") is False
        and forbidden_result["exit_code"] != 0
        and "forbidden-owner-field" in forbidden_codes
        and stale_date_result["exit_code"] != 0
        and "human-reviewed-at-before-created-at" in stale_date_codes
        and hash_mismatch_result["exit_code"] != 0
        and "content-sha256-mismatch" in hash_mismatch_codes
        and archive_only_result["exit_code"] == 0
        and payloads.get("archive_only", {}).get("planned_updates", [{}])[0].get("status_before")
            == payloads.get("archive_only", {}).get("planned_updates", [{}])[0].get("status_after")
        and payloads.get("archive_only", {}).get("planned_updates", [{}])[0].get("lifecycle_mutation") is False
        and apply_result["exit_code"] == 0
        and payloads.get("apply", {}).get("status") == "applied"
        and after_accept_check_result["exit_code"] == 0
        and payloads.get("after_accept_check", {}).get("frontmatter_status_health", {}).get("status") == "pass"
        and str(accept_form.get("path", ""))
            in payloads.get("apply", {}).get("transaction_result", {}).get("changed_paths", [])
        and "registry/items.jsonl"
            in payloads.get("apply", {}).get("transaction_result", {}).get("changed_paths", [])
        and pending_count("after_accept") == pending_count("before") - 1
        and accept_item.get("human_reviewed_by") == "regression-fixture-human"
        and accept_item.get("human_review_decision") == "accept-as-review-record"
        and accept_item.get("human_review_content_sha256") == accept_current_hash
        and accept_current_hash != accept_form.get("content_sha256")
        and accept_item.get("review_status") == "human-reviewed-accepted"
        and pending_count("drift_status") == pending_count("before")
        and drift_check_result["exit_code"] != 0
        and "human review content drift" in drift_check_result["stdout"]
        and needs_edits_apply_result["exit_code"] == 0
        and needs_edits_item.get("human_review_decision") == "needs-edits"
        and needs_edits_item.get("review_status") == "human-review-needs-edits"
        and pending_count("after_needs_edits") == pending_count("after_accept")
        and any(
            blocker.get("id") == "review-queue-pending-product"
            for blocker in payloads.get("after_needs_edits", {}).get("strict_blockers", [])
        )
        and archive_only_apply_result["exit_code"] == 0
        and payloads.get("archive_only_apply", {}).get("status") == "applied"
        and archive_only_item.get("status") == archive_only_form.get("read_only_context", {}).get("registry_status")
        and archive_only_item.get("human_review_decision") == "archive-only"
        and archive_only_item.get("human_review_content_sha256") == archive_only_current_hash
        and archive_only_item.get("review_status") == "human-reviewed-archive-only"
        and pending_count("after_archive") == pending_count("after_accept") - 1
        and pending_count("archive_drift_status")
        == pending_count("after_archive") + 1
        and any(
            row.get("id") == archive_only_item_id
            and "unresolved-content-sha256-drift" in row.get("reasons", [])
            for row in archive_drift_rows
        )
        and archive_drift_check_result["exit_code"] != 0
        and f"items:{archive_only_item_id} human review content drift" in archive_drift_check_result["stdout"],
        "review-queue-apply-tool-contract",
        "review queue apply validates and applies filled forms without owner-gate mutation",
        {
            "forms_exit_code": forms_result["exit_code"],
            "parse_errors": parse_errors,
            "before_exit_code": before_status_result["exit_code"],
            "before_pending": pending_count("before"),
            "dry_run_exit_code": dry_run_result["exit_code"],
            "dry_run_payload": payloads.get("dry_run", {}),
            "forbidden_exit_code": forbidden_result["exit_code"],
            "forbidden_codes": forbidden_codes,
            "stale_date_exit_code": stale_date_result["exit_code"],
            "stale_date_codes": stale_date_codes,
            "hash_mismatch_exit_code": hash_mismatch_result["exit_code"],
            "hash_mismatch_codes": hash_mismatch_codes,
            "archive_only_payload": payloads.get("archive_only", {}),
            "apply_exit_code": apply_result["exit_code"],
            "after_accept_check_exit_code": after_accept_check_result["exit_code"],
            "after_accept_frontmatter_status": payloads.get("after_accept_check", {}).get("frontmatter_status_health", {}).get("status"),
            "after_accept_pending": pending_count("after_accept"),
            "drift_pending": pending_count("drift_status"),
            "drift_check_exit_code": drift_check_result["exit_code"],
            "needs_edits_apply_exit_code": needs_edits_apply_result["exit_code"],
            "after_needs_edits_pending": pending_count("after_needs_edits"),
            "archive_only_apply_exit_code": archive_only_apply_result["exit_code"],
            "after_archive_pending": pending_count("after_archive"),
            "archive_drift_pending": pending_count("archive_drift_status"),
            "archive_drift_check_exit_code": archive_drift_check_result["exit_code"],
            "accept_item": accept_item,
            "needs_edits_item": needs_edits_item,
            "archive_only_item": archive_only_item,
        },
        repo,
    )

def test_external_review_queue_apply_persists_source_metadata():
    repo = copy_repo("external-review-queue-apply")
    item_id = seed_pending_external_review_queue_item(repo)
    forms_result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-index-plan.sh",
            "--section",
            "review-queue",
            "--queue-forms-jsonl",
            "--queue-type",
            "external-source-review",
            "--queue-limit",
            "1",
        ],
    )
    parse_errors = []
    forms = []
    for line in forms_result["stdout"].splitlines():
        if not line.strip():
            continue
        try:
            forms.append(json.loads(line))
        except Exception as exc:
            parse_errors.append(str(exc))
    if len(forms) != 1:
        expect(
            False,
            "external-review-queue-apply-source-metadata",
            "external review apply persists source metadata and clears the queue",
            {
                "setup_error": "expected exactly one external review form",
                "parse_errors": parse_errors,
                "stdout": forms_result["stdout"][:1000],
            },
            repo,
        )
        return

    completed_form = dict(forms[0])
    completed_form.update({
        "human_reviewed_by": "regression-fixture-human",
        "human_reviewed_at": today.isoformat(),
        "review_basis": "Regression fixture reviewed the external source metadata.",
        "review_decision": "accept-as-review-record",
        "retrieved_at": today.isoformat(),
        "read_status": "reviewed-summary",
        "source_license": "fixture-only",
    })
    missing_license_form = dict(completed_form)
    missing_license_form["source_license"] = ""

    temp_root = pathlib.Path(tempfile.mkdtemp(prefix="kh-regression-external-review-"))
    temp_roots.append(temp_root)
    completed_path = temp_root / "completed.jsonl"
    missing_license_path = temp_root / "missing-license.jsonl"
    completed_path.write_text(
        json.dumps(completed_form, ensure_ascii=False, separators=(",", ":")) + "\n"
    )
    missing_license_path.write_text(
        json.dumps(missing_license_form, ensure_ascii=False, separators=(",", ":")) + "\n"
    )

    before_result = run_cmd(
        repo,
        ["rtk", "bash", "tools/knowledge-status.sh", "--strict", "--json", "--as-of", today.isoformat()],
    )
    missing_license_result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-review-queue-apply.sh",
            "--forms",
            str(missing_license_path),
            "--dry-run",
            "--json",
        ],
    )
    dry_run_result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-review-queue-apply.sh",
            "--forms",
            str(completed_path),
            "--dry-run",
            "--json",
        ],
    )
    apply_result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-review-queue-apply.sh",
            "--forms",
            str(completed_path),
            "--apply",
            "--json",
        ],
    )
    after_check_result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-check.sh",
            "--dry-run",
            "--json",
            "--diagnostics",
            "--as-of",
            today.isoformat(),
        ],
    )
    after_result = run_cmd(
        repo,
        ["rtk", "bash", "tools/knowledge-status.sh", "--strict", "--json", "--as-of", today.isoformat()],
    )

    payloads = {}
    for name, result in [
        ("before", before_result),
        ("missing_license", missing_license_result),
        ("dry_run", dry_run_result),
        ("apply", apply_result),
        ("after_check", after_check_result),
        ("after", after_result),
    ]:
        try:
            payloads[name] = json.loads(result["stdout"])
        except Exception as exc:
            payloads[name] = {}
            parse_errors.append(f"{name}: {exc}")
    item = {}
    for line in (repo / "registry" / "items.jsonl").read_text().splitlines():
        if not line.strip():
            continue
        candidate = json.loads(line)
        if candidate.get("id") == item_id:
            item = candidate
            break

    def pending_count(name):
        return int(
            payloads.get(name, {})
            .get("review_queues", {})
            .get("summary", {})
            .get("total_pending_count", -1)
        )

    missing_license_codes = [
        row.get("code")
        for row in payloads.get("missing_license", {}).get("diagnostics", [])
        if isinstance(row, dict)
    ]
    current_content_sha256 = hashlib.sha256(
        (repo / str(completed_form.get("path", ""))).read_bytes()
    ).hexdigest()
    expect(
        forms_result["exit_code"] == 0
        and not parse_errors
        and before_result["exit_code"] != 0
        and missing_license_result["exit_code"] != 0
        and "missing-required-external-review-field" in missing_license_codes
        and dry_run_result["exit_code"] == 0
        and payloads.get("dry_run", {}).get("status") == "planned"
        and apply_result["exit_code"] == 0
        and payloads.get("apply", {}).get("status") == "applied"
        and after_check_result["exit_code"] == 0
        and payloads.get("after_check", {}).get("frontmatter_status_health", {}).get("status") == "pass"
        and str(completed_form.get("path", ""))
            in payloads.get("apply", {}).get("transaction_result", {}).get("changed_paths", [])
        and pending_count("after") == pending_count("before") - 2
        and item.get("retrieved_at") == today.isoformat()
        and item.get("read_status") == "reviewed-summary"
        and item.get("source_license") == "fixture-only"
        and item.get("human_review_decision") == "accept-as-review-record"
        and item.get("human_review_content_sha256") == current_content_sha256
        and current_content_sha256 != completed_form.get("content_sha256"),
        "external-review-queue-apply-source-metadata",
        "external review apply persists source metadata and clears the queue",
        {
            "forms_exit_code": forms_result["exit_code"],
            "parse_errors": parse_errors,
            "before_pending": pending_count("before"),
            "missing_license_exit_code": missing_license_result["exit_code"],
            "missing_license_codes": missing_license_codes,
            "dry_run_exit_code": dry_run_result["exit_code"],
            "apply_exit_code": apply_result["exit_code"],
            "after_check_exit_code": after_check_result["exit_code"],
            "after_frontmatter_status": payloads.get("after_check", {}).get("frontmatter_status_health", {}).get("status"),
            "after_pending": pending_count("after"),
            "item": item,
        },
        repo,
    )

def test_summary_backfill_archived_only_contract():
    repo = copy_repo("summary-backfill")
    items_path = repo / "registry" / "items.jsonl"
    target_archived = "knowledge-hub-archived-summary-full-closeout-20260711"
    target_active = "knowledge-hub-root"
    target_reviewing = "pcr02-camera-raw-preview-virtual-stream-architecture-20260711"
    artifact_id = "knowledge-hub-summary-backfill-regression-closeout-20260711"
    md_path = repo / "artifacts" / "manifests" / f"{artifact_id}.md"
    jsonl_path = repo / "artifacts" / "manifests" / f"{artifact_id}.jsonl"

    rows = []
    seen = set()
    for line in items_path.read_text().splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        if row.get("id") in {target_archived, target_active, target_reviewing}:
            row.pop("summary_zh", None)
            seen.add(row.get("id"))
        rows.append(row)
    items_path.write_text("\n".join(json.dumps(row, ensure_ascii=False, separators=(",", ":")) for row in rows) + "\n")
    before_hash = hashlib.sha256(items_path.read_bytes()).hexdigest()

    dry_run = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-summary-backfill.sh",
            "--as-of",
            today.isoformat(),
            "--artifact-id",
            artifact_id,
            "--json",
        ],
    )
    after_dry_hash = hashlib.sha256(items_path.read_bytes()).hexdigest()
    dry_md_exists = md_path.exists()
    dry_jsonl_exists = jsonl_path.exists()
    apply_result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-summary-backfill.sh",
            "--apply",
            "--as-of",
            today.isoformat(),
            "--artifact-id",
            artifact_id,
            "--json",
        ],
    )

    parse_errors = []
    try:
        dry_payload = json.loads(dry_run["stdout"])
    except Exception as exc:
        dry_payload = {}
        parse_errors.append(f"dry_run: {exc}")
    try:
        apply_payload = json.loads(apply_result["stdout"])
    except Exception as exc:
        apply_payload = {}
        parse_errors.append(f"apply: {exc}")

    items_by_id = {}
    for line in items_path.read_text().splitlines():
        if line.strip():
            row = json.loads(line)
            items_by_id[row.get("id")] = row

    index_texts = {
        "by-owner": (repo / "indexes" / "by-owner.md").read_text(),
        "by-status": (repo / "indexes" / "by-status.md").read_text(),
        "by-review-date": (repo / "indexes" / "by-review-date.md").read_text(),
        "by-decision": (repo / "indexes" / "by-decision.md").read_text(),
    }
    index_refs_present = all(artifact_id in text for text in index_texts.values())
    artifact_json = {}
    try:
        artifact_json = json.loads(jsonl_path.read_text())
    except Exception as exc:
        parse_errors.append(f"artifact_jsonl: {exc}")

    expect(
        seen == {target_archived, target_active, target_reviewing}
        and dry_run["exit_code"] == 0
        and dry_payload.get("mode") == "dry-run"
        and dry_payload.get("selected_count") == 1
        and dry_payload.get("updated_ids") == [target_archived]
        and before_hash == after_dry_hash
        and not dry_md_exists
        and not dry_jsonl_exists
        and apply_result["exit_code"] == 0
        and apply_payload.get("mode") == "apply"
        and apply_payload.get("selected_count") == 1
        and apply_payload.get("updated_ids") == [target_archived]
        and items_by_id.get(target_archived, {}).get("summary_zh")
        and not items_by_id.get(target_active, {}).get("summary_zh")
        and not items_by_id.get(target_reviewing, {}).get("summary_zh")
        and items_by_id.get(artifact_id, {}).get("status") == "archived"
        and md_path.exists()
        and jsonl_path.exists()
        and artifact_json.get("artifact_id") == artifact_id
        and artifact_json.get("selected_count") == 1
        and index_refs_present
        and not parse_errors,
        "summary-backfill-archived-only-contract",
        "summary backfill dry-run is no-write and apply only updates archived missing summaries",
        {
            "seen": sorted(seen),
            "dry_exit_code": dry_run["exit_code"],
            "apply_exit_code": apply_result["exit_code"],
            "dry_payload": dry_payload,
            "apply_payload": apply_payload,
            "before_hash": before_hash,
            "after_dry_hash": after_dry_hash,
            "dry_md_exists": dry_md_exists,
            "dry_jsonl_exists": dry_jsonl_exists,
            "active_summary_present": bool(items_by_id.get(target_active, {}).get("summary_zh")),
            "reviewing_summary_present": bool(items_by_id.get(target_reviewing, {}).get("summary_zh")),
            "index_refs_present": index_refs_present,
            "parse_errors": parse_errors,
        },
        repo,
    )
