"""Generated regression cases: lifecycle 4."""

# Generated by regression_codegen.py; edit assertions here, then keep the generator deterministic.
from .support import *  # noqa: F401,F403

def test_orphan_files_advisory_contract():
    repo = copy_repo("orphan-files")
    git_setup = init_temp_git_repo(repo)
    git_config = run_cmd(
        repo,
        ["rtk", "git", "config", "status.showUntrackedFiles", "no"],
    )
    deleted_rel = "governance/deleted-orphan-regression-fixture.md"
    deleted_path = repo / deleted_rel
    deleted_path.write_text("# Deleted orphan regression fixture\n")
    git_add = run_cmd(repo, ["rtk", "git", "add", deleted_rel])
    git_commit = run_cmd(
        repo,
        [
            "rtk",
            "git",
            "-c",
            "user.name=Knowledge Hub Regression",
            "-c",
            "user.email=regression@knowledge-hub.local",
            "commit",
            "-m",
            "test: track deleted orphan fixture",
        ],
    )
    deleted_path.unlink()
    deleted_candidate = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-orphan-files.sh",
            "--strict",
            "--json",
        ],
    )
    baseline = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-orphan-files.sh",
            "--all",
            "--strict",
            "--json",
            "--limit",
            "20",
        ],
    )
    registered_rel = (
        "projects/xcrz-sigmastar-demo/archive/debug/"
        "registered-regression-fixture.md"
    )
    registered_path = repo / registered_rel
    registered_path.parent.mkdir(parents=True, exist_ok=True)
    registered_path.write_text(
        "# Registered regression fixture\n\n"
        "This file is intentionally covered by an exact registry path.\n"
    )
    with (repo / "registry" / "items.jsonl").open("a") as stream:
        stream.write(
            json.dumps(
                {
                    "id": "registered-regression-fixture",
                    "path": registered_rel,
                }
            )
            + "\n"
        )
    registered_candidate = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-orphan-files.sh",
            "--all",
            "--strict",
            "--json",
            "--limit",
            "20",
        ],
    )
    orphan_rel = "projects/xcrz-sigmastar-demo/archive/debug/orphan-regression-fixture.md"
    orphan_path = repo / orphan_rel
    orphan_path.parent.mkdir(parents=True, exist_ok=True)
    orphan_path.write_text("# Orphan regression fixture\n\nThis file intentionally has no registry item.\n")

    advisory = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-orphan-files.sh",
            "--all",
            "--json",
            "--limit",
            "500",
        ],
    )
    strict = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-orphan-files.sh",
            "--all",
            "--strict",
            "--json",
            "--limit",
            "500",
        ],
    )
    parse_errors = []
    try:
        deleted_candidate_payload = json.loads(deleted_candidate["stdout"])
    except Exception as exc:
        deleted_candidate_payload = {}
        parse_errors.append(f"deleted-candidate: {exc}")
    try:
        baseline_payload = json.loads(baseline["stdout"])
    except Exception as exc:
        baseline_payload = {}
        parse_errors.append(f"baseline: {exc}")
    try:
        registered_candidate_payload = json.loads(registered_candidate["stdout"])
    except Exception as exc:
        registered_candidate_payload = {}
        parse_errors.append(f"registered-candidate: {exc}")
    try:
        advisory_payload = json.loads(advisory["stdout"])
    except Exception as exc:
        advisory_payload = {}
        parse_errors.append(f"advisory: {exc}")
    try:
        strict_payload = json.loads(strict["stdout"])
    except Exception as exc:
        strict_payload = {}
        parse_errors.append(f"strict: {exc}")

    frontmatter_path = repo / "governance" / "obsidian-integration.md"
    frontmatter_text = frontmatter_path.read_text()
    frontmatter_path.write_text(frontmatter_text.replace("status: reviewing", "status: active", 1))
    artifact_manifest = repo / "artifacts" / "manifests" / "patent-disclosure-artifact-ref-20260619.jsonl"
    required_artifact = None
    for line in artifact_manifest.read_text().splitlines():
        row = json.loads(line)
        if row.get("vault_presence", "required") == "required":
            required_artifact = repo / "artifacts" / "vault" / "patent-disclosure" / row["source_path"]
            break
    if required_artifact is not None:
        required_artifact.unlink()
    negative_check = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-check.sh",
            "--dry-run",
            "--json",
            "--diagnostics",
            "--as-of",
            "2026-07-13",
        ],
    )
    try:
        negative_payload = json.loads(negative_check["stdout"])
    except Exception as exc:
        negative_payload = {}
        parse_errors.append(f"negative-check: {exc}")
    negative_categories = {
        row.get("id")
        for row in negative_payload.get("diagnostics", {}).get("categories", [])
        if isinstance(row, dict)
    }

    expect(
        not git_setup
        and git_config["exit_code"] == 0
        and git_add["exit_code"] == 0
        and git_commit["exit_code"] == 0
        and deleted_candidate["exit_code"] == 0
        and deleted_candidate_payload.get("status") == "ok"
        and deleted_rel not in deleted_candidate_payload.get("missing_registry", [])
        and baseline["exit_code"] == 0
        and baseline_payload.get("status") == "ok"
        and baseline_payload.get("missing_registry_count") == 0
        and baseline_payload.get("collection_covered_count", 0) > 0
        and baseline_payload.get("coverage_contract_status") == "pass"
        and registered_candidate["exit_code"] == 0
        and registered_candidate_payload.get("status") == "ok"
        and registered_rel
        not in registered_candidate_payload.get("missing_registry", [])
        and registered_candidate_payload.get("coverage_contract_status") == "pass"
        and advisory["exit_code"] == 0
        and strict["exit_code"] == 1
        and advisory_payload.get("mode") == "all"
        and advisory_payload.get("status") == "needs-fix"
        and orphan_rel in advisory_payload.get("missing_registry", [])
        and strict_payload.get("strict") is True
        and orphan_rel in strict_payload.get("missing_registry", [])
        and negative_check["exit_code"] == 1
        and {"frontmatter-status", "artifact-vault"}.issubset(negative_categories)
        and not parse_errors,
        "orphan-files-advisory-contract",
        "frozen body coverage passes at baseline while orphan, frontmatter drift and missing vault files fail closed",
        {
            "baseline_exit_code": baseline["exit_code"],
            "git_setup": git_setup,
            "git_config_exit_code": git_config["exit_code"],
            "git_add_exit_code": git_add["exit_code"],
            "git_commit_exit_code": git_commit["exit_code"],
            "deleted_candidate_exit_code": deleted_candidate["exit_code"],
            "deleted_candidate_status": deleted_candidate_payload.get("status"),
            "deleted_candidate_missing_registry": deleted_candidate_payload.get("missing_registry"),
            "baseline_status": baseline_payload.get("status"),
            "baseline_exact_registered_count": baseline_payload.get("exact_registered_count"),
            "baseline_collection_covered_count": baseline_payload.get("collection_covered_count"),
            "baseline_coverage_contract_status": baseline_payload.get("coverage_contract_status"),
            "registered_candidate_exit_code": registered_candidate["exit_code"],
            "registered_candidate_status": registered_candidate_payload.get("status"),
            "registered_candidate_missing_registry": registered_candidate_payload.get(
                "missing_registry"
            ),
            "registered_candidate_coverage_contract_status": registered_candidate_payload.get(
                "coverage_contract_status"
            ),
            "advisory_exit_code": advisory["exit_code"],
            "strict_exit_code": strict["exit_code"],
            "advisory_missing_registry": advisory_payload.get("missing_registry"),
            "strict_missing_registry": strict_payload.get("missing_registry"),
            "strict_coverage_contract_status": strict_payload.get("coverage_contract_status"),
            "negative_check_exit_code": negative_check["exit_code"],
            "negative_categories": sorted(negative_categories),
            "parse_errors": parse_errors,
        },
        repo,
    )

def test_reviewing_triage_json_contract():
    command = [
        "rtk",
        "bash",
        "tools/knowledge-reviewing-triage.sh",
        "--json",
        "--as-of",
        today.isoformat(),
    ]
    result = run_cmd(root, command)
    parse_error = ""
    try:
        payload = json.loads(result["stdout"])
    except Exception as exc:
        payload = {}
        parse_error = str(exc)
    expect(
        result["exit_code"] == 0
        and payload.get("read_only") is True
        and payload.get("report_only") is True
        and payload.get("reviewing_count", 0) >= 1
        and isinstance(payload.get("by_bucket"), dict)
        and isinstance(payload.get("by_recommended_action"), dict)
        and "不提升 active" in payload.get("must_not", [])
        and not parse_error,
        "reviewing-triage-json-contract",
        "reviewing triage helper emits read-only grouped queue without owner mutations",
        {
            "exit_code": result["exit_code"],
            "reviewing_count": payload.get("reviewing_count"),
            "by_bucket": payload.get("by_bucket"),
            "by_recommended_action": payload.get("by_recommended_action"),
            "parse_error": parse_error,
        },
    )

def test_source_manual_entry_guide():
    result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--source",
            "--source-id",
            "example-source",
            "--source-path",
            "sources/example-source",
            "--role",
            "hub-canonical-source",
            "--authority",
            "knowledge-hub-canonical",
            "--write-policy",
            "knowledge-hub-only",
            "--no-check-reason",
            "classify-first pending source coverage",
        ],
    )
    required_fragments = [
        "Knowledge Hub Source 登记向导",
        "registry/sources.json object",
        "indexes/by-source.md 主表行",
        "source coverage JSONL row",
        '"source_id":"example-source"',
        '"no_check_reason":"classify-first pending source coverage"',
        '"source_strategy":"hub-canonical-copy-docs"',
        '"final_disposition":"hub-canonical"',
        "rtk bash ~/knowledge-hub/tools/knowledge-index-plan.sh --section source",
    ]
    missing_fragments = [fragment for fragment in required_fragments if fragment not in result["stdout"]]
    today_compact = today.strftime("%Y%m%d")
    review_after_matches_today = f'"review_after":"{today.isoformat()}"' in result["stdout"]
    expect(
        result["exit_code"] == 0
        and not missing_fragments
        and f'"id":"SCC-{today_compact}-example-source"' in result["stdout"]
        and not review_after_matches_today,
        "source-manual-entry-guide",
        "source manual entry guide prints registry, index and coverage drafts",
        {
            "exit_code": result["exit_code"],
            "missing_fragments": missing_fragments,
            "today_compact": today_compact,
            "review_after_matches_today": review_after_matches_today,
            "stdout_sample": result["stdout"][:1400],
        },
    )

def test_source_manual_entry_enum_guide():
    result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--source",
            "--source-id",
            "example-source-enum",
            "--source-path",
            "sources/example-source-enum",
            "--role",
            "hub-canonical-source",
            "--authority",
            "knowledge-hub-canonical",
            "--write-policy",
            "knowledge-hub-only",
            "--no-check-reason",
            "classify-first pending source coverage",
        ],
    )
    invalid = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--source",
            "--source-id",
            "bad-source-enum",
            "--source-path",
            "sources/bad-source-enum",
            "--role",
            "bad-role",
            "--authority",
            "knowledge-hub-canonical",
            "--write-policy",
            "knowledge-hub-only",
            "--no-check-reason",
            "classify-first pending source coverage",
        ],
    )
    required_fragments = [
        "## 枚举速查",
        "role: hub-canonical-source",
        "authority: knowledge-hub-canonical",
        "write_policy: knowledge-hub-only",
        "final_disposition 常用值",
        "脚本会对已传入的 role、authority、status 和 write_policy 做预校验",
    ]
    missing_fragments = [fragment for fragment in required_fragments if fragment not in result["stdout"]]
    expect(
        result["exit_code"] == 0
        and not missing_fragments
        and invalid["exit_code"] != 0
        and "source role value is not allowed" in invalid["stderr"],
        "source-manual-entry-enum-guide",
        "source manual entry guide prints source enum quick reference and rejects invalid provided enums",
        {
            "exit_code": result["exit_code"],
            "missing_fragments": missing_fragments,
            "invalid_exit_code": invalid["exit_code"],
            "invalid_stderr": invalid["stderr"][:500],
            "stdout_sample": result["stdout"][:1800],
        },
    )

def test_source_manual_entry_guide_check_command():
    result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--source",
            "--source-id",
            "example-source-check",
            "--source-path",
            "sources/example-source-check",
            "--role",
            "hub-canonical-source",
            "--authority",
            "knowledge-hub-canonical",
            "--write-policy",
            "knowledge-hub-only",
            "--check",
            "rtk test -d sources/example-source-check",
        ],
    )
    registry_object_has_check = '"final_disposition":"hub-canonical","check":"rtk test -d sources/example-source-check"}' in result["stdout"]
    coverage_row_has_check = '"checked_at":"' in result["stdout"] and '"check":"rtk test -d sources/example-source-check","source_identity"' in result["stdout"]
    json_no_check_reason_absent = '"no_check_reason":' not in result["stdout"]
    expect(
        result["exit_code"] == 0
        and registry_object_has_check
        and coverage_row_has_check
        and json_no_check_reason_absent
        and '"source_id":"example-source-check"' in result["stdout"]
        and "rtk bash ~/knowledge-hub/tools/knowledge-index-plan.sh --section source" in result["stdout"],
        "source-manual-entry-guide-check-command",
        "source manual entry guide uses check fields consistently for registry and coverage drafts",
        {
            "exit_code": result["exit_code"],
            "registry_object_has_check": registry_object_has_check,
            "coverage_row_has_check": coverage_row_has_check,
            "json_no_check_reason_absent": json_no_check_reason_absent,
            "stdout_sample": result["stdout"][:1600],
        },
    )

def test_source_manual_entry_status_coverage_sync():
    registered_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--source",
            "--source-id",
            "example-source-current",
            "--source-path",
            "sources/example-source-current",
            "--role",
            "hub-canonical-source",
            "--authority",
            "knowledge-hub-canonical",
            "--write-policy",
            "knowledge-hub-only",
            "--no-check-reason",
            "classify-first pending source coverage",
        ],
    )
    removed_status_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--source",
            "--source-id",
            "example-source-status-option",
            "--source-path",
            "sources/example-source-status-option",
            "--role",
            "hub-canonical-source",
            "--authority",
            "knowledge-hub-canonical",
            "--write-policy",
            "knowledge-hub-only",
            "--source-status",
            "registered",
            "--no-check-reason",
            "classify-first pending source coverage",
        ],
    )
    expect(
        registered_result["exit_code"] == 0
        and '"status":"registered"' in registered_result["stdout"]
        and '"status":"registered-pending-classification"' in registered_result["stdout"]
        and removed_status_result["exit_code"] == 2
        and "ERROR unknown argument: --source-status" in removed_status_result["stderr"],
        "source-manual-entry-status-coverage-sync",
        "source manual entry emits the current registered status and rejects the removed status-selection option",
        {
            "registered_exit_code": registered_result["exit_code"],
            "removed_status_exit_code": removed_status_result["exit_code"],
            "registered_stdout_sample": registered_result["stdout"][:1800],
            "removed_status_stderr_sample": removed_status_result["stderr"][:800],
        },
    )

def test_source_manual_entry_unknown_owner_warning():
    result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--source",
            "--source-id",
            "example-source-owner-warning",
            "--source-path",
            "sources/example-source-owner-warning",
            "--role",
            "hub-canonical-source",
            "--authority",
            "knowledge-hub-canonical",
            "--write-policy",
            "knowledge-hub-only",
            "--check",
            "rtk test -d sources/example-source-owner-warning",
            "--owner",
            "unknown-source-owner",
        ],
    )
    expect(
        result["exit_code"] == 0
        and "- owner_registry_status: unknown-owner" in result["stdout"]
        and "owner_warning_zh" in result["stdout"]
        and "registry/owners.json" in result["stdout"]
        and '"owner":"unknown-source-owner"' in result["stdout"],
        "source-manual-entry-unknown-owner-warning",
        "source manual entry guide warns when source registry owner is not registered",
        {
            "exit_code": result["exit_code"],
            "stdout_sample": result["stdout"][:1600],
            "stderr_sample": result["stderr"][:500],
        },
    )

def test_source_manual_entry_requires_check_or_reason():
    common_args = [
        "rtk",
        "bash",
        "tools/knowledge-new.sh",
        "--source",
        "--source-id",
        "example-source-required",
        "--source-path",
        str(temp_dir / "example-required"),
        "--role",
        "hub-canonical-source",
        "--authority",
        "knowledge-hub-canonical",
        "--write-policy",
        "knowledge-hub-only",
    ]
    missing = run_cmd(root, common_args)
    conflict = run_cmd(
        root,
        common_args
        + [
            "--check",
            "rtk test -d sources/example-source-required",
            "--no-check-reason",
            "classify-first pending source coverage",
        ],
    )
    expect(
        missing["exit_code"] != 0
        and conflict["exit_code"] != 0
        and "requires either --check" in missing["stderr"]
        and "cannot combine --check with --no-check-reason" in conflict["stderr"],
        "source-manual-entry-requires-check-or-reason",
        "source manual entry guide requires exactly one check or no-check reason",
        {
            "missing_exit_code": missing["exit_code"],
            "conflict_exit_code": conflict["exit_code"],
            "missing_stderr": missing["stderr"][:500],
            "conflict_stderr": conflict["stderr"][:500],
        },
    )

def test_source_manual_entry_docs_check_preferred():
    readme_path = root / "README.md"
    tools_readme_path = root / "tools" / "README.md"
    help_result = run_cmd(root, ["rtk", "bash", "tools/knowledge-new.sh", "--help"])
    try:
        readme = readme_path.read_text()
        tools_readme = tools_readme_path.read_text()
        read_error = ""
    except Exception as exc:
        readme = ""
        tools_readme = ""
        read_error = str(exc)
    readme_required_fragments = [
        "--check",
        "--no-check-reason",
        "稳定只读",
        "registry source object 和 source coverage JSONL row 草稿都应记录 `check`",
        "不再补 JSON 形式的 `no_check_reason`",
    ]
    tools_required_fragments = [
        '--check "rtk test -d sources/<source-id>"',
        "--no-check-reason",
        "要求 `--check` 或 `--no-check-reason` 二选一",
        "优先使用稳定只读",
        "registry source object 和 source coverage JSONL row 草稿都应记录 `check`",
        "不再补 JSON 形式的 `no_check_reason`",
    ]
    readme_missing = [fragment for fragment in readme_required_fragments if fragment not in readme]
    tools_readme_missing = [fragment for fragment in tools_required_fragments if fragment not in tools_readme]
    help_has_check_example = (
        help_result["exit_code"] == 0
        and '--check "rtk test -d sources/example-source"' in help_result["stdout"]
        and "--no-check-reason" in help_result["stdout"]
    )
    expect(
        not read_error
        and not readme_missing
        and not tools_readme_missing
        and help_has_check_example,
        "source-manual-entry-docs-check-preferred",
        "source manual entry docs prefer check commands and preserve no-check fallback",
        {
            "read_error": read_error,
            "readme_missing": readme_missing,
            "tools_readme_missing": tools_readme_missing,
            "help_exit_code": help_result["exit_code"],
            "help_has_check_example": help_has_check_example,
            "help_stdout_sample": help_result["stdout"][:1000],
        },
    )

def test_source_manual_entry_role_aware_recommendations():
    agent_config_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--source",
            "--source-id",
            "example-agent-config-source",
            "--source-path",
            "sources/example-agent-config-source",
            "--role",
            "hub-native-source",
            "--authority",
            "knowledge-hub-ledger",
            "--write-policy",
            "hub-native-registry",
            "--check",
            "rtk test -d sources/example-agent-config-source",
        ],
    )
    auxiliary_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--source",
            "--source-id",
            "example-aux-memory-source",
            "--source-path",
            "sources/example-aux-memory-source",
            "--role",
            "hub-runtime-input",
            "--authority",
            "runtime-input-provenance",
            "--write-policy",
            "runtime-read-only-input",
            "--no-check-reason",
            "auxiliary recall source without stable check",
        ],
    )
    no_check_current_result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-new.sh",
            "--source",
            "--source-id",
            "example-current-no-check-source",
            "--source-path",
            "sources/example-current-no-check-source",
            "--role",
            "hub-canonical-source",
            "--authority",
            "knowledge-hub-canonical",
            "--write-policy",
            "knowledge-hub-only",
            "--no-check-reason",
            "classify-first pending source coverage",
        ],
    )
    expect(
        agent_config_result["exit_code"] == 0
        and auxiliary_result["exit_code"] == 0
        and no_check_current_result["exit_code"] == 0
        and "recommended_final_disposition: hub-native-source" in agent_config_result["stdout"]
        and "recommended_source_strategy: hub-native-ledger" in agent_config_result["stdout"]
        and '"final_disposition":"hub-native-source"' in agent_config_result["stdout"]
        and "recommendation_scope_zh: 以上只是人工填写提示，不代表 owner decision，不关闭 owner gate" in agent_config_result["stdout"]
        and "recommended_final_disposition: runtime-input-reference-only" in auxiliary_result["stdout"]
        and "recommended_source_strategy: runtime-input-index-summary-only" in auxiliary_result["stdout"]
        and "不写 memory" in auxiliary_result["stdout"]
        and "recommended_final_disposition: hub-canonical" in no_check_current_result["stdout"]
        and "no_check_reason: classify-first pending source coverage" in no_check_current_result["stdout"]
        and '"final_disposition":"hub-canonical"' in no_check_current_result["stdout"],
        "source-manual-entry-role-aware-recommendations",
        "source manual entry guide gives role-aware recommendations without replacing conservative copyable JSON",
        {
            "agent_config_exit_code": agent_config_result["exit_code"],
            "auxiliary_exit_code": auxiliary_result["exit_code"],
            "no_check_current_exit_code": no_check_current_result["exit_code"],
            "agent_config_stdout_sample": agent_config_result["stdout"][:1800],
            "auxiliary_stdout_sample": auxiliary_result["stdout"][:1800],
            "no_check_current_stdout_sample": no_check_current_result["stdout"][:1800],
        },
    )
