"""Generated regression cases: model."""

# Generated by regression_codegen.py; edit assertions here, then keep the generator deterministic.
from .support import *  # noqa: F401,F403

def test_governance_goal_path_allowed():
    result = run_cmd(
        root,
        [
            "rtk",
            "bash",
            "tools/knowledge-check.sh",
            "--dry-run",
            "--json",
            "--explain",
            "knowledge-hub-simplified-final-version-goal",
        ],
    )
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    explain = parsed.get("explain", {})
    registry = explain.get("registry", {})
    expect(
        result["exit_code"] == 0
        and parsed.get("status") == "pass"
        and explain.get("found") is True
        and registry.get("path") == "docs/goals/knowledge-hub-simplified-final-version.md"
        and registry.get("path_exists") is True,
        "governance-goal-path-allowed",
        "governance goal docs path is accepted and explainable",
        {
            "exit_code": result["exit_code"],
            "status": parsed.get("status"),
            "found": explain.get("found"),
            "path": registry.get("path"),
            "path_exists": registry.get("path_exists"),
            "stdout_sample": result["stdout"][:1000],
        },
    )

def test_manifest_regression_count_capture_qualifier():
    manifests = sorted((root / "artifacts" / "manifests").glob("knowledge-hub-*20260623.md"))
    count_patterns = [
        re.compile(r"\d+\s*个\s*regression\s*场景"),
        re.compile(r"\d+\s*个\s*回归\s*场景"),
        re.compile(r"回归覆盖扩展到\s*\d+\s*项"),
        re.compile(r"回归覆盖说明更新到\s*\d+\s*项"),
    ]
    qualifier_patterns = [
        "历史捕获",
        "当次捕获",
        "本次运行",
        "以 live 输出为准",
        "以 live 回归输出为准",
        "以 `tools/knowledge-regression.sh --json`",
        "registry 实时派生值",
        "不应作为固定历史事实手工维护",
    ]
    violations = []
    for manifest in manifests:
        if manifest.name == "knowledge-hub-governance-regression-helper-20260619.md":
            continue
        for line_no, line in enumerate(manifest.read_text().splitlines(), start=1):
            if not any(pattern.search(line) for pattern in count_patterns):
                continue
            if any(qualifier in line for qualifier in qualifier_patterns):
                continue
            violations.append(
                {
                    "path": str(manifest.relative_to(root)),
                    "line": line_no,
                    "text": line.strip(),
                }
            )
    expect(
        not violations,
        "manifest-regression-count-capture-qualifier",
        "dated governance manifests qualify fixed regression counts as historical captures",
        {"violations": violations},
    )

def test_manifest_profile_boundary_advisory():
    json_result = run_cmd(root, ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "manifest", "--json"])
    text_result = run_cmd(root, ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "manifest"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(json_result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    manifest_index = parsed.get("indexes", {}).get("by_manifest", {}) if isinstance(parsed, dict) else {}
    summary = manifest_index.get("summary", {})
    profile_health = summary.get("profile_health", {})
    profile_next_actions = summary.get("profile_health_next_actions_zh", {})
    rows = manifest_index.get("rows", [])
    advisory_rows = [row for row in rows if row.get("profile_health") == "advisory-missing-boundary"]
    expect(
        json_result["exit_code"] == 0
        and text_result["exit_code"] == 0
        and not parse_error
        and profile_health.get("advisory-missing-boundary", 0) >= 1
        and "missing-boundary" not in profile_health
        and advisory_rows
        and "advisory-* 仅提示人工补强方向" in summary.get("profile_health_zh", "")
        and "不回填历史正文" in profile_next_actions.get("advisory-missing-boundary", "")
        and "后续新增治理 manifest" in profile_next_actions.get("advisory-missing-boundary", "")
        and "当前 profile 基础字段缺失" in profile_next_actions.get("missing-summary", "")
        and "advisory-missing-boundary" in text_result["stdout"]
        and "missing-summary/missing-evidence" in text_result["stdout"],
        "manifest-profile-boundary-advisory",
        "manifest profile reports missing boundaries as advisory rather than hard-failure-looking status",
        {
            "json_exit_code": json_result["exit_code"],
            "text_exit_code": text_result["exit_code"],
            "parse_error": parse_error,
            "profile_health": profile_health,
            "profile_health_next_actions_zh": profile_next_actions,
            "advisory_sample": advisory_rows[:3],
            "profile_health_zh": summary.get("profile_health_zh", ""),
            "stdout_sample": text_result["stdout"][:1200],
        },
    )

def test_offline_validation_template_placeholders():
    template_names = [
        "item.md",
        "archive-note.md",
        "debug-record.md",
        "external-source-note.md",
        "validation-report.md",
    ]
    missing = {}
    for name in template_names:
        text = (root / "templates" / name).read_text()
        required = [
            "manual_validation_pending: true",
            "manual_validation_reason:",
            "required_followup: rtk bash ~/knowledge-hub/tools/knowledge-check.sh --dry-run --json --diagnostics",
            "owner:",
            "review_after:",
        ]
        gaps = [fragment for fragment in required if fragment not in text]
        if gaps:
            missing[name] = gaps
    expect(
        not missing,
        "offline-validation-template-placeholders",
        "high-frequency templates carry optional manual_validation_pending placeholders for offline maintenance",
        {
            "missing": missing,
            "template_count": len(template_names),
        },
    )

def test_governance_audit_readability_gate():
    repo = copy_repo("governance-audit-readability-gate")
    items_path = repo / "registry" / "items.jsonl"
    rows = [json.loads(line) for line in items_path.read_text().splitlines() if line.strip()]
    target_found = False
    for row in rows:
        if row.get("id") == "knowledge-hub-owner-ready-command-stability-20260621":
            row.pop("summary_zh", None)
            target_found = True
            break
    if not target_found:
        expect(
            False,
            "governance-audit-readability-gate",
            "knowledge-check requires Chinese readability fields for new governance audits",
            {"setup_error": "governance audit fixture not found"},
            repo,
        )
        return
    items_path.write_text("\n".join(json.dumps(row, ensure_ascii=False, separators=(",", ":")) for row in rows) + "\n")
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    errors = parsed.get("errors", [])
    expect(
        result["exit_code"] == 1
        and parsed.get("status") == "needs-fix"
        and any("missing summary_zh for post-2026-06-21 governance audit readability gate" in error for error in errors),
        "governance-audit-readability-gate",
        "knowledge-check requires Chinese readability fields for new governance audits",
        {
            "exit_code": result["exit_code"],
            "status": parsed.get("status"),
            "errors": errors,
            "stdout_sample": result["stdout"][:1200],
        },
        repo,
    )

def test_ai_generated_item_provenance_gate():
    repo = copy_repo("ai-generated-item-provenance-gate")
    items_path = repo / "registry" / "items.jsonl"
    rows = [json.loads(line) for line in items_path.read_text().splitlines() if line.strip()]
    target_found = False
    for row in rows:
        if row.get("id") == "knowledge-hub-owner-ready-command-stability-20260621":
            row.pop("ai_model_or_tool", None)
            row.pop("ai_generated_at", None)
            target_found = True
            break
    if not target_found:
        expect(
            False,
            "ai-generated-item-provenance-gate",
            "knowledge-check requires AI provenance fields for new AI generated items",
            {"setup_error": "ai generated item fixture not found"},
            repo,
        )
        return
    items_path.write_text("\n".join(json.dumps(row, ensure_ascii=False, separators=(",", ":")) for row in rows) + "\n")
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    errors = parsed.get("errors", [])
    expect(
        result["exit_code"] == 1
        and parsed.get("status") == "needs-fix"
        and any("ai-generated item missing provenance fields" in error for error in errors),
        "ai-generated-item-provenance-gate",
        "knowledge-check requires AI provenance fields for new AI generated items",
        {
            "exit_code": result["exit_code"],
            "status": parsed.get("status"),
            "errors": errors,
            "stdout_sample": result["stdout"][:1200],
        },
        repo,
    )

def test_templates_required_sections():
    template_paths = [
        root / "templates" / "item.md",
        root / "templates" / "runbook.md",
        root / "templates" / "decision.md",
    ]
    required_fields = [
        "summary_zh:",
        "review_status:",
        "primary_language:",
        "source_language:",
        "translation_status:",
        "terminology_status:",
        "evidence_strength:",
        "evidence_refs:",
        "promotion_decision:",
        "generated_by_ai:",
        "ai_role:",
        "human_reviewed_by:",
        "human_reviewed_at:",
        "review_basis:",
    ]
    required_sections = [
        "## 适用范围",
        "## 权威来源",
        "## 当前结论",
        "## 风险与限制",
        "## Review",
        "| Command | Exit Code | Result Summary | Evidence Path | Layer | Related Artifact |",
    ]
    missing_by_file = {}
    for path in template_paths:
        try:
            text = path.read_text()
        except Exception as exc:
            missing_by_file[str(path.relative_to(root))] = [f"read_error: {exc}"]
            continue
        missing = [fragment for fragment in required_fields + required_sections if fragment not in text]
        if missing:
            missing_by_file[str(path.relative_to(root))] = missing
    expect(
        not missing_by_file,
        "templates-required-sections",
        "core templates carry canonical readability fields and long-term evidence sections",
        {
            "missing_by_file": missing_by_file,
            "template_count": len(template_paths),
        },
    )

def test_index_readme_maintenance_coverage():
    readme_path = root / "indexes" / "README.md"
    try:
        readme = readme_path.read_text()
        read_error = ""
    except Exception as exc:
        readme = ""
        read_error = str(exc)
    required_fragments = [
        "registry/items.jsonl",
        "registry/sources.json",
        "indexes/by-owner.md",
        "indexes/by-review-date.md",
        "indexes/by-status.md",
        "indexes/by-project.md",
        "indexes/by-source.md",
        "indexes/by-topic.md",
        "indexes/by-decision.md",
        "knowledge-index-plan.sh --section all",
        "knowledge-check.sh --dry-run --json --diagnostics",
        "profile_health",
        "summary_source",
        "evidence_source",
        "manual_validation_pending: true",
        "不得覆盖人工结论",
        "自动改 active",
        "关闭 owner gate",
        "写 memory",
    ]
    missing_fragments = [fragment for fragment in required_fragments if fragment not in readme]
    expect(
        not read_error and not missing_fragments,
        "index-readme-maintenance-coverage",
        "indexes README documents manual maintenance paths and AI safety limits",
        {
            "read_error": read_error,
            "missing_fragments": missing_fragments,
            "has_source_registry": "registry/sources.json" in readme,
            "has_core_indexes": all(fragment in readme for fragment in ["indexes/by-owner.md", "indexes/by-review-date.md", "indexes/by-status.md"]),
            "has_extended_indexes": all(fragment in readme for fragment in ["indexes/by-project.md", "indexes/by-source.md", "indexes/by-topic.md", "indexes/by-decision.md"]),
            "has_ai_limits": all(fragment in readme for fragment in ["不得覆盖人工结论", "自动改 active", "关闭 owner gate", "写 memory"]),
        },
    )

def test_by_topic_first_screen_readability_contract():
    by_topic_path = root / "indexes" / "by-topic.md"
    try:
        by_topic = by_topic_path.read_text()
        read_error = ""
    except Exception as exc:
        by_topic = ""
        read_error = str(exc)
    required_first_screen_topics = [
        "owner gate",
        "PCR02",
        "tools",
        "knowledge",
        "product-test",
        "scratch",
        "diag",
        "ASAN",
        "memory auto-curation",
        "DVR",
        "motor MCU",
        "governance",
        "automation",
        "regression",
        "patent",
        "Codex archive",
    ]
    first_screen_marker = "## 优先恢复主题速查"
    domain_marker = "## 领域入口"
    history_marker = "## 历史治理台账"
    first_screen_index = by_topic.find(first_screen_marker)
    domain_index = by_topic.find(domain_marker)
    history_index = by_topic.find(history_marker)
    first_screen_text = by_topic[first_screen_index:history_index] if first_screen_index >= 0 and history_index >= 0 else ""
    missing_topics = [topic for topic in required_first_screen_topics if topic not in first_screen_text]
    unexpected_history_before_ledger = [
        path for path in re.findall(r"artifacts/manifests/knowledge-hub-[^`]+", first_screen_text)
        if "knowledge-hub-source-coverage-closeout" not in path
        and "knowledge-hub-governance-regression-helper" not in path
    ]
    missing_manifest_paths = []
    for match in re.finditer(r"`([^`]+\.md)`", by_topic):
        candidate = match.group(1)
        if candidate.startswith("artifacts/manifests/") and not (root / candidate).exists():
            missing_manifest_paths.append(candidate)
    expect(
        not read_error
        and first_screen_index >= 0
        and domain_index > first_screen_index
        and history_index > domain_index
        and not missing_topics
        and not unexpected_history_before_ledger
        and not missing_manifest_paths,
        "by-topic-first-screen-readability-contract",
        "by-topic keeps recovery topics before historical governance ledger",
        {
            "read_error": read_error,
            "first_screen_index": first_screen_index,
            "domain_index": domain_index,
            "history_index": history_index,
            "missing_topics": missing_topics,
            "unexpected_history_before_ledger": unexpected_history_before_ledger,
            "missing_manifest_paths": sorted(set(missing_manifest_paths)),
        },
    )

def test_index_plan_extended_sections():
    section_results = {}
    parsed_by_section = {}
    parse_errors = {}
    for section in ["project", "source", "topic", "decision", "manifest", "linking", "review-queue"]:
        result = run_cmd(root, ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", section, "--json"])
        section_results[section] = result
        try:
            parsed_by_section[section] = json.loads(result["stdout"])
        except Exception as exc:
            parsed_by_section[section] = {}
            parse_errors[section] = str(exc)
    manifest_text_result = run_cmd(root, ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "manifest"])

    project_index = parsed_by_section.get("project", {}).get("indexes", {}).get("by_project", {})
    source_index = parsed_by_section.get("source", {}).get("indexes", {}).get("by_source", {})
    source_selection = parsed_by_section.get("source", {}).get("source_coverage_selection", {})
    topic_index = parsed_by_section.get("topic", {}).get("indexes", {}).get("by_topic", {})
    decision_index = parsed_by_section.get("decision", {}).get("indexes", {}).get("by_decision", {})
    manifest_index = parsed_by_section.get("manifest", {}).get("indexes", {}).get("by_manifest", {})
    linking_audit = parsed_by_section.get("linking", {}).get("linking_audit", {})
    review_queue_index = parsed_by_section.get("review-queue", {}).get("indexes", {}).get("by_review_queue", {})
    review_queue_summary = review_queue_index.get("summary", {})
    registry_decisions = decision_index.get("registry_decisions", [])
    owner_worksheets = decision_index.get("owner_worksheets", [])
    source_sample = next(iter(source_index.values()), {})
    source_with_coverage = next(
        (row for row in source_index.values() if row.get("coverage")),
        {},
    )
    source_coverage = source_with_coverage.get("coverage", {})
    source_coverage_decision = source_coverage.get("decision", "")
    source_coverage_risk = source_coverage.get("risk", "")
    manifest_summary = manifest_index.get("summary", {})
    manifest_rows = manifest_index.get("rows", [])
    manifest_unpaired = manifest_index.get("unpaired", [])
    manifest_unpaired_expected = manifest_index.get("unpaired_expected", [])
    manifest_unpaired_needs_review = manifest_index.get("unpaired_needs_review", [])
    latest_manifests = manifest_index.get("latest", [])
    paired_profile_rows = [row for row in manifest_rows if row.get("paired")]
    manifest_profile_health = manifest_summary.get("profile_health", {})
    latest_manifest_ids = [row.get("id") for row in latest_manifests]

    expect(
        not parse_errors
        and all(result["exit_code"] == 0 for result in section_results.values())
        and all(parsed_by_section.get(section, {}).get("status") == "planned" for section in section_results)
        and bool(project_index)
        and bool(source_index)
        and bool(source_sample.get("owner"))
        and bool(source_sample.get("review_after"))
        and bool(source_sample.get("final_disposition"))
        and bool(source_sample.get("check") or source_sample.get("no_check_reason"))
        and source_selection.get("strategy") == "filename-yyyymmdd-sort-last"
        and str(source_selection.get("selected", "")).startswith(
            "artifacts/manifests/knowledge-hub-source-coverage-closeout-"
        )
        and str(source_selection.get("selected", "")).endswith(".jsonl")
        and source_selection.get("candidate_count", 0) >= 1
        and source_selection.get("dated_candidate_count", 0) >= 1
        and bool(source_coverage)
        and bool(source_coverage.get("checked_at"))
        and bool(source_coverage_decision)
        and bool(source_coverage_risk)
        and "project-current" in topic_index
        and any(row.get("decision_id") == "knowledge-hub-root-path" for row in registry_decisions)
        and manifest_summary.get("jsonl_count", 0) >= 188
        and manifest_summary.get("markdown_count", 0) >= 187
        and manifest_summary.get("latest_strategy") == "filename-date-only"
        and "文件名中的 YYYYMMDD" in manifest_summary.get("latest_strategy_zh", "")
        and manifest_profile_health.get("pass", 0) >= 1
        and manifest_profile_health.get("historical-evidence-exempt", 0) >= 1
        and manifest_summary.get("unpaired_count") == len(manifest_unpaired)
        and manifest_summary.get("unpaired_expected_count")
        == len(manifest_unpaired_expected)
        and manifest_summary.get("unpaired_needs_review_count")
        == len(manifest_unpaired_needs_review)
        and all(row.get("review_status") in {"expected", "needs_review"} for row in manifest_unpaired)
        and all(row.get("pairing_status") in {"jsonl-only", "markdown-only"} for row in manifest_unpaired)
        and all(row.get("reasons_zh") and row.get("notes_zh") for row in manifest_unpaired)
        and manifest_text_result["exit_code"] == 0
        and "unpaired_expected_count: {}".format(len(manifest_unpaired_expected))
        in manifest_text_result["stdout"]
        and "unpaired_needs_review_count: {}".format(
            len(manifest_unpaired_needs_review)
        )
        in manifest_text_result["stdout"]
        and "profile_health:" in manifest_text_result["stdout"]
        and "summary_source=`" in manifest_text_result["stdout"]
        and "evidence_source=`evidence_refs`" in manifest_text_result["stdout"]
        and "review_status=`expected`" in manifest_text_result["stdout"]
        and "pairing=`" in manifest_text_result["stdout"]
        and bool(latest_manifests)
        and all(row.get("date_source") in {"filename-YYYYMMDD", "missing-filename-date"} for row in latest_manifests)
        and all("row_date" in row for row in latest_manifests)
        and bool(paired_profile_rows)
        and any(row.get("derived_summary_zh") for row in paired_profile_rows)
        and any(row.get("derived_evidence_count", 0) >= 1 for row in paired_profile_rows)
        and all(
            row.get("summary_source") in {"summary_zh", "notes_zh", "notes", "missing"}
            for row in paired_profile_rows
        )
        and all(
            row.get("profile_health")
            in {
                "pass",
                "advisory-missing-boundary",
                "historical-evidence-exempt",
                "missing-summary",
                "missing-evidence",
                "reference-only",
            }
            for row in paired_profile_rows
        )
        and linking_audit.get("status") == "pass"
        and linking_audit.get("read_only") is True
        and linking_audit.get("source_body_read") is False
        and linking_audit.get("owner_gate_mutation") is False
        and linking_audit.get("cross_session", {}).get("status") == "pass"
        and linking_audit.get("cross_project", {}).get("status") == "pass"
        and linking_audit.get("cross_project", {}).get("registered_source_count")
        == len(source_index)
        and linking_audit.get("markdown_index_recovery", {}).get("status") == "pass"
        and linking_audit.get("markdown_index_recovery", {}).get("missing_anchors") == []
        and review_queue_summary.get("status") in {"needs-human-review", "empty", "clear"}
        and review_queue_summary.get("read_only") is True
        and review_queue_summary.get("report_only") is True
        and review_queue_summary.get("owner_gate_mutation") is False
        and review_queue_summary.get("memory_write") is False
        and review_queue_summary.get("active_or_promotion_blocker_count") == 0
        and all(row.get("queue_type") in {"ai-human-review", "external-source-review"} for row in review_queue_index.get("rows", []))
        and all(row.get("object_status") not in {"active"} for row in review_queue_index.get("rows", []))
        and bool(owner_worksheets)
        and all(
            row.get("worksheet_id")
            and row.get("source_id")
            and row.get("owner")
            and row.get("status")
            and row.get("review_after")
            and row.get("decision_state")
            for row in owner_worksheets
        ),
        "index-plan-extended-sections",
        "index planner covers project/source/topic/decision/manifest sections",
        {
            "exit_codes": {section: result["exit_code"] for section, result in section_results.items()},
            "parse_errors": parse_errors,
            "statuses": {section: parsed_by_section.get(section, {}).get("status") for section in section_results},
            "project_keys_sample": sorted(project_index.keys())[:10],
            "source_count": len(source_index),
            "source_coverage_status": source_coverage.get("status", ""),
            "source_coverage_selection": source_selection,
            "source_coverage_decision": source_coverage_decision,
            "source_coverage_risk": source_coverage_risk,
            "source_sample_id": source_sample.get("id", ""),
            "source_owner": source_sample.get("owner", ""),
            "source_review_after": source_sample.get("review_after", ""),
            "source_final_disposition": source_sample.get("final_disposition", ""),
            "topic_keys_sample": sorted(topic_index.keys())[:10],
            "registry_decision_count": len(registry_decisions),
            "manifest_summary": manifest_summary,
            "manifest_profile_health": manifest_profile_health,
            "manifest_unpaired": manifest_unpaired,
            "manifest_text_stdout_sample": manifest_text_result["stdout"][:1200],
            "latest_manifest_count": len(latest_manifests),
            "latest_manifest_ids": latest_manifest_ids[:20],
            "paired_manifest_profile_count": len(paired_profile_rows),
            "linking_audit": linking_audit,
            "review_queue_summary": review_queue_summary,
            "review_queue_row_count": len(review_queue_index.get("rows", [])),
            "owner_worksheet_count": len(owner_worksheets),
        },
    )

def test_manifest_latest_filename_date_only():
    repo = copy_repo("manifest-latest-filename-date-only")
    manifests_dir = repo / "artifacts" / "manifests"
    old_by_filename = manifests_dir / "fixture-row-date-newer-20200101.jsonl"
    old_by_filename.write_text(
        '{"id":"fixture-row-date-newer","status":"applied","checked_at":"2099-01-01","summary_zh":"row 日期很新但文件名日期很旧，不能抢占 latest。","evidence_refs":["fixture"]}\n'
    )
    new_by_filename = manifests_dir / "fixture-filename-newer-20991231.jsonl"
    new_by_filename.write_text(
        '{"id":"fixture-filename-newer","status":"applied","checked_at":"2020-01-01","summary_zh":"文件名日期更新，应排在旧文件名前。","evidence_refs":["fixture"]}\n'
    )
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "manifest", "--json"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    manifest_index = parsed.get("indexes", {}).get("by_manifest", {}) if isinstance(parsed, dict) else {}
    latest = manifest_index.get("latest", [])
    rows = manifest_index.get("rows", [])
    old_row = next((row for row in rows if row.get("id") == "fixture-row-date-newer"), {})
    new_row = next((row for row in rows if row.get("id") == "fixture-filename-newer"), {})
    expect(
        not parse_error
        and result["exit_code"] == 0
        and latest
        and latest[0].get("id") == "fixture-filename-newer"
        and old_row.get("date") == "2020-01-01"
        and old_row.get("row_date") == "2099-01-01"
        and old_row.get("date_source") == "filename-YYYYMMDD"
        and new_row.get("date") == "2099-12-31"
        and new_row.get("row_date") == "2020-01-01",
        "manifest-latest-filename-date-only",
        "manifest latest view sorts only by filename date, not JSONL row dates",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "latest_first": latest[0] if latest else {},
            "old_row": old_row,
            "new_row": new_row,
        },
        repo,
    )

def test_manifest_jsonl_profile_gate():
    repo = copy_repo("manifest-jsonl-profile-gate")
    manifest_paths = [
        repo / "artifacts" / "manifests" / "knowledge-hub-manifest-profile-index-plan-20260621.jsonl",
        repo / "artifacts" / "manifests" / "knowledge-hub-manual-source-kind-contract-20260622.jsonl",
    ]
    setup_errors = []
    try:
        for manifest_path in manifest_paths:
            rows = []
            for line in manifest_path.read_text().splitlines():
                if not line.strip():
                    continue
                rows.append(json.loads(line))
            rows[0].pop("summary_zh", None)
            rows[0].pop("notes_zh", None)
            rows[0].pop("evidence", None)
            rows[0].pop("evidence_refs", None)
            rows[0].pop("validation_refs", None)
            rows[0].pop("verification_commands", None)
            rows[0].pop("source_refs", None)
            manifest_path.write_text("\n".join(json.dumps(row, ensure_ascii=False) for row in rows) + "\n")
    except Exception as exc:
        setup_errors.append(str(exc))
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    errors = parsed.get("errors", [])
    expect(
        not setup_errors
        and result["exit_code"] != 0
        and any("manifest-profile:knowledge-hub-manifest-profile-index-plan-20260621 missing summary_zh or notes_zh" in error for error in errors)
        and any("manifest-profile:knowledge-hub-manifest-profile-index-plan-20260621 missing evidence field" in error for error in errors)
        and any("manifest-profile:knowledge-hub-manual-source-kind-contract-20260622 missing summary_zh or notes_zh" in error for error in errors)
        and any("manifest-profile:knowledge-hub-manual-source-kind-contract-20260622 missing evidence field" in error for error in errors),
        "manifest-jsonl-profile-gate",
        "knowledge-check requires lightweight profile fields for governance manifest JSONL rows dated 2026-06-21 or later",
        {
            "setup_errors": setup_errors,
            "exit_code": result["exit_code"],
            "errors": errors[:10],
        },
    )

def test_template_readability_field_gate():
    repo = copy_repo("template-readability-field-gate")
    template_path = repo / "templates" / "runbook.md"
    try:
        text = template_path.read_text()
        text = "\n".join(line for line in text.splitlines() if not line.startswith("summary_zh:"))
        template_path.write_text(text + "\n")
        setup_error = ""
    except Exception as exc:
        setup_error = str(exc)
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    errors = parsed.get("errors", [])
    expect(
        not setup_error
        and result["exit_code"] != 0
        and any("template:templates/runbook.md missing readability field summary_zh" in error for error in errors),
        "template-readability-field-gate",
        "knowledge-check requires long-term readability fields in maintained templates",
        {
            "setup_error": setup_error,
            "exit_code": result["exit_code"],
            "errors": errors[:10],
        },
    )

def test_index_plan_topic_schema_health():
    result = run_cmd(root, ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "topic", "--json"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    topics_doc = json.loads((root / "registry" / "topics.json").read_text())
    registry_topic_ids = sorted(topic.get("id", "") for topic in topics_doc.get("topics", []) if topic.get("id"))
    planner_topic_ids = sorted(parsed.get("indexes", {}).get("by_topic", {}).keys())
    expect(
        result["exit_code"] == 0
        and not parse_error
        and parsed.get("status") == "planned"
        and planner_topic_ids == registry_topic_ids,
        "index-plan-topic-schema-health",
        "index planner topic section mirrors registry/topics.json ids",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "registry_topic_ids": registry_topic_ids,
            "planner_topic_ids": planner_topic_ids,
            "stdout_sample": result["stdout"][:1000],
        },
    )

def test_registry_canonical_topic_retention_paths():
    topics_doc = json.loads((root / "registry" / "topics.json").read_text())
    retention_doc = json.loads((root / "registry" / "retention.json").read_text())
    old_prefixes = ("domains/projects", "domains/personal")
    topic_domains = [str(topic.get("domain", "")) for topic in topics_doc.get("topics", [])]
    retention_domains = [str(rule.get("domain", "")) for rule in retention_doc.get("rules", []) if isinstance(rule, dict)]

    repo = copy_repo("registry-canonical-topic-retention-paths")
    mutated_topics = json.loads((repo / "registry" / "topics.json").read_text())
    for topic in mutated_topics.get("topics", []):
        if topic.get("id") == "project-current":
            topic["domain"] = "domains/projects"
        if topic.get("id") == "personal":
            topic["domain"] = "domains/personal"
    (repo / "registry" / "topics.json").write_text(json.dumps(mutated_topics, ensure_ascii=False, indent=2) + "\n")
    mutated_retention = json.loads((repo / "registry" / "retention.json").read_text())
    for rule in mutated_retention.get("rules", []):
        if isinstance(rule, dict) and rule.get("domain") == "notes/personal":
            rule["domain"] = "domains/personal"
    (repo / "registry" / "retention.json").write_text(json.dumps(mutated_retention, ensure_ascii=False, indent=2) + "\n")

    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    errors = parsed.get("errors", []) if isinstance(parsed, dict) else []
    expect(
        not any(domain.startswith(old_prefixes) for domain in topic_domains + retention_domains)
        and result["exit_code"] != 0
        and any(error.startswith("topics:project-current domain uses a noncanonical path") for error in errors)
        and any(error.startswith("topics:personal domain uses a noncanonical path") for error in errors)
        and any(error.startswith("retention:0 domain uses a noncanonical path") for error in errors),
        "registry-canonical-topic-retention-paths",
        "registry topics and retention rules use final canonical paths and reject noncanonical project/personal roots",
        {
            "topic_domains": topic_domains,
            "retention_domains": retention_domains,
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "errors": errors[:10],
        },
        repo,
    )

def test_index_plan_decision_registry_health():
    result = run_cmd(root, ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "decision", "--json"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    registry_decision_ids = []
    for line in (root / "registry" / "decisions.jsonl").read_text().splitlines():
        if not line.strip():
            continue
        registry_decision_ids.append(json.loads(line).get("decision_id", ""))
    planner_decision_ids = [
        decision.get("decision_id", "")
        for decision in parsed.get("indexes", {}).get("by_decision", {}).get("registry_decisions", [])
    ]
    expect(
        result["exit_code"] == 0
        and not parse_error
        and parsed.get("status") == "planned"
        and sorted(planner_decision_ids) == sorted(registry_decision_ids)
        and len(planner_decision_ids) == len(set(planner_decision_ids)),
        "index-plan-decision-registry-health",
        "index planner decision section covers registry decisions exactly once",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "registry_decision_ids": sorted(registry_decision_ids),
            "planner_decision_ids": sorted(planner_decision_ids),
            "stdout_sample": result["stdout"][:1000],
        },
    )

def test_index_decision_registry_gate():
    repo = copy_repo("index-decision-registry-gate")
    index_path = repo / "indexes" / "by-decision.md"
    text = index_path.read_text()
    index_path.write_text(text.replace("`automation-report-only-default`", "`automation-report-only-default-stale`", 1))
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    expect(
        result["exit_code"] != 0
        and "index:indexes/by-decision.md missing registry decision automation-report-only-default" in result["stdout"],
        "index-decision-registry-subsection-gate",
        "by-decision hard gate protects registry decisions without locking owner worksheet rows",
        {
            "exit_code": result["exit_code"],
            "stdout_sample": result["stdout"][:1200],
            "stderr_sample": result["stderr"][:500],
        },
        repo,
    )

def test_index_topic_zero_bucket_allowed():
    result = run_cmd(root, ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "topic", "--json"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    by_topic = parsed.get("indexes", {}).get("by_topic", {}) if isinstance(parsed, dict) else {}
    empty_topics = sorted(topic_id for topic_id, detail in by_topic.items() if not detail.get("items"))
    expect(
        result["exit_code"] == 0
        and not parse_error
        and parsed.get("status") == "planned"
        and set(empty_topics) <= set(by_topic.keys()),
        "index-topic-zero-bucket-allowed",
        "topic planner treats empty topics as health data instead of hard failure",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "empty_topics": empty_topics,
            "topic_count": len(by_topic),
        },
    )

def test_source_check_health_contract():
    result = run_cmd(root, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    source_check_health = parsed.get("source_check_health", {}) if isinstance(parsed, dict) else {}

    repo = copy_repo("source-check-health-non-rtk")
    retired_sources_path = repo / "registry" / "retired-sources.jsonl"
    retired_sources = [
        json.loads(line)
        for line in retired_sources_path.read_text().splitlines()
        if line.strip()
    ]
    for source in retired_sources:
        if source.get("id") == "pcr02-project-tools":
            source["check"] = str(source.get("check", "")).replace("rtk ", "bash ", 1)
            break
    retired_sources_path.write_text(
        "\n".join(json.dumps(row, ensure_ascii=False, separators=(",", ":")) for row in retired_sources) + "\n"
    )
    bad_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    bad_parsed = {}
    bad_parse_error = ""
    try:
        bad_parsed = json.loads(bad_result["stdout"])
    except Exception as exc:
        bad_parse_error = str(exc)
    bad_source_check_health = bad_parsed.get("source_check_health", {}) if isinstance(bad_parsed, dict) else {}
    expect(
        result["exit_code"] == 0
        and not parse_error
        and source_check_health.get("mode") == "static-registry-only"
        and source_check_health.get("executed") is False
        and source_check_health.get("registered_source_count") == 18
        and source_check_health.get("with_check_count") == 18
        and source_check_health.get("with_no_check_reason_count") == 0
        and source_check_health.get("missing_check_or_reason_ids") == []
        and source_check_health.get("non_rtk_check_ids") == []
        and source_check_health.get("missing_source_path_ids") == []
        and len(source_check_health.get("rows", [])) == 18
        and all(row.get("execution_status") == "not-run" for row in source_check_health.get("rows", []))
        and bad_result["exit_code"] != 0
        and not bad_parse_error
        and "pcr02-project-tools" in bad_source_check_health.get("non_rtk_check_ids", [])
        and any("check must start with rtk" in str(error) for error in bad_parsed.get("errors", [])),
        "source-check-health-contract",
        "source check health statically validates check/no-check contracts without executing commands",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "source_check_health": source_check_health,
            "bad_exit_code": bad_result["exit_code"],
            "bad_parse_error": bad_parse_error,
            "bad_source_check_health": bad_source_check_health,
            "bad_errors": bad_parsed.get("errors", [])[:5],
        },
    )

def test_source_check_report_only_helper():
    result = run_cmd(root, ["rtk", "bash", "tools/knowledge-source-check.sh", "--scope", "all", "--json", "--as-of", today.isoformat()])
    check_result = run_cmd(root, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    parsed = {}
    check_parsed = {}
    parse_error = ""
    check_parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    try:
        check_parsed = json.loads(check_result["stdout"])
    except Exception as exc:
        check_parse_error = str(exc)
    source_check_health = check_parsed.get("source_check_health", {}) if isinstance(check_parsed, dict) else {}
    rows = parsed.get("rows", []) if isinstance(parsed.get("rows"), list) else []
    expect(
        result["exit_code"] == 0
        and not parse_error
        and parsed.get("status") == "pass"
        and parsed.get("read_only") is True
        and parsed.get("report_only") is True
        and parsed.get("scope") == "all"
        and parsed.get("source_check_health_contract") == "runtime-all-registered-sources-v1"
        and parsed.get("source_check_health_executed") is True
        and parsed.get("execution_mode") == "direct-filesystem-stat-no-shell"
        and parsed.get("source_body_read") is False
        and parsed.get("owner_gate_mutation") is False
        and parsed.get("memory_write") is False
        and parsed.get("registry_source_count") == 18
        and parsed.get("row_count") == 18
        and parsed.get("executed_count") == 18
        and parsed.get("passed_count") == 18
        and parsed.get("failed_count") == 0
        and parsed.get("unsupported_count") == 0
        and parsed.get("rejected_count") == 0
        and all(row.get("executed") is True and row.get("exit_code") == 0 for row in rows)
        and check_result["exit_code"] == 0
        and not check_parse_error
        and source_check_health.get("mode") == "static-registry-only"
        and source_check_health.get("executed") is False,
        "source-check-report-only-helper",
        "source check helper executes every registry-driven availability check without a shell",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "status": parsed.get("status"),
            "row_count": parsed.get("row_count"),
            "executed_count": parsed.get("executed_count"),
            "passed_count": parsed.get("passed_count"),
            "failed_count": parsed.get("failed_count"),
            "not_applicable_count": parsed.get("not_applicable_count"),
            "rejected_count": parsed.get("rejected_count"),
            "check_exit_code": check_result["exit_code"],
            "check_parse_error": check_parse_error,
            "source_check_health": source_check_health,
        },
    )

def test_source_check_rejects_unsafe_runtime_command():
    repo = copy_repo("source-check-rejects-unsafe-runtime-command")
    if not update_source_registry_entry(repo, "pcr02-project-tools", {"check": "rtk bash -lc 'test -d /tmp && echo unsafe'"}):
        expect(False, "source-check-rejects-unsafe-runtime-command", "source check helper rejects shell control payloads", {"setup_error": "pcr02-project-tools source not found"}, repo)
        return
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-source-check.sh", "--scope", "all", "--source-id", "pcr02-project-tools", "--json", "--as-of", today.isoformat()])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    first = parsed.get("rows", [{}])[0] if parsed.get("rows") else {}
    expect(
        result["exit_code"] == 1
        and not parse_error
        and parsed.get("status") == "fail"
        and parsed.get("row_count") == 1
        and parsed.get("executed_count") == 0
        and first.get("result") in {"unsupported-runtime-check", "rejected-runtime-check"}
        and first.get("executed") is False,
        "source-check-rejects-unsafe-runtime-command",
        "source check helper rejects shell control payloads",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "status": parsed.get("status"),
            "first_row": first,
            "stderr_sample": result["stderr"][:500],
        },
        repo,
    )

def test_source_coverage_date_filename_selection():
    repo = copy_repo("source-coverage-date-filename-selection")
    bad_candidate = repo / "artifacts" / "manifests" / "knowledge-hub-source-coverage-closeout-latest.jsonl"
    bad_candidate.write_text(
        '{"id":"fixture-bad-latest","source_id":"fixture-stale","status":"bad","classification":"bad","decision":"bad","risk":"bad","owner":"bad","checked_at":"2026-06-21"}\n'
    )
    setup_error = init_temp_git_repo(repo)
    check_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    status_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--json"])
    index_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "source", "--json"])
    final_result = run_cmd(
        repo,
        ["rtk", "bash", "tools/knowledge-final-gate.sh", "--json"],
    )
    parse_errors = []
    parsed = {}
    status_parsed = {}
    index_parsed = {}
    final_parsed = {}
    for label, result, target in [
        ("check", check_result, "parsed"),
        ("status", status_result, "status_parsed"),
        ("index", index_result, "index_parsed"),
        ("final", final_result, "final_parsed"),
    ]:
        try:
            value = json.loads(result["stdout"])
        except Exception as exc:
            parse_errors.append(f"{label}: {exc}")
            value = {}
        if target == "parsed":
            parsed = value
        elif target == "status_parsed":
            status_parsed = value
        elif target == "index_parsed":
            index_parsed = value
        else:
            final_parsed = value
    expected_selected = "artifacts/manifests/knowledge-hub-source-coverage-closeout-20260624.jsonl"
    expected_ignored = "artifacts/manifests/knowledge-hub-source-coverage-closeout-latest.jsonl"
    check_selection = parsed.get("source_coverage_selection", {}) if isinstance(parsed, dict) else {}
    status_selection = (
        status_parsed.get("sources", {}).get("latest_coverage_selection", {})
        if isinstance(status_parsed.get("sources", {}), dict)
        else {}
    )
    index_selection = index_parsed.get("source_coverage_selection", {}) if isinstance(index_parsed, dict) else {}
    final_selection = (
        final_parsed.get("final_state_audit", {}).get("level3_registered_sources", {}).get("source_coverage_selection", {})
        if isinstance(final_parsed.get("final_state_audit", {}), dict)
        else {}
    )
    expect(
        not setup_error
        and check_result["exit_code"] == 0
        and status_result["exit_code"] == 0
        and index_result["exit_code"] == 0
        and final_result["exit_code"] in {0, 1}
        and not parse_errors
        and check_selection.get("selected") == expected_selected
        and status_selection.get("selected") == expected_selected
        and index_selection.get("selected") == expected_selected
        and final_selection.get("selected") == expected_selected
        and expected_ignored in check_selection.get("ignored_non_date_candidates", [])
        and expected_ignored in status_selection.get("ignored_non_date_candidates", [])
        and expected_ignored in index_selection.get("ignored_non_date_candidates", [])
        and expected_ignored in final_selection.get("ignored_non_date_candidates", [])
        and any(expected_ignored in warning for warning in parsed.get("warnings", [])),
        "source-coverage-date-filename-selection",
        "source coverage latest selection ignores non-YYYYMMDD closeout candidates",
        {
            "check_exit_code": check_result["exit_code"],
            "setup_error": setup_error,
            "status_exit_code": status_result["exit_code"],
            "index_exit_code": index_result["exit_code"],
            "final_exit_code": final_result["exit_code"],
            "parse_errors": parse_errors,
            "check_selection": check_selection,
            "status_selection": status_selection,
            "index_selection": index_selection,
            "final_selection": final_selection,
            "check_warnings": parsed.get("warnings", []),
        },
        repo,
    )

def test_source_coverage_duplicate_source_id_warning():
    repo = copy_repo("source-coverage-duplicate-source-id-warning")
    coverage_path = repo / "artifacts" / "manifests" / "knowledge-hub-source-coverage-closeout-20260624.jsonl"
    rows = [line for line in coverage_path.read_text().splitlines() if line.strip()]
    first = json.loads(rows[0])
    duplicate = dict(first)
    duplicate["id"] = "SCC-20260624-duplicate-fixture"
    duplicate["status"] = "fixture-duplicate-should-not-overwrite"
    duplicate["decision"] = "duplicate fixture should be warned and ignored for recovery view"
    coverage_path.write_text("\n".join(rows + [json.dumps(duplicate, ensure_ascii=False, separators=(",", ":"))]) + "\n")
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "source", "--json"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    selection = parsed.get("source_coverage_selection", {}) if isinstance(parsed, dict) else {}
    source_id = first.get("source_id", "")
    source_view = parsed.get("indexes", {}).get("by_source", {}).get(source_id, {}) if isinstance(parsed, dict) else {}
    coverage = source_view.get("coverage", {}) if isinstance(source_view, dict) else {}
    warnings_text = "\n".join(parsed.get("warnings", [])) if isinstance(parsed, dict) else ""
    expect(
        not parse_error
        and result["exit_code"] == 0
        and source_id in selection.get("duplicate_source_ids", [])
        and selection.get("duplicate_policy") == "first-row-kept-duplicates-warned"
        and source_id in selection.get("duplicate_rows", {})
        and "duplicate source_id rows" in warnings_text
        and coverage.get("status") == first.get("status")
        and coverage.get("status") != "fixture-duplicate-should-not-overwrite",
        "source-coverage-duplicate-source-id-warning",
        "index plan warns on duplicate source coverage rows and keeps first recovery row",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "source_id": source_id,
            "selection": selection,
            "coverage": coverage,
            "warnings": parsed.get("warnings", []) if isinstance(parsed, dict) else [],
        },
        repo,
    )
