"""Generated regression cases: model index."""

# Generated by regression_codegen.py; edit assertions here, then keep the generator deterministic.
from .support import *  # noqa: F401,F403

def test_manifest_latest_filename_date_only():
    repo = copy_repo("manifest-latest-filename-date-only")
    manifests_dir = repo / "artifacts" / "manifests"
    old_by_filename = manifests_dir / "fixture-row-date-newer-20200101.jsonl"
    old_by_filename.write_text(
        '{"id":"fixture-row-date-newer","status":"applied","checked_at":"2099-01-01","summary_zh":"row 日期很新但文件名日期很旧，不能抢占 latest。","evidence_refs":["fixture"]}\n'
    )
    new_by_filename = manifests_dir / "fixture-filename-newer-20991231.jsonl"
    new_by_filename.write_text(
        '{"id":"fixture-filename-newer","status":"applied","checked_at":"2020-01-01","summary_zh":"文件名日期更新，应排在旧文件名前。","evidence_refs":["fixture"]}\n'
    )
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "manifest", "--json"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    manifest_index = parsed.get("indexes", {}).get("by_manifest", {}) if isinstance(parsed, dict) else {}
    latest = manifest_index.get("latest", [])
    rows = manifest_index.get("rows", [])
    old_row = next((row for row in rows if row.get("id") == "fixture-row-date-newer"), {})
    new_row = next((row for row in rows if row.get("id") == "fixture-filename-newer"), {})
    expect(
        not parse_error
        and result["exit_code"] == 0
        and latest
        and latest[0].get("id") == "fixture-filename-newer"
        and old_row.get("date") == "2020-01-01"
        and old_row.get("row_date") == "2099-01-01"
        and old_row.get("date_source") == "filename-YYYYMMDD"
        and new_row.get("date") == "2099-12-31"
        and new_row.get("row_date") == "2020-01-01",
        "manifest-latest-filename-date-only",
        "manifest latest view sorts only by filename date, not JSONL row dates",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "latest_first": latest[0] if latest else {},
            "old_row": old_row,
            "new_row": new_row,
        },
        repo,
    )

def test_manifest_jsonl_profile_gate():
    repo = copy_repo("manifest-jsonl-profile-gate")
    manifest_paths = [
        repo / "artifacts" / "manifests" / "knowledge-hub-manifest-profile-index-plan-20260621.jsonl",
        repo / "artifacts" / "manifests" / "knowledge-hub-manual-source-kind-contract-20260622.jsonl",
    ]
    setup_errors = []
    try:
        for manifest_path in manifest_paths:
            rows = []
            for line in manifest_path.read_text().splitlines():
                if not line.strip():
                    continue
                rows.append(json.loads(line))
            rows[0].pop("summary_zh", None)
            rows[0].pop("notes_zh", None)
            rows[0].pop("evidence", None)
            rows[0].pop("evidence_refs", None)
            rows[0].pop("validation_refs", None)
            rows[0].pop("verification_commands", None)
            rows[0].pop("source_refs", None)
            manifest_path.write_text("\n".join(json.dumps(row, ensure_ascii=False) for row in rows) + "\n")
    except Exception as exc:
        setup_errors.append(str(exc))
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    errors = parsed.get("errors", [])
    expect(
        not setup_errors
        and result["exit_code"] != 0
        and any("manifest-profile:knowledge-hub-manifest-profile-index-plan-20260621 missing summary_zh or notes_zh" in error for error in errors)
        and any("manifest-profile:knowledge-hub-manifest-profile-index-plan-20260621 missing evidence field" in error for error in errors)
        and any("manifest-profile:knowledge-hub-manual-source-kind-contract-20260622 missing summary_zh or notes_zh" in error for error in errors)
        and any("manifest-profile:knowledge-hub-manual-source-kind-contract-20260622 missing evidence field" in error for error in errors),
        "manifest-jsonl-profile-gate",
        "knowledge-check requires lightweight profile fields for governance manifest JSONL rows dated 2026-06-21 or later",
        {
            "setup_errors": setup_errors,
            "exit_code": result["exit_code"],
            "errors": errors[:10],
        },
    )

def test_template_readability_field_gate():
    repo = copy_repo("template-readability-field-gate")
    template_path = repo / "templates" / "runbook.md"
    try:
        text = template_path.read_text()
        text = "\n".join(line for line in text.splitlines() if not line.startswith("summary_zh:"))
        template_path.write_text(text + "\n")
        setup_error = ""
    except Exception as exc:
        setup_error = str(exc)
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    errors = parsed.get("errors", [])
    expect(
        not setup_error
        and result["exit_code"] != 0
        and any("template:templates/runbook.md missing readability field summary_zh" in error for error in errors),
        "template-readability-field-gate",
        "knowledge-check requires long-term readability fields in maintained templates",
        {
            "setup_error": setup_error,
            "exit_code": result["exit_code"],
            "errors": errors[:10],
        },
    )

def test_index_plan_topic_schema_health():
    result = run_cmd(root, ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "topic", "--json"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    topics_doc = json.loads((root / "registry" / "topics.json").read_text())
    registry_topic_ids = sorted(topic.get("id", "") for topic in topics_doc.get("topics", []) if topic.get("id"))
    planner_topic_ids = sorted(parsed.get("indexes", {}).get("by_topic", {}).keys())
    expect(
        result["exit_code"] == 0
        and not parse_error
        and parsed.get("status") == "planned"
        and planner_topic_ids == registry_topic_ids,
        "index-plan-topic-schema-health",
        "index planner topic section mirrors registry/topics.json ids",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "registry_topic_ids": registry_topic_ids,
            "planner_topic_ids": planner_topic_ids,
            "stdout_sample": result["stdout"][:1000],
        },
    )

def test_registry_canonical_topic_retention_paths():
    topics_doc = json.loads((root / "registry" / "topics.json").read_text())
    retention_doc = json.loads((root / "registry" / "retention.json").read_text())
    old_prefixes = ("domains/projects", "domains/personal")
    topic_domains = [str(topic.get("domain", "")) for topic in topics_doc.get("topics", [])]
    retention_domains = [str(rule.get("domain", "")) for rule in retention_doc.get("rules", []) if isinstance(rule, dict)]

    repo = copy_repo("registry-canonical-topic-retention-paths")
    mutated_topics = json.loads((repo / "registry" / "topics.json").read_text())
    for topic in mutated_topics.get("topics", []):
        if topic.get("id") == "project-current":
            topic["domain"] = "domains/projects"
        if topic.get("id") == "personal":
            topic["domain"] = "domains/personal"
    (repo / "registry" / "topics.json").write_text(json.dumps(mutated_topics, ensure_ascii=False, indent=2) + "\n")
    mutated_retention = json.loads((repo / "registry" / "retention.json").read_text())
    for rule in mutated_retention.get("rules", []):
        if isinstance(rule, dict) and rule.get("domain") == "notes/personal":
            rule["domain"] = "domains/personal"
    (repo / "registry" / "retention.json").write_text(json.dumps(mutated_retention, ensure_ascii=False, indent=2) + "\n")

    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    errors = parsed.get("errors", []) if isinstance(parsed, dict) else []
    expect(
        not any(domain.startswith(old_prefixes) for domain in topic_domains + retention_domains)
        and result["exit_code"] != 0
        and any(error.startswith("topics:project-current domain uses a noncanonical path") for error in errors)
        and any(error.startswith("topics:personal domain uses a noncanonical path") for error in errors)
        and any(error.startswith("retention:0 domain uses a noncanonical path") for error in errors),
        "registry-canonical-topic-retention-paths",
        "registry topics and retention rules use final canonical paths and reject noncanonical project/personal roots",
        {
            "topic_domains": topic_domains,
            "retention_domains": retention_domains,
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "errors": errors[:10],
        },
        repo,
    )

def test_index_plan_decision_registry_health():
    result = run_cmd(root, ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "decision", "--json"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    registry_decision_ids = []
    for line in (root / "registry" / "decisions.jsonl").read_text().splitlines():
        if not line.strip():
            continue
        registry_decision_ids.append(json.loads(line).get("decision_id", ""))
    planner_decision_ids = [
        decision.get("decision_id", "")
        for decision in parsed.get("indexes", {}).get("by_decision", {}).get("registry_decisions", [])
    ]
    expect(
        result["exit_code"] == 0
        and not parse_error
        and parsed.get("status") == "planned"
        and sorted(planner_decision_ids) == sorted(registry_decision_ids)
        and len(planner_decision_ids) == len(set(planner_decision_ids)),
        "index-plan-decision-registry-health",
        "index planner decision section covers registry decisions exactly once",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "registry_decision_ids": sorted(registry_decision_ids),
            "planner_decision_ids": sorted(planner_decision_ids),
            "stdout_sample": result["stdout"][:1000],
        },
    )

def test_index_decision_registry_gate():
    repo = copy_repo("index-decision-registry-gate")
    index_path = repo / "indexes" / "by-decision.md"
    text = index_path.read_text()
    index_path.write_text(text.replace("`automation-report-only-default`", "`automation-report-only-default-stale`", 1))
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    expect(
        result["exit_code"] != 0
        and "index:indexes/by-decision.md missing registry decision automation-report-only-default" in result["stdout"],
        "index-decision-registry-subsection-gate",
        "by-decision hard gate protects registry decisions without locking owner worksheet rows",
        {
            "exit_code": result["exit_code"],
            "stdout_sample": result["stdout"][:1200],
            "stderr_sample": result["stderr"][:500],
        },
        repo,
    )

def test_index_topic_zero_bucket_allowed():
    result = run_cmd(root, ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "topic", "--json"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    by_topic = parsed.get("indexes", {}).get("by_topic", {}) if isinstance(parsed, dict) else {}
    empty_topics = sorted(topic_id for topic_id, detail in by_topic.items() if not detail.get("items"))
    expect(
        result["exit_code"] == 0
        and not parse_error
        and parsed.get("status") == "planned"
        and set(empty_topics) <= set(by_topic.keys()),
        "index-topic-zero-bucket-allowed",
        "topic planner treats empty topics as health data instead of hard failure",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "empty_topics": empty_topics,
            "topic_count": len(by_topic),
        },
    )

def test_source_check_health_contract():
    result = run_cmd(root, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    source_check_health = parsed.get("source_check_health", {}) if isinstance(parsed, dict) else {}

    repo = copy_repo("source-check-health-non-rtk")
    retired_sources_path = repo / "registry" / "retired-sources.jsonl"
    retired_sources = [
        json.loads(line)
        for line in retired_sources_path.read_text().splitlines()
        if line.strip()
    ]
    for source in retired_sources:
        if source.get("id") == "pcr02-project-tools":
            source["check"] = str(source.get("check", "")).replace("rtk ", "bash ", 1)
            break
    retired_sources_path.write_text(
        "\n".join(json.dumps(row, ensure_ascii=False, separators=(",", ":")) for row in retired_sources) + "\n"
    )
    bad_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    bad_parsed = {}
    bad_parse_error = ""
    try:
        bad_parsed = json.loads(bad_result["stdout"])
    except Exception as exc:
        bad_parse_error = str(exc)
    bad_source_check_health = bad_parsed.get("source_check_health", {}) if isinstance(bad_parsed, dict) else {}
    expect(
        result["exit_code"] == 0
        and not parse_error
        and source_check_health.get("mode") == "static-registry-only"
        and source_check_health.get("executed") is False
        and source_check_health.get("registered_source_count") == 18
        and source_check_health.get("with_check_count") == 18
        and source_check_health.get("with_no_check_reason_count") == 0
        and source_check_health.get("missing_check_or_reason_ids") == []
        and source_check_health.get("non_rtk_check_ids") == []
        and source_check_health.get("missing_source_path_ids") == []
        and len(source_check_health.get("rows", [])) == 18
        and all(row.get("execution_status") == "not-run" for row in source_check_health.get("rows", []))
        and bad_result["exit_code"] != 0
        and not bad_parse_error
        and "pcr02-project-tools" in bad_source_check_health.get("non_rtk_check_ids", [])
        and any("check must start with rtk" in str(error) for error in bad_parsed.get("errors", [])),
        "source-check-health-contract",
        "source check health statically validates check/no-check contracts without executing commands",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "source_check_health": source_check_health,
            "bad_exit_code": bad_result["exit_code"],
            "bad_parse_error": bad_parse_error,
            "bad_source_check_health": bad_source_check_health,
            "bad_errors": bad_parsed.get("errors", [])[:5],
        },
    )

def test_source_check_report_only_helper():
    result = run_cmd(root, ["rtk", "bash", "tools/knowledge-source-check.sh", "--scope", "all", "--json", "--as-of", today.isoformat()])
    check_result = run_cmd(root, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    parsed = {}
    check_parsed = {}
    parse_error = ""
    check_parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    try:
        check_parsed = json.loads(check_result["stdout"])
    except Exception as exc:
        check_parse_error = str(exc)
    source_check_health = check_parsed.get("source_check_health", {}) if isinstance(check_parsed, dict) else {}
    rows = parsed.get("rows", []) if isinstance(parsed.get("rows"), list) else []
    expect(
        result["exit_code"] == 0
        and not parse_error
        and parsed.get("status") == "pass"
        and parsed.get("read_only") is True
        and parsed.get("report_only") is True
        and parsed.get("scope") == "all"
        and parsed.get("source_check_health_contract") == "runtime-all-registered-sources-v1"
        and parsed.get("source_check_health_executed") is True
        and parsed.get("execution_mode") == "direct-filesystem-stat-no-shell"
        and parsed.get("source_body_read") is False
        and parsed.get("owner_gate_mutation") is False
        and parsed.get("memory_write") is False
        and parsed.get("registry_source_count") == 18
        and parsed.get("row_count") == 18
        and parsed.get("executed_count") == 18
        and parsed.get("passed_count") == 18
        and parsed.get("failed_count") == 0
        and parsed.get("unsupported_count") == 0
        and parsed.get("rejected_count") == 0
        and all(row.get("executed") is True and row.get("exit_code") == 0 for row in rows)
        and check_result["exit_code"] == 0
        and not check_parse_error
        and source_check_health.get("mode") == "static-registry-only"
        and source_check_health.get("executed") is False,
        "source-check-report-only-helper",
        "source check helper executes every registry-driven availability check without a shell",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "status": parsed.get("status"),
            "row_count": parsed.get("row_count"),
            "executed_count": parsed.get("executed_count"),
            "passed_count": parsed.get("passed_count"),
            "failed_count": parsed.get("failed_count"),
            "not_applicable_count": parsed.get("not_applicable_count"),
            "rejected_count": parsed.get("rejected_count"),
            "check_exit_code": check_result["exit_code"],
            "check_parse_error": check_parse_error,
            "source_check_health": source_check_health,
        },
    )

def test_source_check_rejects_unsafe_runtime_command():
    repo = copy_repo("source-check-rejects-unsafe-runtime-command")
    if not update_source_registry_entry(repo, "pcr02-project-tools", {"check": "rtk bash -lc 'test -d /tmp && echo unsafe'"}):
        expect(False, "source-check-rejects-unsafe-runtime-command", "source check helper rejects shell control payloads", {"setup_error": "pcr02-project-tools source not found"}, repo)
        return
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-source-check.sh", "--scope", "all", "--source-id", "pcr02-project-tools", "--json", "--as-of", today.isoformat()])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    first = parsed.get("rows", [{}])[0] if parsed.get("rows") else {}
    expect(
        result["exit_code"] == 1
        and not parse_error
        and parsed.get("status") == "fail"
        and parsed.get("row_count") == 1
        and parsed.get("executed_count") == 0
        and first.get("result") in {"unsupported-runtime-check", "rejected-runtime-check"}
        and first.get("executed") is False,
        "source-check-rejects-unsafe-runtime-command",
        "source check helper rejects shell control payloads",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "status": parsed.get("status"),
            "first_row": first,
            "stderr_sample": result["stderr"][:500],
        },
        repo,
    )

def test_source_coverage_date_filename_selection():
    repo = copy_repo("source-coverage-date-filename-selection")
    bad_candidate = repo / "artifacts" / "manifests" / "knowledge-hub-source-coverage-closeout-latest.jsonl"
    bad_candidate.write_text(
        '{"id":"fixture-bad-latest","source_id":"fixture-stale","status":"bad","classification":"bad","decision":"bad","risk":"bad","owner":"bad","checked_at":"2026-06-21"}\n'
    )
    setup_error = init_temp_git_repo(repo)
    check_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    status_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--json"])
    index_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "source", "--json"])
    final_result = run_cmd(
        repo,
        ["rtk", "bash", "tools/knowledge-final-gate.sh", "--json"],
    )
    parse_errors = []
    parsed = {}
    status_parsed = {}
    index_parsed = {}
    final_parsed = {}
    for label, result, target in [
        ("check", check_result, "parsed"),
        ("status", status_result, "status_parsed"),
        ("index", index_result, "index_parsed"),
        ("final", final_result, "final_parsed"),
    ]:
        try:
            value = json.loads(result["stdout"])
        except Exception as exc:
            parse_errors.append(f"{label}: {exc}")
            value = {}
        if target == "parsed":
            parsed = value
        elif target == "status_parsed":
            status_parsed = value
        elif target == "index_parsed":
            index_parsed = value
        else:
            final_parsed = value
    expected_selected = "artifacts/manifests/knowledge-hub-source-coverage-closeout-20260624.jsonl"
    expected_ignored = "artifacts/manifests/knowledge-hub-source-coverage-closeout-latest.jsonl"
    check_selection = parsed.get("source_coverage_selection", {}) if isinstance(parsed, dict) else {}
    status_selection = (
        status_parsed.get("sources", {}).get("latest_coverage_selection", {})
        if isinstance(status_parsed.get("sources", {}), dict)
        else {}
    )
    index_selection = index_parsed.get("source_coverage_selection", {}) if isinstance(index_parsed, dict) else {}
    final_selection = (
        final_parsed.get("final_state_audit", {}).get("level3_registered_sources", {}).get("source_coverage_selection", {})
        if isinstance(final_parsed.get("final_state_audit", {}), dict)
        else {}
    )
    expect(
        not setup_error
        and check_result["exit_code"] == 0
        and status_result["exit_code"] == 0
        and index_result["exit_code"] == 0
        and final_result["exit_code"] in {0, 1}
        and not parse_errors
        and check_selection.get("selected") == expected_selected
        and status_selection.get("selected") == expected_selected
        and index_selection.get("selected") == expected_selected
        and final_selection.get("selected") == expected_selected
        and expected_ignored in check_selection.get("ignored_non_date_candidates", [])
        and expected_ignored in status_selection.get("ignored_non_date_candidates", [])
        and expected_ignored in index_selection.get("ignored_non_date_candidates", [])
        and expected_ignored in final_selection.get("ignored_non_date_candidates", [])
        and any(expected_ignored in warning for warning in parsed.get("warnings", [])),
        "source-coverage-date-filename-selection",
        "source coverage latest selection ignores non-YYYYMMDD closeout candidates",
        {
            "check_exit_code": check_result["exit_code"],
            "setup_error": setup_error,
            "status_exit_code": status_result["exit_code"],
            "index_exit_code": index_result["exit_code"],
            "final_exit_code": final_result["exit_code"],
            "parse_errors": parse_errors,
            "check_selection": check_selection,
            "status_selection": status_selection,
            "index_selection": index_selection,
            "final_selection": final_selection,
            "check_warnings": parsed.get("warnings", []),
        },
        repo,
    )

def test_source_coverage_duplicate_source_id_warning():
    repo = copy_repo("source-coverage-duplicate-source-id-warning")
    coverage_path = repo / "artifacts" / "manifests" / "knowledge-hub-source-coverage-closeout-20260624.jsonl"
    rows = [line for line in coverage_path.read_text().splitlines() if line.strip()]
    first = json.loads(rows[0])
    duplicate = dict(first)
    duplicate["id"] = "SCC-20260624-duplicate-fixture"
    duplicate["status"] = "fixture-duplicate-should-not-overwrite"
    duplicate["decision"] = "duplicate fixture should be warned and ignored for recovery view"
    coverage_path.write_text("\n".join(rows + [json.dumps(duplicate, ensure_ascii=False, separators=(",", ":"))]) + "\n")
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-index-plan.sh", "--section", "source", "--json"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    selection = parsed.get("source_coverage_selection", {}) if isinstance(parsed, dict) else {}
    source_id = first.get("source_id", "")
    source_view = parsed.get("indexes", {}).get("by_source", {}).get(source_id, {}) if isinstance(parsed, dict) else {}
    coverage = source_view.get("coverage", {}) if isinstance(source_view, dict) else {}
    warnings_text = "\n".join(parsed.get("warnings", [])) if isinstance(parsed, dict) else ""
    expect(
        not parse_error
        and result["exit_code"] == 0
        and source_id in selection.get("duplicate_source_ids", [])
        and selection.get("duplicate_policy") == "first-row-kept-duplicates-warned"
        and source_id in selection.get("duplicate_rows", {})
        and "duplicate source_id rows" in warnings_text
        and coverage.get("status") == first.get("status")
        and coverage.get("status") != "fixture-duplicate-should-not-overwrite",
        "source-coverage-duplicate-source-id-warning",
        "index plan warns on duplicate source coverage rows and keeps first recovery row",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "source_id": source_id,
            "selection": selection,
            "coverage": coverage,
            "warnings": parsed.get("warnings", []) if isinstance(parsed, dict) else [],
        },
        repo,
    )
