"""Generated regression cases: project routing."""

# Generated by regression_codegen.py; edit assertions here, then keep the generator deterministic.
from .support import *  # noqa: F401,F403

def test_pcr02_level2_source_coverage():
    expected = {
        "pcr02-project-tools",
        "pcr02-project-knowledge",
        "pcr02-product-test",
        "pcr02-project-scratch",
        "pcr02-project-root-artifacts",
        "pcr02-module-agent-rules",
        "pcr02-project-agent-config",
    }
    sources_path = root / "registry" / "sources.json"
    retired_sources_path = root / "registry" / "retired-sources.jsonl"
    by_source_path = root / "indexes" / "by-source.md"
    coverage_paths = sorted((root / "artifacts" / "manifests").glob("knowledge-hub-source-coverage-closeout-*.jsonl"))
    source_ids = set()
    by_source_ids = set()
    coverage_ids = set()
    coverage_path = coverage_paths[-1] if coverage_paths else None
    errors = []
    try:
        current_source_rows = json.loads(sources_path.read_text()).get("sources", [])
        retired_source_rows = [
            json.loads(line)
            for line in retired_sources_path.read_text().splitlines()
            if line.strip()
        ]
        source_ids = {item.get("id", "") for item in current_source_rows + retired_source_rows}
    except Exception as exc:
        errors.append(f"sources parse: {exc}")
    try:
        in_table = False
        for line in by_source_path.read_text().splitlines():
            stripped = line.strip()
            if not stripped:
                if in_table:
                    break
                continue
            if not stripped.startswith("|"):
                continue
            cells = [cell.strip().strip("`") for cell in stripped.strip("|").split("|")]
            if len(cells) < 3 or cells[0] in {"Source", "---"}:
                continue
            in_table = True
            by_source_ids.add(cells[0])
    except Exception as exc:
        errors.append(f"by-source parse: {exc}")
    if coverage_path:
        try:
            for line in coverage_path.read_text().splitlines():
                if not line.strip():
                    continue
                row = json.loads(line)
                coverage_ids.add(row.get("source_id", ""))
        except Exception as exc:
            errors.append(f"coverage parse: {exc}")
    else:
        errors.append("missing source coverage closeout jsonl")
    expect(
        not errors
        and coverage_path is not None
        and coverage_path.name == "knowledge-hub-source-coverage-closeout-20260624.jsonl"
        and expected <= source_ids
        and expected <= by_source_ids
        and expected <= coverage_ids,
        "pcr02-level2-source-coverage",
        "PCR02 Level 2 sources are registered, indexed and covered",
        {
            "errors": errors,
            "latest_coverage": str(coverage_path.relative_to(root)) if coverage_path else "",
            "missing_sources": sorted(expected - source_ids),
            "missing_by_source": sorted(expected - by_source_ids),
            "missing_coverage": sorted(expected - coverage_ids),
            "registered_count": len(source_ids),
            "coverage_count": len(coverage_ids),
        },
    )

def test_pcr02_level2_boundary_manifests():
    expected = {
        "pcr02-tools-boundary-20260620": {
            "md": "artifacts/manifests/pcr02-tools-boundary-20260620.md",
            "jsonl": "artifacts/manifests/pcr02-tools-boundary-20260620.jsonl",
            "source_id": "pcr02-project-tools",
            "required_text": "memory-candidate-automation-ref",
        },
        "pcr02-knowledge-secret-config-boundary-20260620": {
            "md": "artifacts/manifests/pcr02-knowledge-secret-config-boundary-20260620.md",
            "jsonl": "artifacts/manifests/pcr02-knowledge-secret-config-boundary-20260620.jsonl",
            "source_id": "pcr02-project-knowledge",
            "required_text": "project-local-standard-candidate",
        },
        "pcr02-product-test-artifact-config-interface-boundary-20260620": {
            "md": "artifacts/manifests/pcr02-product-test-artifact-config-interface-boundary-20260620.md",
            "jsonl": "artifacts/manifests/pcr02-product-test-artifact-config-interface-boundary-20260620.jsonl",
            "source_id": "pcr02-product-test",
            "required_text": "build-artifact-generated",
        },
        "pcr02-scratch-archive-boundary-20260620": {
            "md": "artifacts/manifests/pcr02-scratch-archive-boundary-20260620.md",
            "jsonl": "artifacts/manifests/pcr02-scratch-archive-boundary-20260620.jsonl",
            "source_id": "pcr02-project-scratch",
            "required_text": "historical-session-evidence",
        },
        "pcr02-root-artifacts-boundary-20260620": {
            "md": "artifacts/manifests/pcr02-root-artifacts-boundary-20260620.md",
            "jsonl": "artifacts/manifests/pcr02-root-artifacts-boundary-20260620.jsonl",
            "source_id": "pcr02-project-root-artifacts",
            "required_text": "source-coverage-evidence-drift",
        },
        "pcr02-module-agent-rules-boundary-20260620": {
            "md": "artifacts/manifests/pcr02-module-agent-rules-boundary-20260620.md",
            "jsonl": "artifacts/manifests/pcr02-module-agent-rules-boundary-20260620.jsonl",
            "source_id": "pcr02-module-agent-rules",
            "required_text": "module-local-owner-gated-control-entry-rule",
        },
        "pcr02-agent-config-boundary-20260620": {
            "md": "artifacts/manifests/pcr02-agent-config-boundary-20260620.md",
            "jsonl": "artifacts/manifests/pcr02-agent-config-boundary-20260620.jsonl",
            "source_id": "pcr02-project-agent-config",
            "required_text": "third-party-dependency-artifact",
        },
    }
    errors = []
    registry_ids = set()
    by_source_text = ""
    by_project_text = ""
    try:
        for line in (root / "registry" / "items.jsonl").read_text().splitlines():
            if line.strip():
                registry_ids.add(json.loads(line).get("id", ""))
    except Exception as exc:
        errors.append(f"registry parse: {exc}")
    try:
        by_source_text = (root / "indexes" / "by-source.md").read_text()
        by_project_text = (root / "indexes" / "by-project.md").read_text()
    except Exception as exc:
        errors.append(f"index read: {exc}")
    row_source_ids = {}
    row_counts = {}
    missing_files = []
    missing_required_text = []
    for item_id, spec in expected.items():
        md_path = root / spec["md"]
        jsonl_path = root / spec["jsonl"]
        if not md_path.exists():
            missing_files.append(spec["md"])
        if not jsonl_path.exists():
            missing_files.append(spec["jsonl"])
            continue
        rows = []
        try:
            for line in jsonl_path.read_text().splitlines():
                if line.strip():
                    rows.append(json.loads(line))
        except Exception as exc:
            errors.append(f"{spec['jsonl']} parse: {exc}")
        row_counts[item_id] = len(rows)
        row_source_ids[item_id] = sorted({row.get("source_id", "") for row in rows})
        if rows and set(row_source_ids[item_id]) != {spec["source_id"]}:
            errors.append(f"{item_id} source_id mismatch: {row_source_ids[item_id]}")
        try:
            md_text = md_path.read_text()
        except Exception as exc:
            errors.append(f"{spec['md']} read: {exc}")
            md_text = ""
        if spec["required_text"] not in md_text:
            missing_required_text.append(spec["required_text"])
    missing_registry = sorted(set(expected) - registry_ids)
    missing_by_source = [spec["md"] for spec in expected.values() if spec["md"] not in by_source_text]
    missing_by_project = [spec["md"] for spec in expected.values() if spec["md"] not in by_project_text]
    expect(
        not errors
        and not missing_files
        and not missing_registry
        and not missing_by_source
        and not missing_by_project
        and not missing_required_text
        and all(count > 0 for count in row_counts.values()),
        "pcr02-level2-boundary-manifests",
        "PCR02 Level 2 boundary manifests are registered and indexed",
        {
            "errors": errors,
            "missing_files": missing_files,
            "missing_registry": missing_registry,
            "missing_by_source": missing_by_source,
            "missing_by_project": missing_by_project,
            "missing_required_text": missing_required_text,
            "row_counts": row_counts,
            "row_source_ids": row_source_ids,
        },
    )

def test_boundary_health_internal_evidence():
    result = run_cmd(root, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    parsed = {}
    parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    boundary_health = parsed.get("boundary_health", {}) if isinstance(parsed, dict) else {}

    repo = copy_repo("boundary-health-source-id-mismatch")
    boundary_path = repo / "artifacts" / "manifests" / "pcr02-tools-boundary-20260620.jsonl"
    rows = [json.loads(line) for line in boundary_path.read_text().splitlines() if line.strip()]
    if rows:
        rows[0]["source_id"] = "pcr02-wrong-source"
    boundary_path.write_text("\n".join(json.dumps(row, ensure_ascii=False) for row in rows) + "\n")
    bad_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    bad_parsed = {}
    bad_parse_error = ""
    try:
        bad_parsed = json.loads(bad_result["stdout"])
    except Exception as exc:
        bad_parse_error = str(exc)
    bad_boundary_health = bad_parsed.get("boundary_health", {}) if isinstance(bad_parsed, dict) else {}
    expect(
        result["exit_code"] == 0
        and not parse_error
        and boundary_health.get("status") == "pass"
        and boundary_health.get("mode") == "read-only-internal-evidence"
        and boundary_health.get("scope") == "pcr02-level2-boundary-manifests"
        and boundary_health.get("source_project_read") is False
        and boundary_health.get("owner_gate_mutation") is False
        and boundary_health.get("memory_write") is False
        and boundary_health.get("expected_boundary_count") == 7
        and boundary_health.get("jsonl_manifest_count") == 7
        and boundary_health.get("md_manifest_count") == 7
        and boundary_health.get("row_count") == 78
        and boundary_health.get("summary", {}).get("registered_item_count") == 7
        and boundary_health.get("summary", {}).get("source_coverage_count") == 7
        and boundary_health.get("summary", {}).get("by_source_reference_count") == 7
        and boundary_health.get("summary", {}).get("by_project_reference_count") == 7
        and boundary_health.get("hard_failures") == []
        and bad_result["exit_code"] != 0
        and not bad_parse_error
        and bad_boundary_health.get("status") == "fail"
        and bad_boundary_health.get("source_id_mismatch_rows")
        and any("boundary-health:" in str(error) for error in bad_parsed.get("errors", [])),
        "boundary-health-internal-evidence",
        "boundary health is a read-only internal evidence gate for PCR02 Level 2 manifests",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "boundary_health": boundary_health,
            "bad_exit_code": bad_result["exit_code"],
            "bad_parse_error": bad_parse_error,
            "bad_boundary_health": bad_boundary_health,
            "bad_errors": bad_parsed.get("errors", [])[:5],
        },
    )
