"""Generated regression cases: terminal gates."""

# Generated by regression_codegen.py; edit assertions here, then keep the generator deterministic.
from .support import *  # noqa: F401,F403

def test_status_wrong_bucket():
    repo = copy_repo("status-wrong-bucket")
    path = repo / "indexes" / "by-status.md"
    text = path.read_text()
    old = "- active: `knowledge-hub-root`"
    new = "- reviewing: `knowledge-hub-root`"
    if old not in text:
        expect(False, "status-wrong-bucket", "status bucket mismatch is rejected", {"setup_error": f"missing {old}"}, repo)
        return
    path.write_text(text.replace(old, new, 1))
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    expect(
        result["exit_code"] != 0 and "wrong status bucket" in result["stdout"],
        "status-wrong-bucket",
        "status bucket mismatch is rejected",
        {"exit_code": result["exit_code"], "expected": "wrong status bucket", "stdout_sample": result["stdout"][:1000]},
        repo,
    )

def test_status_noncanonical_only():
    repo = copy_repo("status-noncanonical-only")
    item_id = "knowledge-hub-owner-status-gate-hardening-20260619"
    path = repo / "indexes" / "by-status.md"
    text = path.read_text()
    old = f"- archived: `{item_id}`"
    new = f"- noncanonical-note: `{item_id}`"
    if old not in text:
        expect(False, "status-noncanonical-only", "noncanonical status mention is not enough", {"setup_error": f"missing {old}"}, repo)
        return
    path.write_text(text.replace(old, new, 1))
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    expect(
        result["exit_code"] != 0 and f"missing item {item_id}" in result["stdout"],
        "status-noncanonical-only",
        "noncanonical status mention is not enough",
        {"exit_code": result["exit_code"], "expected": f"missing item {item_id}", "stdout_sample": result["stdout"][:1000]},
        repo,
    )

def test_status_next_owner_gate():
    repo = copy_repo_with_open_owner_gates("status-next-owner-gate")
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--json"])
    strict_result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--strict", "--json"])
    expected_final_gate_command = "rtk bash ~/knowledge-hub/tools/knowledge-final-gate.sh --json --final-profile product"
    if today_source != "system-date":
        expected_final_gate_command = f"rtk bash ~/knowledge-hub/tools/knowledge-final-gate.sh --as-of {today.isoformat()} --json --final-profile product"
    parsed = {}
    strict_parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    try:
        strict_parsed = json.loads(strict_result["stdout"])
    except Exception:
        pass
    next_open = parsed.get("owner_gates", {}).get("next_open", {})
    owner_gates = parsed.get("owner_gates", {})
    owner_dispatch = parsed.get("owner_gates", {}).get("owner_dispatch", [])
    dispatch_by_owner = {row.get("owner"): row for row in owner_dispatch}
    project_owner_dispatch = dispatch_by_owner.get("project-owner", {})
    project_owner_handoff_packet = project_owner_dispatch.get("suggested_owner_packet", {})
    project_owner_route = project_owner_dispatch.get("owner_route", {})
    summary_commands = parsed.get("owner_gates", {}).get("summary_commands", [])
    owner_summary_commands = parsed.get("owner_gates", {}).get("owner_summary_commands", [])
    owner_forms_jsonl_commands = parsed.get("owner_gates", {}).get("owner_forms_jsonl_commands", [])
    owner_evidence_readiness_commands = parsed.get("owner_gates", {}).get("owner_evidence_readiness_commands", [])
    owner_validate_forms_command_templates = parsed.get("owner_gates", {}).get("owner_validate_forms_command_templates", [])
    owner_landing_plan_command_templates = parsed.get("owner_gates", {}).get("owner_landing_plan_command_templates", [])
    owner_landing_audit_command_templates = parsed.get("owner_gates", {}).get("owner_landing_audit_command_templates", [])
    forms_jsonl_commands = parsed.get("owner_gates", {}).get("forms_jsonl_commands", [])
    evidence_readiness_commands = parsed.get("owner_gates", {}).get("evidence_readiness_commands", [])
    validate_forms_command_templates = parsed.get("owner_gates", {}).get("validate_forms_command_templates", [])
    landing_plan_command_templates = parsed.get("owner_gates", {}).get("landing_plan_command_templates", [])
    landing_audit_command_templates = parsed.get("owner_gates", {}).get("landing_audit_command_templates", [])
    final_gate_command = parsed.get("final_gate_command", "")
    next_actions = parsed.get("next_actions_zh", [])
    owner_blocker_source = strict_parsed.get("owner_blocker_source", {})
    strict_blockers = strict_parsed.get("strict_blockers", [])
    owner_blocker = next(
        (blocker for blocker in strict_blockers if blocker.get("id") == "owner-gates-open"),
        {},
    )
    next_open_queue = owner_gates.get("next_open_queue", [])
    first_queue_row = next_open_queue[0] if next_open_queue else {}
    second_queue_row = next_open_queue[1] if len(next_open_queue) > 1 else {}
    queue_executable_commands = []
    for row in next_open_queue:
        for field in ["focus_command", "forms_jsonl_command", "evidence_readiness_command"]:
            queue_executable_commands.append(str(row.get(field, "")))
    queue_template_commands = []
    for row in next_open_queue:
        for field in ["validate_forms_command_template", "landing_plan_command_template", "landing_audit_command_template"]:
            queue_template_commands.append(str(row.get(field, "")))
    expect(
        result["exit_code"] == 0
        and strict_result["exit_code"] == 1
        and parsed.get("status") == "needs-owner-review"
        and strict_parsed.get("strict") is True
        and strict_parsed.get("status") == "needs-owner-review"
        and owner_blocker_source.get("status_source") == "knowledge-status --strict"
        and "owner-gates-open" in owner_blocker_source.get("strict_blocker_ids", [])
        and owner_blocker_source.get("owner_gate_open_count_field") == "owner_gates.open_count"
        and owner_blocker_source.get("open_count") == 7
        and owner_blocker_source.get("owner_ready_package_coverage") == "7/7"
        and owner_blocker_source.get("owner_ready_row_status_source") == "knowledge-owner-gates.rows[].owner_ready_package_status"
        and owner_blocker_source.get("owner_ready_row_schema_error_count") == 0
        and owner_blocker_source.get("active_exposure_count") == 0
        and owner_gates.get("owner_ready_package_count") == 7
        and owner_gates.get("owner_ready_missing_count") == 0
        and owner_gates.get("owner_ready_invalid_count") == 0
        and owner_gates.get("owner_ready_duplicate_count") == 0
        and owner_gates.get("owner_ready_package_coverage") == "7/7"
        and owner_gates.get("owner_ready_row_status_source") == "knowledge-owner-gates.rows[].owner_ready_package_status"
        and owner_gates.get("owner_ready_row_schema_errors") == []
        and len(owner_dispatch) == 6
        and project_owner_dispatch.get("open_count") == 2
        and project_owner_handoff_packet.get("status") == "ready-for-owner-review"
        and project_owner_handoff_packet.get("read_only") is True
        and owner_gates.get("source_identity_read_policy", {}).get("source_body_read_for_hash") is True
        and owner_gates.get("source_identity_read_policy", {}).get("source_body_copied") is False
        and owner_gates.get("source_identity_read_policy", {}).get("source_project_written") is False
        and project_owner_handoff_packet.get("suggested_local_owner_decisions_path") == "artifacts/manifests/pcr02-project-docs-project-owner-owner-decisions-YYYYMMDD.local.jsonl"
        and project_owner_handoff_packet.get("source_identity_read_policy", {}).get("source_body_read_for_hash") is True
        and len(project_owner_handoff_packet.get("recommended_sequence", [])) == 7
        and all(step.get("notes_zh") for step in project_owner_handoff_packet.get("recommended_sequence", []))
        and any(step.get("step") == "1-open-owner-inbox" and "--owner-inbox --json" in step.get("command", "") for step in project_owner_handoff_packet.get("recommended_sequence", []))
        and any(step.get("step") == "5-validate-filled-forms" and "owner-decisions.jsonl" in step.get("command_template", "") for step in project_owner_handoff_packet.get("recommended_sequence", []))
        and project_owner_route.get("routing_owner") == "pcr02-registry-owner"
        and project_owner_route.get("no_owner_decision_generated") is True
        and "pcr02-owner-decision-worksheet-005" in project_owner_dispatch.get("worksheet_ids", [])
        and "--owner project-owner --owner-inbox --json" in project_owner_dispatch.get("owner_inbox_json_command", "")
        and "--owner project-owner --forms-jsonl" in project_owner_dispatch.get("forms_jsonl_command", "")
        and "--owner project-owner --evidence-readiness --json" in project_owner_dispatch.get("evidence_readiness_command", "")
        and "--owner project-owner --validate-forms '<owner-decisions.jsonl>' --json" in project_owner_dispatch.get("validate_forms_command_template", "")
        and "--owner project-owner --validate-forms '<owner-decisions.jsonl>' --landing-plan --json" in project_owner_dispatch.get("landing_plan_command_template", "")
        and "--owner project-owner --validate-forms '<owner-decisions.jsonl>' --landing-audit --json" in project_owner_dispatch.get("landing_audit_command_template", "")
        and "--owner project-owner --worksheet-id pcr02-owner-decision-worksheet-005 --checklist --forms" in project_owner_dispatch.get("next_focus_command", "")
        and any("--summary" in str(command) for command in summary_commands)
        and any("--owner project-owner" in str(command) and "--summary" in str(command) for command in owner_summary_commands)
        and any("--owner project-owner" in str(command) and "--forms-jsonl" in str(command) for command in owner_forms_jsonl_commands)
        and any("--owner project-owner" in str(command) and "--evidence-readiness --json" in str(command) for command in owner_evidence_readiness_commands)
        and any("--owner project-owner" in str(command) and "--validate-forms" in str(command) and "owner-decisions.jsonl" in str(command) for command in owner_validate_forms_command_templates)
        and any("--owner project-owner" in str(command) and "--landing-plan" in str(command) and "owner-decisions.jsonl" in str(command) for command in owner_landing_plan_command_templates)
        and any("--owner project-owner" in str(command) and "--landing-audit" in str(command) and "owner-decisions.jsonl" in str(command) for command in owner_landing_audit_command_templates)
        and any("--forms-jsonl" in str(command) for command in forms_jsonl_commands)
        and any("--evidence-readiness --json" in str(command) for command in evidence_readiness_commands)
        and any("--validate-forms" in str(command) and "owner-decisions.jsonl" in str(command) and "--json" in str(command) for command in validate_forms_command_templates)
        and any("--validate-forms" in str(command) and "owner-decisions.jsonl" in str(command) and "--landing-plan" in str(command) and "--json" in str(command) for command in landing_plan_command_templates)
        and any("--validate-forms" in str(command) and "owner-decisions.jsonl" in str(command) and "--landing-audit" in str(command) and "--json" in str(command) for command in landing_audit_command_templates)
        and final_gate_command == expected_final_gate_command
        and next_open.get("worksheet_id") == "pcr02-owner-decision-worksheet-001"
        and next_open.get("owner_route", {}).get("routing_owner") == "pcr02-registry-owner"
        and next_open.get("owner_route", {}).get("no_owner_decision_generated") is True
        and "--next-open" in next_open.get("next_open_command", "")
        and "--checklist" in next_open.get("next_open_command", "")
        and "--forms" in next_open.get("next_open_command", "")
        and "--next-open" in next_open.get("next_open_forms_jsonl_command", "")
        and "--forms-jsonl" in next_open.get("next_open_forms_jsonl_command", "")
        and "--next-open" in next_open.get("next_open_evidence_readiness_command", "")
        and "--evidence-readiness" in next_open.get("next_open_evidence_readiness_command", "")
        and "--worksheet-id pcr02-owner-decision-worksheet-001" in next_open.get("focus_command", "")
        and "--checklist" in next_open.get("focus_command", "")
        and "--forms" in next_open.get("focus_command", "")
        and "--worksheet-id pcr02-owner-decision-worksheet-001" in next_open.get("focus_forms_jsonl_command", "")
        and "--forms-jsonl" in next_open.get("focus_forms_jsonl_command", "")
        and "--worksheet-id pcr02-owner-decision-worksheet-001" in next_open.get("focus_evidence_readiness_command", "")
        and "--evidence-readiness" in next_open.get("focus_evidence_readiness_command", "")
        and "--worksheet-id pcr02-owner-decision-worksheet-001" in next_open.get("focus_validate_forms_command_template", "")
        and "--validate-forms" in next_open.get("focus_validate_forms_command_template", "")
        and "owner-decisions.jsonl" in next_open.get("focus_validate_forms_command_template", "")
        and "--worksheet-id pcr02-owner-decision-worksheet-001" in next_open.get("focus_landing_plan_command_template", "")
        and "--validate-forms" in next_open.get("focus_landing_plan_command_template", "")
        and "--landing-plan" in next_open.get("focus_landing_plan_command_template", "")
        and "owner-decisions.jsonl" in next_open.get("focus_landing_plan_command_template", "")
        and "--worksheet-id pcr02-owner-decision-worksheet-001" in next_open.get("focus_landing_audit_command_template", "")
        and "--validate-forms" in next_open.get("focus_landing_audit_command_template", "")
        and "--landing-audit" in next_open.get("focus_landing_audit_command_template", "")
        and "owner-decisions.jsonl" in next_open.get("focus_landing_audit_command_template", "")
        and owner_gates.get("next_open_queue_count") == 7
        and owner_gates.get("next_open_queue_selection_order") == "review_after, worksheet_id"
        and len(next_open_queue) == 7
        and first_queue_row.get("worksheet_id") == "pcr02-owner-decision-worksheet-001"
        and first_queue_row.get("source_path") == "AGENTS.md"
        and first_queue_row.get("owner_ready_package_status") == "covered"
        and first_queue_row.get("owner_ready_source") == "knowledge-owner-gates.rows[].owner_ready_package_status"
        and first_queue_row.get("owner_ready_package_status_source") == "knowledge-owner-gates.owner_ready_state"
        and first_queue_row.get("owner_ready_package_count") == 1
        and "pcr02-agents-owner-ready-package-20260620" in first_queue_row.get("owner_ready_package_ids", [])
        and "--worksheet-id pcr02-owner-decision-worksheet-001 --checklist --forms" in first_queue_row.get("focus_command", "")
        and "--worksheet-id pcr02-owner-decision-worksheet-001 --forms-jsonl" in first_queue_row.get("forms_jsonl_command", "")
        and "--worksheet-id pcr02-owner-decision-worksheet-001 --evidence-readiness --json" in first_queue_row.get("evidence_readiness_command", "")
        and "owner-decisions.jsonl" in first_queue_row.get("validate_forms_command_template", "")
        and second_queue_row.get("worksheet_id") == "pcr02-owner-decision-worksheet-002"
        and second_queue_row.get("source_path") == "standards/diag-command-metadata-standard.md"
        and second_queue_row.get("owner") == "pcr02-diag-owner-or-team-core"
        and second_queue_row.get("owner_ready_package_status") == "covered"
        and second_queue_row.get("owner_ready_source") == "knowledge-owner-gates.rows[].owner_ready_package_status"
        and second_queue_row.get("owner_ready_package_status_source") == "knowledge-owner-gates.owner_ready_state"
        and second_queue_row.get("owner_ready_package_count") == 1
        and not any("owner-decisions.jsonl" in command for command in queue_executable_commands)
        and any("owner-decisions.jsonl" in command and "--landing-plan" in command for command in queue_template_commands)
        and any("owner-decisions.jsonl" in command and "--landing-audit" in command for command in queue_template_commands)
        and any("--summary" in str(action) for action in next_actions)
        and any("--owner" in str(action) and "--summary" in str(action) for action in next_actions)
        and any("owner_gates.owner_dispatch[]" in str(action) for action in next_actions)
        and any("--owner" in str(action) and "--forms-jsonl" in str(action) for action in next_actions)
        and any("--owner" in str(action) and "--evidence-readiness" in str(action) for action in next_actions)
        and any("--owner" in str(action) and "--validate-forms" in str(action) for action in next_actions)
        and any("--owner" in str(action) and "--landing-plan" in str(action) for action in next_actions)
        and any("--owner" in str(action) and "--landing-audit" in str(action) for action in next_actions)
        and any("knowledge-final-gate.sh" in str(action) and "--json" in str(action) for action in next_actions)
        and any("--next-open --checklist --forms" in str(action) for action in next_actions)
        and any("--next-open --forms-jsonl" in str(action) for action in next_actions)
        and any("--next-open --evidence-readiness --json" in str(action) for action in next_actions)
        and any("--validate-forms" in str(action) and "owner-decisions.jsonl" in str(action) for action in next_actions)
        and any("--landing-plan" in str(action) for action in next_actions)
        and any("--landing-audit" in str(action) for action in next_actions)
        and owner_blocker.get("count") == 7
        and any("--summary" in str(command) for command in owner_blocker.get("commands", []))
        and any("--owner project-owner" in str(command) and "--summary" in str(command) for command in owner_blocker.get("commands", []))
        and any("--owner project-owner" in str(command) and "--forms-jsonl" in str(command) for command in owner_blocker.get("commands", []))
        and any("--owner project-owner" in str(command) and "--evidence-readiness --json" in str(command) for command in owner_blocker.get("commands", []))
        and any("--next-open --checklist --forms" in str(command) for command in owner_blocker.get("commands", []))
        and any("--next-open --forms-jsonl" in str(command) for command in owner_blocker.get("commands", []))
        and any("--next-open --evidence-readiness --json" in str(command) for command in owner_blocker.get("commands", []))
        and not any("owner-decisions.jsonl" in str(command) for command in owner_blocker.get("commands", []))
        and any("--owner project-owner" in str(command) and "--validate-forms" in str(command) and "owner-decisions.jsonl" in str(command) for command in owner_blocker.get("command_templates", []))
        and any("--owner project-owner" in str(command) and "--landing-plan" in str(command) and "owner-decisions.jsonl" in str(command) for command in owner_blocker.get("command_templates", []))
        and any("--owner project-owner" in str(command) and "--landing-audit" in str(command) and "owner-decisions.jsonl" in str(command) for command in owner_blocker.get("command_templates", []))
        and any("--validate-forms" in str(command) and "owner-decisions.jsonl" in str(command) for command in owner_blocker.get("command_templates", []))
        and any("--landing-plan" in str(command) for command in owner_blocker.get("command_templates", []))
        and any("--landing-audit" in str(command) for command in owner_blocker.get("command_templates", []))
        and owner_blocker.get("owner_blocker_source", {}).get("open_count") == 7,
        "status-next-owner-gate",
        "status dashboard separates executable owner commands from validation and landing templates",
        {
            "exit_code": result["exit_code"],
            "strict_exit_code": strict_result["exit_code"],
            "status": parsed.get("status"),
            "strict_status": strict_parsed.get("status"),
            "owner_ready_package_coverage": owner_gates.get("owner_ready_package_coverage"),
            "owner_ready_missing_count": owner_gates.get("owner_ready_missing_count"),
            "owner_ready_invalid_count": owner_gates.get("owner_ready_invalid_count"),
            "owner_ready_duplicate_count": owner_gates.get("owner_ready_duplicate_count"),
            "owner_dispatch": owner_dispatch,
            "project_owner_handoff_packet": project_owner_handoff_packet,
            "worksheet_id": next_open.get("worksheet_id"),
            "summary_commands": summary_commands,
            "owner_summary_commands": owner_summary_commands,
            "owner_forms_jsonl_commands": owner_forms_jsonl_commands,
            "owner_evidence_readiness_commands": owner_evidence_readiness_commands,
            "owner_validate_forms_command_templates": owner_validate_forms_command_templates,
            "owner_landing_plan_command_templates": owner_landing_plan_command_templates,
            "owner_landing_audit_command_templates": owner_landing_audit_command_templates,
            "forms_jsonl_commands": forms_jsonl_commands,
            "evidence_readiness_commands": evidence_readiness_commands,
            "validate_forms_command_templates": validate_forms_command_templates,
            "landing_plan_command_templates": landing_plan_command_templates,
            "landing_audit_command_templates": landing_audit_command_templates,
            "final_gate_command": final_gate_command,
            "expected_final_gate_command": expected_final_gate_command,
            "next_open_command": next_open.get("next_open_command", ""),
            "next_open_forms_jsonl_command": next_open.get("next_open_forms_jsonl_command", ""),
            "next_open_evidence_readiness_command": next_open.get("next_open_evidence_readiness_command", ""),
            "focus_command": next_open.get("focus_command", ""),
            "focus_forms_jsonl_command": next_open.get("focus_forms_jsonl_command", ""),
            "focus_evidence_readiness_command": next_open.get("focus_evidence_readiness_command", ""),
            "focus_validate_forms_command_template": next_open.get("focus_validate_forms_command_template", ""),
            "focus_landing_plan_command_template": next_open.get("focus_landing_plan_command_template", ""),
            "focus_landing_audit_command_template": next_open.get("focus_landing_audit_command_template", ""),
            "next_open_queue_count": owner_gates.get("next_open_queue_count"),
            "next_open_queue": next_open_queue,
            "owner_blocker_source": owner_blocker_source,
            "strict_blockers": strict_blockers,
            "next_actions_zh": next_actions,
            "stdout_sample": result["stdout"][:1000],
            "strict_stdout_sample": strict_result["stdout"][:1000],
        },
    )
def test_status_owner_ready_source_no_registry_fallback():
    source = (root / "tools" / "codex_assets" / "knowledge_hub" / "status_cli.py").read_text()
    banned_fragments = [
        "covered\" if owner_ready_packages or registry_items else \"missing",
        "owner_ready_package_ids = [str(item.get(\"id\", \"\")) for item in registry_items",
        "owner_ready_package_count\": len(owner_ready_packages) if owner_ready_packages else len(registry_items)",
    ]
    required_fragments = [
        "OWNER_READY_ROW_STATUS_SOURCE = \"knowledge-owner-gates.rows[].owner_ready_package_status\"",
        "\"owner_ready_source\": OWNER_READY_ROW_STATUS_SOURCE",
        "\"id\": \"owner-ready-row-schema-missing\"",
    ]
    present_banned = [fragment for fragment in banned_fragments if fragment in source]
    missing_required = [fragment for fragment in required_fragments if fragment not in source]
    expect(
        not present_banned and not missing_required,
        "status-owner-ready-source-no-registry-fallback",
        "status next_open_queue owner-ready state comes from owner-gates row validation, not registry_items fallback",
        {
            "present_banned_fragments": present_banned,
            "missing_required_fragments": missing_required,
        },
    )

def test_final_gate_maintenance_entry_wording_no_section_drift():
    source = (root / "tools" / "codex_assets" / "knowledge_hub" / "product_gate.py").read_text()
    banned_fragments = [
        "第七节 8 类长期维护入口",
        "第七节长期维护入口",
    ]
    required_fragments = [
        "docs/goals 中列出的 8 类长期维护入口和 1 个离线维护包均有文档、工具或回归证据。",
        "docs/goals 中列出的 8 类长期维护入口和 1 个离线维护包均可恢复；只证明入口存在，不代表人工动作已完成。",
    ]
    present_banned = [fragment for fragment in banned_fragments if fragment in source]
    missing_required = [fragment for fragment in required_fragments if fragment not in source]
    expect(
        not present_banned and not missing_required,
        "final-gate-maintenance-entry-wording-no-section-drift",
        "final gate maintenance entry wording points to docs/goals instead of stale section numbering",
        {
            "present_banned_fragments": present_banned,
            "missing_required_fragments": missing_required,
        },
    )

def test_status_text_owner_summary_commands():
    repo = copy_repo_with_open_owner_gates("status-text-owner-summary-commands")
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh"])
    expect(
        result["exit_code"] == 0
        and "- owner summary commands:" in result["stdout"]
        and "rtk bash ~/knowledge-hub/tools/knowledge-owner-gates.sh --source-id pcr02-project-docs --owner project-owner --summary" in result["stdout"]
        and "- owner forms-jsonl commands:" in result["stdout"]
        and "rtk bash ~/knowledge-hub/tools/knowledge-owner-gates.sh --source-id pcr02-project-docs --owner project-owner --forms-jsonl" in result["stdout"]
        and "- owner validate-forms command templates:" in result["stdout"]
        and "rtk bash ~/knowledge-hub/tools/knowledge-owner-gates.sh --source-id pcr02-project-docs --owner project-owner --validate-forms '<owner-decisions.jsonl>' --json" in result["stdout"]
        and "- owner landing plan command templates:" in result["stdout"]
        and "rtk bash ~/knowledge-hub/tools/knowledge-owner-gates.sh --source-id pcr02-project-docs --owner project-owner --validate-forms '<owner-decisions.jsonl>' --landing-plan --json" in result["stdout"]
        and "- owner landing audit command templates:" in result["stdout"]
        and "rtk bash ~/knowledge-hub/tools/knowledge-owner-gates.sh --source-id pcr02-project-docs --owner project-owner --validate-forms '<owner-decisions.jsonl>' --landing-audit --json" in result["stdout"]
        and "- review_after command: `rtk bash ~/knowledge-hub/tools/knowledge-index-plan.sh --section review-date`" in result["stdout"]
        and "- review_after near-due command: `rtk bash ~/knowledge-hub/tools/knowledge-review-after.sh --as-of " in result["stdout"]
        and " --window-days 30 --json`" in result["stdout"]
        and "- source check report command: `rtk bash ~/knowledge-hub/tools/knowledge-source-check.sh --scope all --as-of " in result["stdout"],
        "status-text-owner-summary-commands",
        "status text mode exposes owner dispatch, owner validation templates, review_after and source-check report commands",
        {
            "exit_code": result["exit_code"],
            "has_owner_summary_heading": "- owner summary commands:" in result["stdout"],
            "has_project_owner_summary": "rtk bash ~/knowledge-hub/tools/knowledge-owner-gates.sh --source-id pcr02-project-docs --owner project-owner --summary" in result["stdout"],
            "has_project_owner_forms_jsonl": "rtk bash ~/knowledge-hub/tools/knowledge-owner-gates.sh --source-id pcr02-project-docs --owner project-owner --forms-jsonl" in result["stdout"],
            "has_project_owner_validate_forms": "rtk bash ~/knowledge-hub/tools/knowledge-owner-gates.sh --source-id pcr02-project-docs --owner project-owner --validate-forms '<owner-decisions.jsonl>' --json" in result["stdout"],
            "has_project_owner_landing_plan": "rtk bash ~/knowledge-hub/tools/knowledge-owner-gates.sh --source-id pcr02-project-docs --owner project-owner --validate-forms '<owner-decisions.jsonl>' --landing-plan --json" in result["stdout"],
            "has_project_owner_landing_audit": "rtk bash ~/knowledge-hub/tools/knowledge-owner-gates.sh --source-id pcr02-project-docs --owner project-owner --validate-forms '<owner-decisions.jsonl>' --landing-audit --json" in result["stdout"],
            "has_review_after_command": "- review_after command: `rtk bash ~/knowledge-hub/tools/knowledge-index-plan.sh --section review-date`" in result["stdout"],
            "has_review_after_near_due_command": "- review_after near-due command: `rtk bash ~/knowledge-hub/tools/knowledge-review-after.sh --as-of " in result["stdout"],
            "has_source_check_report_command": "- source check report command: `rtk bash ~/knowledge-hub/tools/knowledge-source-check.sh --scope all --as-of " in result["stdout"],
            "stdout_sample": result["stdout"][:1200],
        },
    )

def test_status_owner_gates_exit_code_blocker():
    repo = copy_repo("status-owner-gates-exit-code-blocker")
    owner_gates_path = repo / "tools" / "knowledge-owner-gates.sh"
    owner_gates_path.write_text(
        "#!/usr/bin/env bash\n"
        "printf '%s\\n' '{\"schema_version\":1,\"row_count\":0,\"open_count\":0,\"active_exposure_count\":0,\"owner_ready_package_count\":0}'\n"
        "printf '%s\\n' 'fixture owner-gates failure' >&2\n"
        "exit 1\n"
    )
    result = run_cmd(repo, ["rtk", "bash", "tools/knowledge-status.sh", "--strict", "--json"])
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    blocker = next(
        (
            item
            for item in parsed.get("strict_blockers", [])
            if item.get("id") == "owner-gates-command-failed"
        ),
        {},
    )
    expect(
        result["exit_code"] == 1
        and parsed.get("status") == "needs-fix"
        and blocker.get("severity") == "blocker"
        and blocker.get("exit_code") == 1
        and "fixture owner-gates failure" in blocker.get("stderr_sample", ""),
        "status-owner-gates-exit-code-blocker",
        "status dashboard blocks non-zero owner-gates child command even when JSON is parseable",
        {
            "exit_code": result["exit_code"],
            "status": parsed.get("status"),
            "strict_blockers": parsed.get("strict_blockers", []),
            "owner_gates": parsed.get("owner_gates", {}),
            "stdout_sample": result["stdout"][:1200],
            "stderr_sample": result["stderr"][:500],
        },
        repo,
    )


def test_status_product_profile_blocks_noncanonical_residue():
    repo = copy_repo("status-product-profile-blocks-noncanonical-residue")
    injected = {
        "id": "migrated-fixture-copyfirst-20260628",
        "title": "Migrated fixture copy-first 2026-06-28",
        "kind": "audit",
        "domain": "governance",
        "path": "artifacts/manifests/migrated-fixture-copyfirst-20260628.md",
        "scope": "team-general",
        "visibility": "team-internal",
        "status": "reviewing",
        "owner": "leiwenjun",
        "source": {"type": "generated"},
        "validation_refs": ["tools/knowledge-check.sh --dry-run --json --diagnostics"],
        "tags": ["copy-first", "migration-baseline"],
        "review_after": today.isoformat(),
        "promotion": "none",
        "review_status": "owner-ready-no-decision",
        "created_at": today.isoformat(),
        "updated_at": today.isoformat(),
    }
    items_path = repo / "registry" / "items.jsonl"
    with items_path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(injected, ensure_ascii=False, separators=(",", ":")) + "\n")
    unsupported_profile_result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-status.sh",
            "--strict",
            "--json",
            "--final-profile",
            "mature",
            "--as-of",
            today.isoformat(),
        ],
    )
    result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-status.sh",
            "--strict",
            "--json",
            "--as-of",
            today.isoformat(),
        ],
    )
    parsed = {}
    try:
        parsed = json.loads(result["stdout"])
    except Exception:
        pass
    residue_audit = parsed.get("sources", {}).get("product_noncanonical_residue_audit", {})
    blocker_ids = {
        blocker.get("id")
        for blocker in residue_audit.get("blockers", [])
        if isinstance(blocker, dict)
    }
    strict_blocker_ids = {
        blocker.get("id")
        for blocker in parsed.get("strict_blockers", [])
        if isinstance(blocker, dict)
    }
    expect(
        unsupported_profile_result["exit_code"] == 2
        and result["exit_code"] == 1
        and parsed.get("status") == "needs-fix"
        and residue_audit.get("status") == "needs-fix"
        and residue_audit.get("copy_first_tool_count") == 0
        and residue_audit.get("blocker_count", 0) >= 1
        and "product-noncanonical-residue-blockers" in strict_blocker_ids
        and "product-noncanonical-items" in blocker_ids,
        "status-product-profile-blocks-noncanonical-residue",
        "unsupported final profile is rejected and the product status gate blocks noncanonical residues",
        {
            "unsupported_profile_exit_code": unsupported_profile_result["exit_code"],
            "exit_code": result["exit_code"],
            "status": parsed.get("status"),
            "strict_blocker_ids": sorted(strict_blocker_ids),
            "product_noncanonical_residue_audit": residue_audit,
            "stdout_sample": result["stdout"][:1200],
        },
    )


def test_regression_trend_from_json_contract():
    repo = copy_repo("regression-trend")
    fixture_rel = "artifacts/manifests/regression-trend-fixture.json"
    fixture_path = repo / fixture_rel
    fixture_payload = {
        "status": "pass",
        "suite": "full",
        "selected_test_count": 2,
        "full_test_count": 2,
        "result_count": 2,
        "slowest_results": [
            {
                "id": "slow-fixture",
                "test_fn": "test_slow_fixture",
                "duration_sec": 1.23,
                "status": "pass",
            }
        ],
        "results": [
            {"id": "fast-fixture", "status": "pass"},
            {"id": "slow-fixture", "status": "pass"},
        ],
    }
    fixture_path.write_text(json.dumps(fixture_payload, ensure_ascii=False, indent=2))
    result = run_cmd(
        repo,
        [
            "rtk",
            "bash",
            "tools/knowledge-regression-trend.sh",
            "--from-json",
            fixture_rel,
            "--json",
        ],
    )
    parse_error = ""
    try:
        payload = json.loads(result["stdout"])
    except Exception as exc:
        payload = {}
        parse_error = str(exc)
    expect(
        result["exit_code"] == 0
        and payload.get("read_only") is True
        and payload.get("regression_status") == "pass"
        and payload.get("selected_test_count") == 2
        and payload.get("result_count") == 2
        and payload.get("failed_count") == 0
        and payload.get("slowest_results", [{}])[0].get("id") == "slow-fixture"
        and not parse_error,
        "regression-trend-from-json-contract",
        "regression trend helper compacts existing regression JSON without rerunning full suite",
        {
            "exit_code": result["exit_code"],
            "payload": payload,
            "parse_error": parse_error,
        },
        repo,
    )

def test_health_summary_operational_fields():
    command = [
        "rtk",
        "bash",
        "tools/knowledge-health-summary.sh",
        "--json",
        "--as-of",
        today.isoformat(),
    ]
    result = run_cmd(root, command)
    parse_error = ""
    try:
        payload = json.loads(result["stdout"])
    except Exception as exc:
        payload = {}
        parse_error = str(exc)
    orphan = payload.get("changed_orphan_files", {})
    triage = payload.get("reviewing_triage", {})
    expect(
        result["exit_code"] in {0, 1}
        and payload.get("read_only") is True
        and payload.get("health_status") in {"ok", "needs-owner-review", "partial", "needs-fix"}
        and orphan.get("parse_error", "") == ""
        and "missing_registry_count" in orphan
        and triage.get("parse_error", "") == ""
        and "reviewing_count" in triage
        and not parse_error,
        "health-summary-operational-fields",
        "health summary exposes changed-only body coverage and reviewing triage fields for both green and review-pending states",
        {
            "exit_code": result["exit_code"],
            "health_status": payload.get("health_status"),
            "changed_orphan_files": orphan,
            "reviewing_triage": triage,
            "parse_error": parse_error,
        },
    )

def test_status_source_governance_summary():
    result = run_cmd(root, ["rtk", "bash", "tools/knowledge-status.sh", "--json"])
    check_result = run_cmd(root, ["rtk", "bash", "tools/knowledge-check.sh", "--dry-run", "--json", "--diagnostics"])
    expected_final_gate_command = "rtk bash ~/knowledge-hub/tools/knowledge-final-gate.sh --json --final-profile product"
    if today_source != "system-date":
        expected_final_gate_command = f"rtk bash ~/knowledge-hub/tools/knowledge-final-gate.sh --as-of {today.isoformat()} --json --final-profile product"
    parsed = {}
    check_parsed = {}
    parse_error = ""
    check_parse_error = ""
    try:
        parsed = json.loads(result["stdout"])
    except Exception as exc:
        parse_error = str(exc)
    try:
        check_parsed = json.loads(check_result["stdout"])
    except Exception as exc:
        check_parse_error = str(exc)
    sources = parsed.get("sources", {}) if isinstance(parsed.get("sources"), dict) else {}
    registry = parsed.get("registry", {}) if isinstance(parsed.get("registry"), dict) else {}
    owner_gates = parsed.get("owner_gates", {}) if isinstance(parsed.get("owner_gates"), dict) else {}
    check_selection = check_parsed.get("source_coverage_selection", {}) if isinstance(check_parsed, dict) else {}
    check_health = check_parsed.get("source_coverage_health", {}) if isinstance(check_parsed, dict) else {}
    check_source_check_health = check_parsed.get("source_check_health", {}) if isinstance(check_parsed, dict) else {}
    status_source_check_health = sources.get("source_check_health", {}) if isinstance(sources.get("source_check_health"), dict) else {}
    status_source_runtime = sources.get("source_runtime", {}) if isinstance(sources.get("source_runtime"), dict) else {}
    source_recovery_rows = sources.get("source_recovery_rows", []) if isinstance(sources.get("source_recovery_rows"), list) else []
    source_recovery_by_id = {
        row.get("source_id"): row
        for row in source_recovery_rows
        if isinstance(row, dict)
    }
    pcr02_docs_recovery = source_recovery_by_id.get("pcr02-project-docs", {})
    pcr02_tools_recovery = source_recovery_by_id.get("pcr02-project-tools", {})
    expect(
        result["exit_code"] == 0
        and not parse_error
        and check_result["exit_code"] == 0
        and not check_parse_error
        and sources.get("registered_count") == 18
        and sources.get("latest_coverage_manifest") == "artifacts/manifests/knowledge-hub-source-coverage-closeout-20260624.jsonl"
        and sources.get("latest_coverage_selection", {}).get("strategy") == "filename-yyyymmdd-sort-last"
        and sources.get("latest_coverage_selection", {}).get("selected") == "artifacts/manifests/knowledge-hub-source-coverage-closeout-20260624.jsonl"
        and sources.get("latest_coverage_selection", {}).get("candidate_count", 0) >= 1
        and sources.get("latest_coverage_selection", {}).get("dated_candidate_count", 0) >= 1
        and check_selection.get("selected") == "artifacts/manifests/knowledge-hub-source-coverage-closeout-20260624.jsonl"
        and check_selection.get("strategy") == "filename-yyyymmdd-sort-last"
        and check_health.get("registered_source_count") == 18
        and check_health.get("row_count") == 18
        and check_health.get("unique_source_count") == 18
        and check_health.get("missing_source_ids") == []
        and check_health.get("stale_source_ids") == []
        and check_health.get("duplicate_source_ids") == []
        and check_source_check_health.get("with_check_count") == 18
        and check_source_check_health.get("with_no_check_reason_count") == 0
        and check_source_check_health.get("missing_check_or_reason_ids") == []
        and check_source_check_health.get("non_rtk_check_ids") == []
        and status_source_check_health.get("with_check_count") == 18
        and status_source_check_health.get("executed") is False
        and status_source_runtime.get("status") == "pass"
        and status_source_runtime.get("scope") == "all"
        and status_source_runtime.get("registry_source_count") == 18
        and status_source_runtime.get("executed_count") == 18
        and status_source_runtime.get("source_check_health_executed") is True
        and len(source_recovery_rows) == 18
        and pcr02_docs_recovery.get("final_disposition") == "hub-canonical"
        and pcr02_docs_recovery.get("coverage_status") == "hub-canonical"
        and "hash-only-provenance" in pcr02_docs_recovery.get("coverage_classification", "")
        and "旧正文副本已按终态剪枝" in pcr02_docs_recovery.get("coverage_decision", "")
        and pcr02_docs_recovery.get("has_check") is True
        and pcr02_docs_recovery.get("has_no_check_reason") is False
        and pcr02_tools_recovery.get("check_contract_status") == "ok"
        and pcr02_tools_recovery.get("has_check") is True
        and pcr02_tools_recovery.get("coverage_status") == "hub-canonical"
        and registry.get("stale_review_after_count") == 0
        and registry.get("review_after_command") == "rtk bash ~/knowledge-hub/tools/knowledge-index-plan.sh --section review-date"
        and registry.get("review_after_near_due_command") == f"rtk bash ~/knowledge-hub/tools/knowledge-review-after.sh --as-of {today.isoformat()} --window-days 30 --json"
        and sources.get("source_check_report_command") == f"rtk bash ~/knowledge-hub/tools/knowledge-source-check.sh --scope all --as-of {today.isoformat()} --json"
        and owner_gates.get("owner_ready_package_coverage") == "0/7"
        and parsed.get("final_gate_command") == expected_final_gate_command,
        "status-source-governance-summary",
        "status JSON exposes source coverage, review_after and final gate recovery summary",
        {
            "exit_code": result["exit_code"],
            "parse_error": parse_error,
            "check_exit_code": check_result["exit_code"],
            "check_parse_error": check_parse_error,
            "registered_count": sources.get("registered_count"),
            "latest_coverage_manifest": sources.get("latest_coverage_manifest"),
            "latest_coverage_selection": sources.get("latest_coverage_selection"),
            "check_source_coverage_selection": check_selection,
            "check_source_coverage_health": check_health,
            "check_source_check_health": check_source_check_health,
            "status_source_check_health": status_source_check_health,
            "status_source_runtime": status_source_runtime,
            "stale_review_after_count": registry.get("stale_review_after_count"),
            "review_after_command": registry.get("review_after_command"),
            "review_after_near_due_command": registry.get("review_after_near_due_command"),
            "source_check_report_command": sources.get("source_check_report_command"),
            "source_recovery_row_count": len(source_recovery_rows),
            "pcr02_docs_recovery": pcr02_docs_recovery,
            "pcr02_tools_recovery": pcr02_tools_recovery,
            "owner_ready_package_coverage": owner_gates.get("owner_ready_package_coverage"),
            "final_gate_command": parsed.get("final_gate_command"),
            "expected_final_gate_command": expected_final_gate_command,
            "status": parsed.get("status"),
            "stdout_sample": result["stdout"][:1200],
        },
    )
